<div class="right-panel right-panel--blue">
    <div class="right-panel__back"><?php echo file_get_contents("parts/svg/close.svg"); ?></div>
    <div class="right-panel__wrapper">
        <div class="right-panel__part" data-panel="1">
            <div class="right-panel__heading" data-panel="heading">Political Economy</div>
            <div class="right-panel__text" data-panel="text">
                <p>Libya’s economy has undergone substantial change since the 2011 revolution as a result of the country’s political and security situation. A multitude of stakeholders and decisions have played a significant role in transforming the economic sector in a way that perpetuates conflict and violence.
                Before the revolution, Libya relied mainly on oil and gas extraction, which represented 95% of its export earnings and 99% of government income<sup>1</sup>. The country exported some 1.6 million barrels of oil per day<sup>2</sup>, trading principally with China, Italy, Germany, Spain and Turkey<sup>3</sup>. Libya’s economy used to be somewhat stable — a negligible gap existed between the parallel market and the official market rate of foreign exchange to the Libyan dinar (LYD) — despite significant mismanagement and corruption under the regime of Muammar Gaddafi. Public funds were used to pay for an inflated public sector, and 69% of total workers in Libya today are employed in the service sector while trade and agriculture account for one percent and six percent respectively<sup>4</sup>.</p>
                <p>During the 2011 uprising, oil profits plummeted. A year earlier, Libya’s GDP was USD 74.76 billion; in 2011, it fell to USD 34.7 billion. Though Libya’s foreign-exchange reserves were not directly affected after the revolution — they reached an all-time high of USD 125 billion in 2012 — they had fallen to USD 79 billion by 2017, the lowest in a decade<sup>6</sup>. This was largely attributable to the country’s deteriorating security. However, it was also a result of events that unfolded and economic decisions that were taken in the years following Gaddafi’s ouster.</p>
                <p>For eight years, the proliferation of non-state armed groups and their infiltration of governing bodies could to a large extent be attributed to the links between armed groups and the political elite. The former are capable of influencing economic decisions, diverting state funds and engaging in illicit schemes. The connivance of political actors and their dependence on non-state armed groups to secure control has gradually contributed to a dynamic where the state is perceived as complicit in the dispensation of violence. As a result, the legitimacy of governing political institutions has been undermined. Citizens, who rely on salaries, the provision of security, basic infrastructure, services and goods, have suffered severely, while the power of non-state armed groups has grown.
                Libya’s political economy deteriorated substantially after the 2014 battle in Tripoli between rival military alliances, which severely damaged key infrastructure such as the city’s international airport and the Brega oil facility, and triggered the evacuation of most of the international diplomatic, commercial and NGO communities. For example, oil revenues allocated through the Central Bank of Libya (CBL) allowed alternative power centres to thrive. Repeated violent takeovers of key oil infrastructure have been another drastic impediment for the economy.</p>
                <p>In addition, inadequate attempts at economic stabilisation post-2011, coupled with the blockade of Libya’s oil production in the summer of 2013, contributed to the widening gap between the official exchange rate and the black-market rate of the Libyan dinar against the US dollar. With the distrust of Libyans towards the banking sector persisting even today, more than half of Libya’s liquidity circulates outside the banking system, along with a persistent discrepancy between official and unofficial exchange rates. </p>
                <p>Austerity measures introduced in 2015 by the CBL in response to the economic crisis meant that some armed groups would no longer receive state salaries. This made some armed groups resort to devising new schemes to generate revenue. Although the business of illicit arms-trading had already blossomed in Libya after rebels ransacked Gaddafi’s arsenals in 2011, the “war economy” that emerged in 2014 is symptomatic of the country’s legitimacy crisis and a central cause of the state’s protracted dysfunction. </p>
                <p>Fuel subsidies remain in place, despite the state’s awareness that oil smugglers have capitalised on them to generate income through transnational smuggling networks. Several residents of the western coastal town of Zuwara, where a fuel-smuggling hub has emerged, have become extremely wealthy through their involvement in the illicit trade. The struggle for monopoly over the black-market business has often triggered fighting between armed groups as well as the closure of the Tunisia-Libya border, including the major land crossing of Ras Jedir.</p>
                <p>Moreover, some leaders of non-state armed groups have made substantial profits with Letters of Credit (LC) schemes via the CBL. This particular LC fraud consists of failing to import the declared goods. Instead, with the assistance of corrupt customs officials, the dishonest user produces fraudulent bills of lading in order to have the Libyan bank wire the LC’s dollar amount abroad, before importing part of that dollar sum in the form of physical cash and selling it on the black market at a much higher exchange rate than the official rate of ~1.30. </p>
                <p>Other armed groups have taken advantage of the international community’s response to human trafficking and migrant smuggling, simultaneously playing both sides of the lucrative trafficking and anti-smuggling markets. Prominent members of the Libyan coast guard and officials at detention centres are sometimes involved in their own human-trafficking rackets. Detention centre officials charge ransoms for migrants to be freed, only for the tipped-off Libyan coast guard to intercept their boats at sea and return them to captivity.</p>
                <p>The lack of transparency and the multitude of internal and external actors that influence Libya’s political economy present an enormous and complex challenge for those trying to improve the economy and enhance state legitimacy.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="2">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">February 2011</div>
                Libyan assets freeze</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 25 February, as the 2011 uprising gained ground, US President Barack Obama passed an executive order imposing sanctions on Gaddafi and his family. The US Treasury seized Libyan assets held in US banks, hoping it would prevent Gaddafi from using his finances to repress protesters. Some USD 29.7 billion was seized, most of it money deposited in one US bank. This sum represented almost half of Libya’s USD 67 billion sovereign wealth fund.</p>
                <p>A day after the US froze the regime’s assets, the United Nations Security Council (UNSC) adopted Resolution 1970, which mandated all states to freeze assets and economic resources owned or controlled by Gaddafi and his family. Today, an estimated USD 50 billion is withheld worldwide, though exact figures remain undetermined.</p>
                <p>Although UNSC Resolution 1973 states that the frozen assets “shall at a later stage be made available to and for the benefit of the people”, they have not been released due to Libya’s political divisions and chronic instability. Since 2011, factions from Libya’s consecutive governments have called for the freeze to be lifted. In November 2018, the Libyan Investment Authority (LIA), which is the country’s sovereign wealth fund, claimed that interest and dividends on holdings frozen under UN sanctions in Belgium at Euroclear Bank had not been frozen, but had instead been paid to “unknown beneficiaries”. This underscores the importance of maintaining the asset freeze to safeguard a large portion of Libya’s wealth as long as public funds continue to be misappropriated and used to fuel conflict.</p>
                <p>At the time, the asset freeze initiated by the US signalled an important change in its approach to the Libyan conflict and highlighted its intention to use all available means to diminish Gaddafi’s ability to use violence. It was also one of the first internationally coordinated efforts to pave the way for intervention in Libya under the so-called Responsibility to Protect. Seven years later, the international community is still responsible for protecting the frozen assets, given the current polarised environment. Moving forward, it is important for the international community and Libyan government officials to address the issue of interest payments on the frozen funds. This is key, especially since the UN Panel of Experts concluded in 2017 that payments on interests that flow to unknown beneficiaries could be contributing to Libya’s instability.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="3">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">2011 to Present</div>
                Land and property rights</div>
            <div class="right-panel__text" data-panel="text">
                <p>Early in the 2011 uprising, Libya’s novice transitional lawmakers faced the contentious issue of land and property rights. Gaddafi’s legacy and his manipulation of land and property as a tool to tamp down political dissent and reward supporters meant that, once he was gone, a complex tangle of ownership disputes emerged. </p>
                <p>Some influential members of Libya’s interim National Transitional Council (NTC) and revolutionary armed groups claimed to have had their properties confiscated during Gaddafi’s regime. Law Number 4 of 1978 took buildings and apartments away from their owners, and handed ownership to their tenants. Although Gaddafi’s son, Saif al-Islam, established a property compensation committee in 2007, it needed time to understand the complex circumstances of the current occupants and address the compensation of aggrieved former owners.</p>
                <p>The disputes led to the establishment of the League of the Property Owners Harmed by the Rule of the Oppressor, or Rabitat al-Mulak al-Mutadarariyn min Hukm al-Taghyat, also known as The Rabitat, a group of former owners lobbying for the restitution of their property, or for adequate compensation. This complex situation, together with the extended families of the original tenants occupying the premises over the four decades of Gaddafi’s rule, were a source of instability and grievance in the immediate aftermath of the 2011 revolution.</p>
                <p>Attempts to resolve the issue peacefully were often blocked by influential politicians and non-state armed groups. They considered abandoned or captured property and land an adequate compensation for their participation in the revolution. Today, many properties and land are still occupied and bitterly disputed across Libya.</p>
                <p>Moreover, several business owners and leaders of non-state armed groups, with their ability to access foreign currency at official rates, are involved in arbitrage schemes, thereby benefitting from the volatility of the black-market exchange rates. In essence, land and property, priced in dinars, is purchased with US dollars obtained at an official rate, when the dinar depreciates in the parallel market.</p>
                <p>The issue of property rights is a divisive legacy of the Gaddafi regime, one that has been amplified by the failure to implement effective reforms since 2011. A prerequisite to resolving the issue is strong reform-oriented fiscal and macroeconomic policies aimed at enhancing the economy and building public trust. However, the issue of disputed land and property rights can only be resolved through an independent judiciary and the proper functioning of the Compensation Committees.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="4">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2013</div>
                Jadhran blockades the ports of Es Sider, Ras Lanuf and Zueitina</div>
            <div class="right-panel__text" data-panel="text">
                <p>In July 2013, Ibrahim Jadhran, the head of the Petroleum Facilities Guard (PFG) from Ajdabia, triggered what is now known as Libya’s second civil war. The young militia leader, from the Magharba tribe, used federalist and anti-Muslim Brotherhood rhetoric to justify the takeover and blockade of Es Sider, Ras Lanuf and Zueitina, three of Libya’s most vital oil terminals on the Mediterranean, by his PFG faction. To end the blockade, he demanded that the General National Congress (GNC) cede power to Libya’s eastern region of Cyrenaica, especially in regard to selling oil. Mustafa Sanalla, the head of the Tripoli-based National Oil Corporation (NOC), estimated that the losses incurred due to Jadhran’s blockade amounted to some USD 30 million per day.</p>
                <p>Jadhran was shrewd in his ability to use grievances arising from Gaddafi’s historical negligence of eastern Libya. The move won him a degree of popular support. Jadhran even went as far as to declare an eastern government of his own and hired Canadian lobbyist Ari Ben-Menashe to advocate for him abroad. One of the lobbyist’s alleged goals was to seek both the US and Russia’s endorsement of a federalist structure that would grant Cyrenaica autonomous status. Jadhran also proactively sought to sell oil outside the legitimate NOC channels, thereby establishing a parallel oil and gas corporation based in Benghazi in November 2013.</p>
                <p>The precedent of selling Libya’s oil, which then constituted 60% of Libya’s GDP, via unofficial channels was considered disastrous. It prompted Prime Minister Ali Zeidan to threaten to attack oil tankers carrying crude shipments off the Gulf of Sidra. Despite the warnings, Jadhran attempted to sell crude oil multiple times: in August 2013, January 2014 and March 2014. While Libya’s GNC-controlled navy foiled these attempts, in March 2014 the UAE-registered tanker, The Morning Glory, successfully departed from Libya’s oil port carrying over USD 30 million in crude oil. The owner and the manager of the ship were based in the UAE. The March 2014 episode would be merely the first of a series of incidents whereby actors linked with the UAE would attempt to help eastern Libyan factions conduct sales of crude oil outside Tripoli’s purview.</p>
                <p>Its departure having alarmed the US, the UK and Italy, The Morning Glory was later boarded by the US Navy, which ensured its illicit cargo was returned to Libya. Nevertheless, the GNC used Zeidan’s failure to thwart the attempt as an excuse to force him out. The anti-Islamist faction installed Abdullah al-Thinni in his stead.</p>
                <p>Zeidan fled to Germany the night he was ousted, and the GNC mobilised Misrata’s Libya Shield to attack the oil ports in December 2014 amid an attempt to expel Jadhran. After substantial damage to the oil infrastructure resulting from the fighting, the revolutionary-leaning Libya Shield coalition retreated. From May 2014 until late 2015, Field Marshal Khalifa Haftar and Ibrahim Jadhran were de-facto allies. The military commander began turning on Jadhran in the last few months of 2015. The oil ports remained blockaded by Jadhran until September 2016. Haftar had managed to convince the Magharba tribe that the so-called Libyan National Army (LNA) would offer them better socio-economic treatment than Jadhran. The deal paved the way for the LNA to seize control of the facilities. Proceeds from oil sales from the now-reopened ports continued to flow through Tripoli’s Central Bank of Libya (CBL).</p>
                <p>Jadhran’s blockade of Libya’s key oil ports had a heavy economic toll in Libya. Foreign exchange reserves plummeted from USD 108 billion in 2013 to USD 57 billion in 2016. Seeing the reserves dwindling fast, speculators concluded that the official exchange rate was becoming increasingly unsustainable. To make a profit, those speculators decided then to “front run” the trend by selling US dollars on the black market at a more expensive rate against the Libyan dinar. The dollars they sold had in fact been purchased cheaply from the state itself via fraudulent LCs.</p>
                <p>The inability of the UN to effectively manage and resolve the oil blockade caused many Libyans to become disillusioned with the ongoing political process. In addition to the inflation resulting from the dysfunctional economy, families had also to endure a shortage of fuel and cooking gas, as well as frequent electricity cuts and inoperative medical services.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="5">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">September 2014</div>
                The HoR fires CBL Governor al-Kabir and appoints al-Hibri in Bayda</div>
            <div class="right-panel__text" data-panel="text">
                <p>In September 2014, the Tobruk-based House of Representatives (HoR) fired Sadiq al-Kabir, the governor of the Central Bank of Libya (CBL) in Tripoli. His deputy, Ali Salim al-Hibri, was appointed interim governor in his place. The HoR called on the attorney general to launch an investigation of al-Kabir’s involvement in “financial irregularities”. This was arguably the first time that the political and institutional divide directly impacted the leadership of the CBL, an institution that is meant to be both neutral and centralised.</p>
                <p>The crisis of legitimacy between the GNC-approved cabinet in Tripoli and the HoR required separate budgets for the two rival entities and their respective governments. Al-Kabir’s perceived preference for the administration in Tripoli — although, under his leadership, the CBL refused to approve expenditures for either the GNC or the HoR — led to his dismissal and to the split of the CBL into two entities.</p>
                <p>Following his CBL appointment, al-Hibri was briefly recognised by the IMF in July 2015 as the official governor of the CBL, before the Libyan Political Agreement (LPA) reverted that role to the Tripoli-based governor. The LPA was signed in December 2015, three months before the new Western-backed Government of National Accord’s (GNA) arrival in Tripoli by ship.</p>
                <p>Subsequently, in May 2016, sources from the eastern CBL revealed that al-Hibri’s signature was on new Libyan banknotes that had been printed in Russia and were circulating throughout eastern Libya. Though the eastern CBL stressed that there would be no dissimilarities between the country’s banknotes, the US embassy declared the Russian-made notes to be counterfeit and said they could “undermine trust in Libya’s currency and the CBL’s ability to manage monetary policy”. In November 2018, a representative of the eastern CBL said that it had received some 9 billion dinars worth of banknotes printed in Russia. Some merchants in western Libyan cities such as Misrata and Tripoli did not accept this currency, which differs from the UK-printed banknotes issued by the Tripoli-based CBL by bearing the respective governors’ signatures. However, the Tripoli-based CBL itself accepted the Russian-manufactured banknotes as legitimate. In effect, it tolerated complex schemes used by eastern Libyan authorities to convert Russian-manufactured banknotes into US dollars through Tripoli’s black market. Such operations can be carried out only if certified checks for large amounts of dinars are accepted by Tripoli black-marketeers. Separately, the US banknotes had to be flown back to eastern Libya, a transfer that could be performed only with assistance from key GNA-aligned militias. This is a reminder that the eastern Libyan authorities could finance themselves only with the quiet acquiescence or help of their nominal rivals in Tripoli.</p>
                <p>In the future, a political deal and unification of the rival institutions will be contingent on conducting an independent audit and improving the transparency of financial decisions in order to avoid fund mismanagement. In the absence of a unified government, the CBL is largely financing fiscal spending through its reserve, which fell from USD 108 billion in 2013 to USD 57 billion by the end of 2015. There is a modicum of agreement among rival factions and governors to unite the CBL. But each faction, along with its respective foreign sponsors, is intent on achieving a unification to its own advantage.</p>
                <p>Because of CBL governor al-Kabir’s history of proximity to the Muslim Brotherhood, the eastern Libyan authorities will remain intent on forcing him out or weakening his grip on the country’s hard-currency reserves. Al-Kabir has accommodated the eastern faction in many crucial regards, but this is unlikely to diminish his political enemies’ desire to dislodge him. Indeed, Libya’s anti-Islamist camp is interested in achieving total control over state coffers. So far, Washington’s support for al-Kabir has been the main reason he has been able to hold on to his post for more than seven years. This dynamic may change in the foreseeable future, as the US retrenchment continues vis-à-vis Libya.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="6">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August 2015</div>
                Rise in illicit foreign currency and Letters of Credit fraud</div>
            <div class="right-panel__text" data-panel="text">
                <p>In late August 2015, Libya’s Audit Bureau issued a report listing 42 Libyans, 25 Libyan companies and twelve foreign companies accused of smuggling foreign currency abroad through fake import transactions. The companies had used Letters of Credit (LCs), approved by the Central Bank of Libya (CBL), for the import of essential goods such as food, medicine and medical equipment, but had instead shipped empty containers into Libya’s ports. The scheme was commonly used to leverage the exchange-rate difference between the Libyan dinar and foreign currencies.</p>
                <p>The rising discrepancy between the black-market exchange rate and the fixed official rate of the dinar against the US dollar created an increasingly lucrative scheme, especially when the parallel market rate climbed to LYD 10 to USD 1 in 2017, as opposed to the official rate of LYD 1.3 LYD to USD 1. The complicity of government and banking officials and their willingness to facilitate access to LCs in exchange for security meant that armed groups began competing for the rewards of territorial control in Tripoli, in addition to carrying out extortion and kidnappings.</p>
                <p>The austerity measures introduced by the CBL in 2015 translated into deep cuts. Fiscal spending declined by 32.7% in 2015, while public sector wages were stabilised and food subsidies greatly reduced. In tandem, capital expenditure also decreased by half a percent during that period. Used to import goods, the LCs were almost impossible to obtain through official channels, as the CBL sought to slow down the erosion of its foreign cash reserves. Even legitimate LCs for essential goods were stalled as a result of arbitrary CBL policies.</p>
                <p>Part of al-Kabir’s 2015 drive towards more austerity stemmed from his desire to retain US support and thus keep his post. The quid pro quo largely worked. By reducing the funds allocated to hard-line militias, the CBL in Tripoli helped turn the province of Tripolitania into an environment in which the UN-backed Skhirat peace talks would stand a greater chance at succeeding. During the key year of 2015, Washington’s influence was instrumental in forming the UN-backed Government of National Accord of Fayaz al-Serraj.</p>
                <p>The shrinking of government-approved expenditures meant that not all armed groups could remain on the state’s payroll. This can be correlated with a rise in LC fraud in 2015, which was one of several corrupt methods of making up for lost cash.</p>
                <p>Another way to profit from the growing exchange-rate gap that year was a debit-card scheme that became increasingly attractive as the liquidity crunch worsened. It entailed using Visa cards issued by Libyan banks to withdraw cash abroad at official rates, then returning to Libya and selling the foreign currency through the black market. Both the LC fraud and debit-card scheme were major factors in the ability of armed groups to access state funds in exchange for providing security to banks.</p>
                <p>After August 2015, Libya’s deeply rooted parallel economy succeeded supplanting banks with a parallel market, as citizens were increasingly forced to rely on the latter to access cash. Although the CBL attempted to address cash shortages by providing allowances to Libyan families at official rates, there was a great risk that foreign currency would end up being sold through the black market.</p>
                <p>There are two major impediments to a reunified, functional CBL. First, the international community tends to support the most powerful militias in Tripoli because day-to-day security and counterterrorism measures are provided by those very actors. The latter are involved in the embezzlement of LC money, and use their security role as insurance against any potential move by the UN that could punish them for their illicit activities. The second obstacle is the fact that the armed groups exploiting the dysfunction of the CBL have accomplices in the official banking system.</p>
                <p>The international community must work with Libya to unify the CBL. Both the Ministry of Finance and the CBL should be supported to develop home-grown economic, financial and administrative reforms aimed at eliminating the black market and ending the manipulation of LCs and debit cards. Most importantly, the CBL should adopt measures aimed at gradually closing the gap in the exchange rate between the black market and the official market and at building public confidence in the country’s financial and monetary system.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="7">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October 2017</div>
                Haftar sets up the Military Authority for Investment and Public Works</div>
            <div class="right-panel__text" data-panel="text">
                <p>In October 2017, Khalifa Haftar, head of the Libyan National Army (LNA) in the east, issued a decree that broadened the mandate of the Military Authority for Investment and Public Works (MAIPW), essentially giving the LNA a “legal mandate” to manage any service and manufacturing project in the areas under its control.</p>
                <p>An administrative committee was formed to oversee the MAIPW’s activities and the diversification of its portfolio, with Mohammed Madani Abdul Hafiz al-Fakhri, the former interior minister of the al-Bayda government, appointed as board chairman. Haftar put al-Fakhri in charge of emulating the Egyptian model of militarising the local economy. Within that context, Haftar had his son Uqba lobby Western capitals to achieve political control of part or all of Libya’s public funds, the foreign reserves of the Central Bank and the country’s sovereign wealth fund, the Libyan Investment Authority (LIA). The LNA has been determined to raise hard-currency capital as part of its MAIPW initiative.</p>
                <p>In recent years, the MAIPW has proactively expanded its influence. In a visit to the Oujla municipality in July 2017, al-Fakhri explained that the LNA was keen to take over agricultural projects in the city’s vicinity, as well as Gaddafi’s former properties in the region. A similar modus operandi was employed in most of the LNA-controlled areas. In October 2017, Haftar ordered the closure of Tobruk’s port, citing endemic corruption and illicit smuggling at the port due to a lack of security. Most ships were re-routed to Benghazi, where the LNA had taken over port security and customs.</p>
                <p>The MAIPW’s monopoly over exports and projects was bound to trigger internal struggles over the spoils, and they erupted in July 2018. In a leaked phone call, Mahmoud Werfalli — commander of the LNA’s elite unit, Al-Saiqa, who is wanted by the International Criminal Court (ICC) for war crimes — accused al-Fakhri of stealing large sums of money. A few days later, Werfalli stormed the headquarters of the MAIPW in Benghazi, seized some documents and left.</p>
                <p>Nevertheless, the MAIPW is still expanding its scope of operations and business interests with the support of Haftar and his sons. In September 2018, several news outlets reported that a Togo-flagged vessel docked at the port of Brega, loaded with 5,000 tons of scrap metal, allegedly in a deal struck between the MAIPW and Turkey.</p>
                <p>The setup of the MAIPW not only expands the role of both Haftar and the LNA into the economic sphere, but further divides the economic landscape between Libya’s east and west. Funds created through the MAIPW could also be used to finance the protraction of the conflict, acting as an impediment for political dialogue that would place the military under civilian authority. Finally, space for civilian projects and activities may also shrink as the LNA penetrates a space that could have been filled by the private sector. This economic model may exclusively benefit segments of society that are connected to the LNA, thus deepening the economic disenfranchisement of those excluded.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="8">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August 2017</div>
                Interrupting Mediterranean migration flows from Sabratha, and the creation of a lucrative smuggling and anti-smuggling market</div>
            <div class="right-panel__text" data-panel="text">
                <p>In October 2017, fighting erupted between rival armed groups in Sabratha, causing thousands of families to flee the coastal city. A deal was allegedly struck between Italy and one of Sabratha’s armed groups — the 48th Battalion, headed by Anas Dabbashi, and sanctioned by the Government of National Accord (GNA) — to stem migration flows to Europe from Sabratha’s coast. The alleged deal caused havoc in the city and disrupted the fragile peace.</p>
                <p>Sabratha was widely regarded as a hub for human trafficking in Libya. Italian politicians were under pressure to curb migration ahead of the elections in Italy. In July 2017, the 48th Battalion in Sabratha began coordinating with the Zawiyah refinery coast guard, headed by Abdulrahman Milad — nicknamed al-Bija — to stop migrant boats departing Libyan shores and, when needed, to intercept them. That month saw a 50% drop in migrants arriving in Italy compared to the previous July.</p>
                <p>What surprised most observers, however, was the cooperation between Dabbashi and al-Bija, as both were former rivals in the business of human trafficking and migrant smuggling. This provides a reminder that Libyan actors involved in illicit activities often follow the most efficient arrangement from an economic perspective, rather than one based on their ideology or personal resentment.</p>
                <p>Before August 2017, Dabbashi had been cited several times in the UN Panel of Experts’ report on Libya as one of the main actors involved in the smuggling of migrants. Though the alleged deal between Italy and Dabbashi was never acknowledged by Italy or the GNA, the cooperation scheme weakened other armed groups in Sabratha which did not financially benefit from being involved in those activities. Perhaps even more so than the prospect of financial reward, the armed groups that attacked Italy’s partners in Sabratha were triggered by considerations of legitimacy. Indeed, the Italian government had arranged for several militias to receive official salaries from GNA ministries. In Libya, state salaries, even when relatively low, are perceived as a source of officialdom, prestige and political legitimacy.</p>
                <p>This dynamic precipitated a full-fledged battle that ended with Dabbashi’s forces being ousted from Sabratha and led to at least five deaths and over 40 people injured.</p>
                <p>A few months later, in November 2017, the broadcast of a CNN report implicating Libyans in acts of slavery sparked international outrage and put Libya in the spotlight as a brutal transit country for migrants. International consensus on the viability of migration policies reliant on the interception of migrants at sea and confinement of migrants in detention centres allowed actors such as Dabbashi and al-Bija to further benefit from the anti-immigration and smuggling markets that they were engaged in simultaneously. Though migrant departures from Libya declined by about 80% from 2017 to 2018, questions remain about the ethical aspects of policies implemented by the international community to curb arrivals to Europe.</p>
                <p>Indeed, this issue highlights the importance of the international community’s migration policies, especially the legitimacy that actors can gain through partnering with international organisations. Al-Bija epitomises this dynamic. Despite being responsible for the majority of interceptions off the coast of Zawiyah and receiving EU equipment, he was a smuggler himself. It is important for the EU to revise its policies based on this information, and to ensure rigorous scrutiny of the local actors that it partners with on immigration control. </p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="9">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August 2017</div>
                Fuel-smuggling “kingpin" Fahmi Salim arrested in Zuwara</div>
            <div class="right-panel__text" data-panel="text">
                <p>In late August 2017, the so-called “king of smuggling” Fahmi Salim Ben Khalifa was arrested by a Salafi-leaning group in Zuwara called the Muqanein (the masked men) and handed over to the Special Deterrence Force in Tripoli. Libya’s National Oil Corporation (NOC) applauded the arrest. Meanwhile, many more fuel smugglers, both nationally and internationally, still roam free.</p>
                <p>Ben Khalifa, who comes from the coastal town of Zuwara, has been renowned for his involvement in smuggling fuel and illicit goods across the sea and the Tunisian border since the Gaddafi era. He was sentenced to 15 years in prison by the former regime before escaping during the uprising of 2011. Ben Khalifa lent his support to the revolutionaries from Zuwara, donating large sums of money to pay for the treatment of wounded fighters. He later tried to build social legitimacy by supporting local institutions such as the town’s football club, and contributing to the construction of Zuwara’s key infrastructure.</p>
                <p>Through his transnational links, Ben Khalifa was primarily involved in a complex fuel-smuggling scheme that involved sending ships loaded with fuel off the Libyan coast. They were then unloaded onto other vessels and sent to the coast of Malta, where they became “certified” imports from Saudi Arabia and sold to Italian oil companies.</p>
                <p>According to some politically motivated Libyan figures, some USD 4 billion worth of Libyan fuel was sold in Italy through this scheme. However, it is important to note that this figure, which has been cited by several respectable outlets, is impossible. The amount of wealth stolen from Libya in the form of smuggled gasoline and diesel and exported to Italy has never exceeded USD 150 million per annum.</p>
                <p>Although the NOC has repeatedly called on European states to sanction more fuel smugglers, the international community has yet to take a unified stance to discourage non-state actors from smuggling fuel. According to the NOC, 30 to 40% of fuel refined in Libya or imported ends up being stolen or smuggled. In addition, about 83% of gas stations in west Libya don’t exist, yet continue to receive fuel deliveries.</p>
                <p>The ramifications of fuel smuggling are perhaps most evident at the Tunisia-Libya border crossing in Ras Jdeir, where the World Bank estimates that flows from Libya into Tunisia are valued at approximately USD 148 million. Since 2011, Libyan armed groups have competed for access to smuggling profits at this border. A controversial Fuel Crisis Committee — which advertised its anti-fuel smuggling activities but is rumoured to being a front for smugglers — was recently dissolved in the absence of a unified Libyan government response. Although it often exaggerated its accomplishments, the committee’s anti-smuggling efforts proved moderately successful by late 2018. One likely reason that the committee was dissolved by authorities in Tripoli was the latter’s desire to soothe relations with their Tunis counterparts, who were demanding a resumption of the smuggling activity. Indeed, the area around the Tunisian town of Ben Gardane relies heavily on the informal fuel trade with Libyan smugglers, and in the summer of 2018 protests broke out against the blocked border and the loss of the illicit fuel economy in Ben Gardane, increasing tensions between the neighbouring governments.</p>
                <p>The fuel-smuggling industry costs Libya’s economy between USD 450 million and USD 750 million annually. Those responsible are not only armed groups, but also employees from companies that are responsible for distributing fuel to gas stations.</p>
                <p>Lastly, it is important to note that refined fuel imported by Libya continues on to other destinations, including Niger, Chad and Egypt. The illicit activities conducted by eastern Libyan actors receive less coverage than their western counterparts only because, as a result of the authoritarian governance of Field Marshal Haftar, Cyrenaica is less accessible to researchers and analysts than Tripolitania. However, the absence of information doesn’t mean that eastern Libya isn’t affected by fuel smuggling.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="10">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">March 2018</div>
                Salamé describes Libya’s shadow economy as its biggest problem</div>
            <div class="right-panel__text" data-panel="text">
                <p>According to the UN, by 2018, almost 1.1 million Libyans needed urgent humanitarian assistance. This was despite Libya’s oil production averaging 1 million barrels a day in 2018, and the country topping the IMF’s list for real GDP growth for the same year. In essence, the lucrative war economy has thrived while progress on the political and security fronts has stalled, preventing macro-economic improvements from trickling down to the streets.</p>
                <p>In an interview in March 2018, Ghassan Salamé, Special Representative of the United Nations Secretary General (SRSG) to Libya, publicly acknowledged that the economic track was inextricably linked to the political one, and declared that the most important challenge for Libya was its “shadow” economy. This is significant because it was the first time that an SRSG assigned to Libya overtly stated that a political deal would be contingent on an economic overhaul. Salamé said he sought to persuade international actors to support a political deal and also “to put an end to all kinds of trafficking in this country. Not only trafficking in human beings, but also trafficking in fuel, subsidised [goods], and in drugs.” Finally, the SRSG also recognised that Libya’s armed groups needed to be included in plans for reform since they have been manipulating the system for financial gains.</p>
                <p>Salamé asserted that a “determined effort” by the UN as well as international financial institutions and foreign powers was needed to address Libya's economy. Throughout 2018, the World Bank and the IMF supported efforts aimed at unifying the two different Central Banks of Libya (CBL), and offered advice to manage inflation and promote economic reforms. These efforts have successfully prevented a complete split of the CBL.</p>
                <p>Salamé’s public acknowledgement signalled a shift from the UN’s approach, which usually compartmentalises the economic, security and political tracks. Recognising that a political deal is predicated on some form of redistribution of Libya’s oil wealth is an important takeaway that will go a long way towards improving the prospects of achieving a successful political dialogue. </p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="11">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">June 2018</div>
                The UN Security Council imposes sanctions on smugglers</div>
            <div class="right-panel__text" data-panel="text">
                <p>In June 2018, the United Nations Security Council (UNSC) for the first time imposed sanctions on six individuals involved in human trafficking and migrant smuggling in Libya. The rationale behind the sanctions, pushed for by the Netherlands, was to contribute to improve “the lives of refugees and migrants in Libya and prevent them from making the dangerous journey across the Mediterranean.”</p>
                <p>One of the human traffickers sanctioned, Abd Al Rahman Milad (nicknamed al-Bija), heads the Zawiyah’s regional coast-guard unit, which was financed by Italy and trained and equipped by the EU as part of efforts to stem migrant departures from Libya. Al-Bija’s unit was responsible for the majority of interceptions carried out by the Libyan coast guard off the western coast. Another individual included on the UN sanctions list is Mohammed Koshlaf (nicknamed Gsab), who was also involved in migrant smuggling through the control of a detention centre in Zawiyah. He often colluded with al-Bija. The latter would intercept migrants off the coast of Sabratha and transfer them to Gsab’s detention centre. Detained migrants were given the option of paying a fee to get out and depart Libya again by boat. In essence, Gsab and Al-Bija worked both for and against the EU’s efforts to stem migrant smuggling.</p>
                <p>Koshlaf was also heavily involved in the procurement of fuel for smugglers. Operating with his brother Walid — who wasn’t sanctioned despite handling the operation’s finances — Gsab leads the Nasr Brigade. It controls Zawiyah’s oil refinery, which is also — crucially — the facility into which billions of dollars’ worth of gasoline and diesel is imported from Italy and other countries. However, the brothers’ authority was contested by rival groups in Zawiyah, especially by the Awlad Saqr family, who run their own smuggling business. This has sparked fighting between the groups, with migrants trapped in detention centres caught up in the clashes. So far, it is unclear whether the financial sanctions and travel ban imposed on al-Bija and Gsab will have a tangible impact. It is important to note that these sanctions exclusively target individuals within a network, who can easily be replaced.</p>
                <p>The sanctions on Gsab have had no impact on his day-to-day behaviour, as he continues to play a key role in human smuggling, fuel smuggling and local security.</p>
                <p>The local actor who provides Gsab with political cover is a Zawiyan militia leader known as Ali Abu Zuriba. He is allied with a militia known as the Tripoli Revolutionary Battalion. Meanwhile, Gsab has pledged his allegiance to the LNA. One might note that, despite the LNA’s anti-smuggling rhetoric, it may ally itself with smuggling kingpins such as Gsab for the purpose of prevailing over Islamist militias. If this scenario ensues, smuggling activities in Zawiyah will continue even if it falls under the supervision of the LNA.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="12">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2018</div>
                Attempts to sell oil by eastern-based National Oil Corporation after closure of ports by Libyan National Army</div>
            <div class="right-panel__text" data-panel="text">
                <p>In June 2018, an alliance formed by Ibrahim Jadhran and remnants of the Benghazi Defense Brigade (BDB) captured the oil ports of Ras Lanuf and El Sidra from Haftar’s Libyan National Army (LNA), causing not only their closure but also a production loss of 240,000 barrels per day. Two weeks later, the LNA mobilised to recapture the oil terminals, which they eventually did. Haftar refused to hand back control of Libya’s oil ports to the state-owned National Oil Corporation (NOC) based in Tripoli, choosing instead to turn them over to an eastern-based parallel NOC. Haftar justified this move by expressing his frustration with the Central Bank of Libya (CBL), accusing it of financing “militias” and “terrorists", and blaming the Government of National Accord (GNA) for its alleged dependence on Tripoli-based armed groups for security.</p>
                <p>In practice, eastern officials had shut the ports of Zueitina and Hariga, stopping legitimate NOC tankers from loading oil at the facilities. Oil production, which stood at slightly more than a million barrels per day, was slashed to 150,000 barrels per day. The move was seen as a political gambit on Haftar’s part to sell oil outside the official channels of the Tripoli-based NOC. In response, NOC head Mustafa Sanalla sent communiqués to both the UN and foreign embassies, warning that the illicit sale of oil by a parallel NOC in the east could lead to Libya’s further fragmentation, if not its partition. Sanalla also likened Haftar’s actions to Jadhran's in 2013.</p>
                <p>The standoff was resolved a few days later when the US stepped in, asking Haftar to withdraw and signalling its intention to help keep al-Kabir in his post. On 11 July, Haftar ceded control of the oil ports to the legitimate Tripoli-based NOC. Rumours swirled that a strongly worded letter from US President Donald Trump had prompted Haftar to back down. Still, Libyan authorities agreed that both branches of the CBL would have to be audited to ensure the transparency and accountability of their spending.</p>
                <p>This ought to provide the perfect opportunity to move towards the unification of other divided institutions in Libya, while also promoting confidence and transparency. Ideally, an independent audit could create a conducive environment for political dialogue to increase the chances of success. In actuality, however, no progress has been made in almost nine months since the UN promised to enforce an independent audit on both central banks. It is unlikely that either audit will be conducted on a genuine, valid basis within the foreseeable future. There are two possible reasons for this outcome. Firstly, the CBL in Tripoli helped fund unsavoury anti-Assad actors in Syria in 2012 and 2013. At the time, the US largely approved of those activities because President Bashar al-Assad was not expected to hold on to power. It is unlikely that CBL activities during that period will ever be examined by independent auditors. Secondly, the rogue CBL subsidiary in al-Bayda engaged in several illicit schemes for the purpose of funding Haftar’s army, among other things. Now that Haftar is close to victory and benefiting from the support of numerous foreign states, it is unlikely that a genuine audit will risk disclosing the various financial abuses committed by Haftar and his Libyan allies.</p>
                <p>The alleged intervention of the US president highlighted the commitment of the international community to thwarting illegitimate oil sales outside the jurisdiction of the official NOC, and preventing the Libyan economy from suffering the consequences of yet another blockade — which in this instance cost it USD 69 million per day. As a result, it is unlikely that Haftar will attempt a similar move in the immediate future.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="13">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">September 2018</div>
                Economic reforms and application of a service fee on foreign currency transactions</div>
            <div class="right-panel__text" data-panel="text">
                <p>By empowering rent-seeking armed groups to provide security to Tripoli, the Government of National Accord (GNA) has made some groups’ leaders rich while excluding others. Towards the end of August 2018, an attack by Tarhuna’s 7th Infantry Kani Brigade on Tripoli gave several armed actors who had been excluded from sharing the spoils an unforeseen opportunity to intervene and try to dislodge the armed groups enjoying supremacy in central Tripoli. The fighting followed a strong UN statement that condemned interference in Libya’s sovereign institutions and implicitly referred to Tripoli’s armed groups charged with keeping the peace. The UN took the lead in negotiating a fragile ceasefire, which was breached many times. The battle ended in a truce, with a death toll of 117 people, many of them civilians, and nearly 600 wounded. The ceasefire conditions included the institutionalisation of security and tangible steps to introduce economic reforms.</p>
                <p>In September 2018, after a three-month delay, the GNA finally introduced economic measures related to foreign-currency exchange, as well as plans to lift subsidies. In practice, the GNA imposed a 184% service fee on the official exchange rate for foreign-currency purchases in both commercial and personal transactions. The economic reforms led to a fall in the parallel-market rate — from LYD 7 to USD 1 in October 2018 to LYD 4.5 to USD 1 in January 2019. However, instead of being an official devaluation, the service-fee model created a second alternative rate for transactions which armed groups and select politicians could still profit from.</p>
                <p>The tax on the purchase of foreign currency provided much-needed relief to Libyan citizens buying everyday goods, as the parallel-market rate of the dinar against the US dollar fell. It is important for the UN to support the GNA in building on this success by establishing a timeline for the full implementation of economic reforms, especially in removing subsidies.</p>
                <p>Finally, it is too early to judge the effectiveness of the economic reforms because an integral reduction in fuel and goods subsidies has not yet been implemented. The latter may seem unrealistic, not least because lifting subsidies may result in most citizens being unable to afford common goods, even after improvements both in access to liquidity and in prices. With no date specified for implementation yet, lifting the subsidies may remain on the back burner.</p>
                <p>In any case, phasing out fuel subsidies will not help combat fuel smuggling. Indeed, a hike in the retail price will have no impact on the behaviour of armed groups involved in the theft of gasoline and diesel from the state. Those militias are now deeply entrenched and benefit from the complicity of employees in state institutions, including in the National Oil Company.</p>
                <p>Implementing economic reforms in tandem with a move towards unification of the CBL is paramount, too, as it would provide an opportunity to establish a longer-term fiscal policy and account for expenditure outside the budget, which both the Tripoli-based CBL and the World Bank have struggled to account for. Currently, the existence of a parallel government implies that official figures released by the CBL do not actually reflect overall spending, while the Russian banknotes that the eastern CBL has distributed limits the scope of economic reforms because they remain unaccounted for in the overall budget of the CBL.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="14">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">November 2018</div>
                Sanctions on Salah Badi</div>
            <div class="right-panel__text" data-panel="text">
                <p>In November 2018, the US, the UK and France secured the UN Security Council’s approval to sanction Salah Badi, the Samoud Brigade commander from Misrata. Badi has been accused of repeatedly undermining security and stability, and played a key role in the clashes in residential neighbourhoods in Tripoli in September 2018. He also led multiple anti-GNA attacks in 2016 and 2017, when he sought to restore the internationally unrecognised National Salvation Government of former Prime Minister Khalifa Ghwell. His use of lethal force in densely populated areas and his continuous breach of the ceasefire in Tripoli were deemed an obstruction to peace, and banned under international humanitarian law.</p>
                <p>Some Libyans saw the sanctions against Badi as justified. Others pointed the finger at other, unnamed armed groups involved in the conflict, and criticised what they believed to be bias on the part of the international community. Although France argued at the UN Security Council that sanctions were an adequate punishment for the deadly fighting in Tripoli, it is unclear whether they will succeed in maintaining peace or deterring Badi or others from acting as spoilers. There is also a risk that institutions implementing selective sanctions could lose credibility with Libyans, especially if the criteria are not applicable to all armed actors involved in the conflict.</p>
                <p>The international community’s swift condemnation of Badi’s behaviour was meant to signal to armed groups that initiating conflict could result in their being ostracised. In turn, the use of sanctions can be interpreted as both a precedent and a mechanism to reshape incentives and introduce accountability for prominent leaders of armed groups that possess significant finances abroad. In the future, it is important for the international community to apply punishment similarly to individuals who blatantly flaunt the law and interfere with building the Libyan state.</p>
                <p>In some cases, however, international sanctions have proved futile in post-2011 Libya. Individuals who have already been sanctioned know that the UN cannot increase its punishment, because sanctions are its harshest weapon and the International Criminal Court fails to be an effective deterrent. Within this dynamic, individuals who have already been sanctioned continue to act as inflexible spoilers, while retaining the support of their community. This has happened in both eastern and western Libya. In other words, sanctions do not constitute an infallible solution to weaken hard-liners.</p>
                <p>Recommendation: The international community should support the implementation of authentic security-sector reform in Libya. Simultaneously, the international community should encourage the creation of checks and balances in the country’s financial system, which would help limit the influence of political actors on the Central Bank of Libya (CBL). For instance, the international community’s current policy consists of tolerating the militias with the most sway on the CBL. The rationale is that the militias provide security and so must not be criticised or hampered. Thinking along those lines will contribute to instability over the long run, as it helps create violent actors with enormous power over public finances. Instead, the international community should stop granting unconditional support to armed groups regardless of their illicit activities in the financial realm.</p>
            </div>
        </div>
        <div class="right-panel__part">
            <div class="footnotes">
                <div class="footnotes__line"></div>
                <div class="footnotes__wrapper">
                    <ol class="footnotes__list">
                        <li>Sudarsan Raghavan, "As oil output falls, Libya is on the verge of economic collapse”, Washington Post. 16 April 2016. <a href="https://www.washingtonpost.com/world/middle_east/as-oil-output-falls-libya-is-on-the-verge-of-economic-collapse/2016/04/15/5824a148-e16c-11e5-8c00-8aa03741dced_story.html?utm_term=.75a903186cc7">https://www.washingtonpost.com/world/middle_east/as-oil-output-falls-libya-is-on-the-verge-of-economic-collapse/2016/04/15/5824a148-e16c-11e5-8c00-8aa03741dced_story.html?utm_term=.75a903186cc7</a> (3 April 2019)</li>
                        <li>Paul Adrian Raymond and Mohammed Haddad, “The Battle for Libya’s Oil”, Al Jazeera, 19 February 2015. <a href="https://www.aljazeera.com/indepth/interactive/2015/02/battle-libyas-oil-150219124633572.html">https://www.aljazeera.com/indepth/interactive/2015/02/battle-libyas-oil-150219124633572.html</a> (3 April 2019)</li>
                        <li>Federica Saini Fasanotti, “Making Libya’s economy work again”, Brookings Institution, Washington, D.C., 7 October 2016. <a href="https://www.brookings.edu/blog/order-from-chaos/2016/10/07/making-libyas-economy-work-again/">https://www.brookings.edu/blog/order-from-chaos/2016/10/07/making-libyas-economy-work-again/</a> (3 April 2019)</li>
                        <li>Voluntas Advisory, “Libya Workforce Market Survey Report”, April 2017. <a href="https://voluntasgroup.com/wp-content/uploads/2019/06/Libya-Workforce-Market-Survey-Report-FINAL.pdf">PDF</a></a> (3 April 2019)</li>
                        <li>World Bank, “The World Bank in Libya: Collaboration Despite Conflict”, Washington, D.C., 19 February 2019. <a href="https://www.worldbank.org/en/news/feature/2019/02/19/the-world-bank-in-libya-collaboration-despite-conflict">https://www.worldbank.org/en/news/feature/2019/02/19/the-world-bank-in-libya-collaboration-despite-conflict</a> (3 April 2019)</li>
                        <li>Wolfram Lacher and Alaa al-Idrissi, “Capital of Militias: Tripoli’s Armed Groups Capture The Libyan State”, Small Arms Survey, June 2018.</li>
                        <li> International Foundation for Electoral Systems, “New Survey on Libyan Voters’ Attitudes Toward Political Situation and Future Elections”, Arlington, VA, 6 December 2018. <a href="https://www.ifes.org/surveys/new-survey-libyan-voters-attitudes-toward-political-situation-and-future-elections">https://www.ifes.org/surveys/new-survey-libyan-voters-attitudes-toward-political-situation-and-future-elections</a> (3 April 2019)</li>
                        <li> Irene Constantini, “Conflict dynamics in post-2011 Libya: a political economy perspective”, Conflict, Security & Development, Vol. 16, Issue 5, 1 August 2016.</li>
                        <li> Suliman Ali Zway, “Libya’s Shadow Economy”, Mercy Corps, April 2017.</li>
                        <li> Libya Business News, “Dramatic Measures to Plug Budget Deficit”, 17 January 2015. <a href="https://www.libya-businessnews.com/2015/01/17/dramatic-measures-to-plug-budget-deficit/">https://www.libya-businessnews.com/2015/01/17/dramatic-measures-to-plug-budget-deficit/</a> (3 April 2019)</li>
                        <li> Tim Eaton, “Libya’s War Economy: Predation, Profiteering and State Weakness”, Chatham House, London, 12 April 2018. <a href="https://www.chathamhouse.org/publication/libyas-war-economy-predation-profiteering-and-state-weakness">https://www.chathamhouse.org/publication/libyas-war-economy-predation-profiteering-and-state-weakness</a> (3 April 2019)</li>
                        <li> Quentin Sommerville, “Inside Zuwara, the heart of Libya’s people-smuggling trade”, BBC News, 4 September 2015. <a href="https://www.bbc.com/news/world-africa-34157123">https://www.bbc.com/news/world-africa-34157123</a> (3 April 2019)</li>
                        <li> Zway, “Libya’s Shadow Economy”.</li>
                        <li> Mark Micallef, “The Human Conveyor Belt: Trends in human trafficking and smuggling in post-revolution Libya”, The Global Initiative Against Transnational Organized Crime, Geneva, 17 March 2017. <a href="https://globalinitiative.net/report-the-human-conveyor-belt-trends-in-human-trafficking-and-smuggling-in-post-revolution-libya/">https://globalinitiative.net/report-the-human-conveyor-belt-trends-in-human-trafficking-and-smuggling-in-post-revolution-libya/</a> (3 April 2019)</li>
                        <li> Micallef, “The Human Conveyor Belt”.</li>
                        <li> The White House, “Executive Order 13566 — Libya”, Washington, D.C., 25 February 2011. <a href="https://obamawhitehouse.archives.gov/the-press-office/2011/02/25/executive-order-13566-libya">https://obamawhitehouse.archives.gov/the-press-office/2011/02/25/executive-order-13566-libya</a> (3 April 2019)</li>
                        <li> Dominic Rushe, “US Treasury blocks record $30bn of Libya assets”, Guardian, 28 February 2011. <a href="https://www.theguardian.com/world/2011/feb/28/us-treasury-blocks-libya-assets">https://www.theguardian.com/world/2011/feb/28/us-treasury-blocks-libya-assets</a> (3 April 2019)</li>
                        <li> Robert O’Harrow Jr., James V. Grimaldi and Brady Dennis, “Sanctions in 72 hours: how the U.S. pulled off a major freeze of Libyan assets”, Washington Post, 23 March 2011. <a href="https://www.washingtonpost.com/investigations/sanctions-in-72-hours-how-the-us-pulled-off-a-major-freeze-of-libyan-assets/2011/03/11/ABBckxJB_story.html?utm_term=.8e9f6001a6fc">https://www.washingtonpost.com/investigations/sanctions-in-72-hours-how-the-us-pulled-off-a-major-freeze-of-libyan-assets/2011/03/11/ABBckxJB_story.html?utm_term=.8e9f6001a6fc</a> (3 April 2019)</li>
                        <li> Heba Saleh and Andrew England, “Libya sovereign wealth fund chief to appeal to UN over frozen assets”, Financial Times, 19 April 2017. <a href="https://www.ft.com/content/a9be923c-2349-11e7-8691-d5f7e0cd0a16">https://www.ft.com/content/a9be923c-2349-11e7-8691-d5f7e0cd0a16</a> (3 April 2019)</li>
                        <li> United Nations, “In Swift, Decisive Action, Security Council Imposes Tough Measures on Libyan Regime, Adopting Resolution 1970 in Wake of Crackdown on Protesters”, New York, NY, 26 February 2011. <a href="https://www.un.org/press/en/2011/sc10187.doc.htm">https://www.un.org/press/en/2011/sc10187.doc.htm</a> (3 April 2019)</li>
                        <li> Statista, “Amount Of Libyan Assets Frozen Abroad”, 2019. <a href="https://www.statista.com/statistics/275294/amount-of-libyan-assets-frozen-abroad/">https://www.statista.com/statistics/275294/amount-of-libyan-assets-frozen-abroad/</a> (3 April 2019) </li>
                        <li> BBC News, “Libya: UN resolution on no-fly zone”, 18 March 2011. <a href="https://www.bbc.com/news/uk-politics-12783819">https://www.bbc.com/news/uk-politics-12783819</a> (3 April 2019)</li>
                        <li> United Nations, “Letter dated 5 September 2018 from the Panel of Experts on Libya established pursuant to resolution 1973 (2011) addressed to the President of the Security Council”, New York, NY, 5 September 2018.</li>
                        <li> Giulia Paravicini, “Millions flow from Gaddafi’s ‘frozen funds’ to unknown beneficiaries”, Politico, 8 February 2018. <a href="https://www.politico.eu/article/muammar-gaddafi-frozen-funds-belgium-unknown-beneficiaries/">https://www.politico.eu/article/muammar-gaddafi-frozen-funds-belgium-unknown-beneficiaries/</a> (3 April 2019)  </li>
                        <li> Giulia Paravicini, “Millions flow from Gaddafi’s ‘frozen funds’ to unknown beneficiaries”, Politico, 8 February 2018. <a href="https://www.politico.eu/article/muammar-gaddafi-frozen-funds-belgium-unknown-beneficiaries/">https://www.politico.eu/article/muammar-gaddafi-frozen-funds-belgium-unknown-beneficiaries/</a> (3 April 2019)  </li>
                        <li> BBC News, “Libya: Barack Obama announces Gaddafi sanctions”, 26 February 2011. <a href="https://www.bbc.com/news/world-africa-12585949">https://www.bbc.com/news/world-africa-12585949</a> (3 April 2019)</li>
                        <li> Economist, “Responsibility to protect: the lessons of Libya”, 19 May 2011. <a href="https://www.economist.com/international/2011/05/19/the-lessons-of-libya">https://www.economist.com/international/2011/05/19/the-lessons-of-libya</a> (3 April 2019)</li>
                        <li> George Libby, “Libya's $67 billion frozen funds must remain on ice says would-be investment chief”, Reuters, 17 July 2015. <a href="https://www.reuters.com/article/libya-investment-idUSL5N0ZX22820150717">https://www.reuters.com/article/libya-investment-idUSL5N0ZX22820150717</a> (3 April 2019)</li>
                        <li> Simon Marks, “Libya fund: 5 EU countries think Gaddafi account interest not frozen”, Politico, 16 November 2018. <a href="https://www.politico.eu/article/libyan-fund-five-eu-countries-released-muammar-gaddafis-frozen-money/">https://www.politico.eu/article/libyan-fund-five-eu-countries-released-muammar-gaddafis-frozen-money/</a> (3 April 2019)</li>
                        <li> Rebecca Murray, “Libyans Now Battle Over Housing”, Inter Press Service, 17 April 2012. <a href="http://www.globalissues.org/news/2012/04/17/13368">http://www.globalissues.org/news/2012/04/17/13368</a> (3 April 2019)</li>
                        <li> Mary Fitzgerald and Tarek Megerisi, “Libya: Whose Land Is It? Property Rights and Transition in Libya”, Legatum Institute, London, 16 April 2015.</li>
                        <li> Brian McQuinn, “After The Fall: Libya’s Evolving Armed Groups”, Small Arms Survey, Geneva, October 2012.</li>
                        <li> Fitzgerald and Megerisi, “Libya: Whose Land Is It?”</li>
                        <li> Margaret Coker, “Ex-Rebel, With Militia, Lays Claim To Libyan Oil Patch”, Wall Street Journal, 3 October 2013. <a href="https://www.wsj.com/articles/exrebel-with-militia-lays-claim-to-libyan-oil-patch-1380842931">https://www.wsj.com/articles/exrebel-with-militia-lays-claim-to-libyan-oil-patch-1380842931</a> (3 April 2019)</li>
                        <li> Ahmad Ghaddar and Aidan Lewis, “Libya outlines ambitious plans to restore oil output”, Reuters, 28 April 2016. <a href="https://www.reuters.com/article/us-libya-oil-production-idUSKCN0XP25R">https://www.reuters.com/article/us-libya-oil-production-idUSKCN0XP25R</a> (3 April 2019)</li>
                        <li> Brian Hutchinson, “Notorious Canadian lobbyist signs $2M contract to promote Libyan militants aiming to divide country”, National Post, 6 January 2014. <a href="https://nationalpost.com/news/notorious-canadian-lobbyist-hired-by-militants-seeking-breakaway-from-libya">https://nationalpost.com/news/notorious-canadian-lobbyist-hired-by-militants-seeking-breakaway-from-libya</a> (3 April 2019)</li>
                        <li> OPEC, “Libya facts and figures”, Vienna, 2018. <a href="https://www.opec.org/opec_web/en/about_us/166.htm">https://www.opec.org/opec_web/en/about_us/166.htm</a> (3 April 2019)</li>
                        <li> Ulf Laessing and Ghaith Shennib, “Libya’s PM warns may sink oil tankers nearing east ports”, Reuters, 8 January 2014. <a href="https://news.yahoo.com/libya-premier-says-reshuffle-cabinet-soon-disorder-mounts-133401616.html">https://news.yahoo.com/libya-premier-says-reshuffle-cabinet-soon-disorder-mounts-133401616.html</a> (3 April 2019)</li>
                        <li> Associated Press, “US sailors hand over control of captured oil tanker to Libyan forces”, 22 March 2014. <a href="https://www.theguardian.com/world/2014/mar/22/us-sailors-libya-north-korea-oil-tanker">https://www.theguardian.com/world/2014/mar/22/us-sailors-libya-north-korea-oil-tanker</a> (3 April 2019)   </li>
                        <li> Jalel Harchaoui, “Libya’s Monetary Crisis”, Lawfare, 10 January 2018. <a href="https://www.lawfareblog.com/libyas-monetary-crisis">https://www.lawfareblog.com/libyas-monetary-crisis</a> (3 April 2019)</li>
                        <li> Economist Intelligence Unit, “House of Representatives Sacks Central Bank Governor”, London, 16 September 2014.</li>
                        <li> Ayman al-Warfalli and Ulf Laessing, “IMF names eastern bank governor as its Libya contact”, Reuters, 24 July 2015. <a href="https://www.reuters.com/article/libya-bank-oil-idUSL5N1042I920150724">https://www.reuters.com/article/libya-bank-oil-idUSL5N1042I920150724</a> (3 April 2019)</li>
                        <li> Al-Warfalli and Laessing, “IMF names eastern bank governor as its Libya contact”. </li>
                        <li> Aidan Lewis, “Separate banknotes symbols of Libyan disunity, financial disarray”, Reuters, 3 June 2016. <a href="https://www.reuters.com/article/us-libya-economy-idUSKCN0YP156">https://www.reuters.com/article/us-libya-economy-idUSKCN0YP156</a> (3 April 2019)</li>
                        <li> Abdulkader Assad, “Libya’s parallel central bank admits printing 9.7 million dinar banknotes in Russia”, Libya Observer, 20 November 2018. <a href="https://www.libyaobserver.ly/economy/libyas-parallel-central-bank-admits-printing-97-billion-dinar-banknotes-russia">https://www.libyaobserver.ly/economy/libyas-parallel-central-bank-admits-printing-97-billion-dinar-banknotes-russia</a> (3 April 2019)</li>
                        <li> Zway, “Libya’s Shadow Economy”.</li>
                        <li> Harchaoui, “Libya’s Monetary Crisis”.</li>
                        <li> International Crisis Group, “After the Showdown in Libya’s Oil Crescent”, Brussels, 9 August 2018. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/189-after-showdown-libyas-oil-crescent">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/189-after-showdown-libyas-oil-crescent</a> (3 April 2019)</li>
                        <li> Libya Business News, “Audit Bureau Exposes Forex Scams”, 11 August 2015. <a href="https://www.libya-businessnews.com/2015/08/11/audit-bureau-exposes-forex-scams/">https://www.libya-businessnews.com/2015/08/11/audit-bureau-exposes-forex-scams/</a> (3 April 2019)</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Economist Intelligence Unit, “Central Bank Cuts Spending Further,” London, 19 January 2016.</li>
                        <li> Sami Zaptia, “Audit Bureau calls on CBL to speed up the opening of stalled LCs for essential goods”, Libya Herald, 22 November 2017. <a href="https://www.libyaherald.com/2017/11/22/audit-bureau-calls-on-cbl-to-speed-up-the-opening-of-stalled-lcs-for-essential-goods/">https://www.libyaherald.com/2017/11/22/audit-bureau-calls-on-cbl-to-speed-up-the-opening-of-stalled-lcs-for-essential-goods/</a> (4 April 2019)</li>
                        <li> Harchaoui, “Libya’s Monetary Crisis”.</li>
                        <li> Zway, “Libya’s Shadow Economy”. </li>
                        <li> Sami Zaptia, “CBL to allow every Libyan citizen the right to buy $US 400 at official exchange rate’. 1 February”, Libya Herald, 1 February 2017. <a href="https://www.libyaherald.com/2017/02/01/cbl-to-allow-every-libyan-citizen-the-right-to-buy-us-400-at-official-exchange-rate/">https://www.libyaherald.com/2017/02/01/cbl-to-allow-every-libyan-citizen-the-right-to-buy-us-400-at-official-exchange-rate/</a> (4 April 2019)</li>
                        <li> Eaton, “Libya’s War Economy”.</li>
                        <li> Eaton, “Libya’s War Economy”.</li>
                        <li> Libya Akhbar, “ICC-Wanted Libyan Threatens A Haftar-Allied Military Man In Benghazi”, 2018. </li>
                        <li> Libya Prospect, “Why Haftar Exports Scrap To Turkey?” 29 September 2018.</li>
                        <li> Mark Micallef and Tuesday Reitano, “The anti-human smuggling business and Libya’s political end game”, The Global Initiative Against Transnational Organized Crime, Geneva, 31 January 2018. <a href="https://globalinitiative.net/the-anti-human-smuggling-business-and-libyas-political-end-game/">https://globalinitiative.net/the-anti-human-smuggling-business-and-libyas-political-end-game/</a> (4 April 2019)</li>
                        <li> Micallef and Reitano, “The anti-human smuggling business”.</li>
                        <li> Micallef and Reitano, “The anti-human smuggling business”.</li>
                        <li> Aidan Lewis and Steve Scherer, “Exclusive: Armed group stopping migrant boats leaving Libya”, Reuters, 21 August 2017. <a href="https://www.reuters.com/article/us-europe-migrants-libya-italy-exclusive-idUSKCN1B11XC">https://www.reuters.com/article/us-europe-migrants-libya-italy-exclusive-idUSKCN1B11XC</a> (4 April 2019)</li>
                        <li> Micallef and Reitano, “The anti-human smuggling business”.</li>
                        <li> UN Panel of Experts, “Final Report Of The Panel of Experts On Libya Established Pursuant To Resolution 1973 (2011) (S/2017/466)”, 1 June 2011. <a href="https://reliefweb.int/report/libya/final-report-panel-experts-libya-established-pursuant-resolution-1973-2011-s2017466">https://reliefweb.int/report/libya/final-report-panel-experts-libya-established-pursuant-resolution-1973-2011-s2017466</a> (4 April 2019)</li>
                        <li> Matthew Herbert and Jalel Harchaoui, “Italy claims it's found a solution to Europe's migrant problem. Here's why Italy's wrong”, Washington Post, 26 September 2017. <a href="https://www.washingtonpost.com/news/monkey-cage/wp/2017/09/25/italy-claims-its-found-a-solution-to-europes-migrant-problem-heres-why-italys-wrong/">https://www.washingtonpost.com/news/monkey-cage/wp/2017/09/25/italy-claims-its-found-a-solution-to-europes-migrant-problem-heres-why-italys-wrong/</a> (4 April 2019) </li>
                        <li> United Nations Support Mission in Libya, “Human Rights Report on Civilian Casualities — October”, 1 November 2017. <a href="https://unsmil.unmissions.org/human-rights-report-civilian-casualties-october-2017">https://unsmil.unmissions.org/human-rights-report-civilian-casualties-october-2017</a> (4 April 2019)</li>
                        <li> BBC News, “Libya migrant ‘slave market’ footage sparks outrage”, 18 November 2017. <a href="https://www.bbc.com/news/world-africa-42038451">https://www.bbc.com/news/world-africa-42038451</a> (4 April 2019)</li>
                        <li> John Phillips et al., “Spanish charity accuses Libyan coastguard of leaving woman and toddler to die in the Mediterranean”, Telegraph, 17 July 2018. <a href="https://www.telegraph.co.uk/news/2018/07/17/spanish-charity-accuses-libyan-coastguard-leaving-woman-toddler/">https://www.telegraph.co.uk/news/2018/07/17/spanish-charity-accuses-libyan-coastguard-leaving-woman-toddler/</a> (4 April 2019)</li>
                        <li> Nancy Porsia, “The kingpin of Libya’s human trafficking mafia”, TRT World, 20 February 2017. <a href="https://www.trtworld.com/magazine/libya-human-trafficking-mafia-in-zawiya-301505">https://www.trtworld.com/magazine/libya-human-trafficking-mafia-in-zawiya-301505</a> (4 April 2019)</li>
                        <li> Libya Herald, “NOC calls for more arrests of fuel smugglers”, 26 August 2017. <a href="https://www.libyaherald.com/2017/08/26/noc-calls-for-more-arrests-of-fuel-smugglers/">https://www.libyaherald.com/2017/08/26/noc-calls-for-more-arrests-of-fuel-smugglers/</a> (4 April 2019)</li>
                        <li> Malta Independent, “Men involved in diesel smuggling from Malta in Libyan ships arrested”, 24 July 2015. <a href="http://www.independent.com.mt/articles/2015-07-24/local-news/Men-involved-in-diesel-smuggling-from-Malta-in-Libyan-ships-arrested-6736139388">http://www.independent.com.mt/articles/2015-07-24/local-news/Men-involved-in-diesel-smuggling-from-Malta-in-Libyan-ships-arrested-6736139388</a> (4 April 2019) </li>
                        <li> Aidan Lewis, “Libya eyes fuel marking, boat seizures, to counter fuel smuggling”, Reuters, 18 April 2018. <a href="https://af.reuters.com/article/worldNews/idAFKBN1HP2RQ">https://af.reuters.com/article/worldNews/idAFKBN1HP2RQ</a> (4 April 2019)</li>
                        <li> Julian Lee, “Qaddafi’s Long Gone, But Libya’s Oil Still Struggles”, Bloomberg, 4 February 2018. <a href="https://www.bloomberg.com/opinion/articles/2018-02-04/qaddafi-s-long-gone-but-libya-s-oil-still-struggles">https://www.bloomberg.com/opinion/articles/2018-02-04/qaddafi-s-long-gone-but-libya-s-oil-still-struggles</a> (4 April 2019)</li>
                        <li> Safa Alharaty, “Negotiations between Libya and Tunisia stall as protests continue in Ben Gardane”, Libya Observer, 26 August 2018. <a href="https://www.libyaobserver.ly/inbrief/negotiations-between-libya-and-tunisia-stall-protests-continue-ben-gardane">https://www.libyaobserver.ly/inbrief/negotiations-between-libya-and-tunisia-stall-protests-continue-ben-gardane</a> (4 April 2019)</li>
                        <li> World Bank, “Republic Of Tunisia — Impact of the Libya Crisis on the Tunisian Economy”, Washington, D.C., February 2017. <a href="http://documents.worldbank.org/curated/en/517981490766125612/pdf/ACS16340-WP-P158090-PUBLIC-Impact-of-Libya-Crisis-on-the-Tunisian-Economy-Long-Version.pdf">http://documents.worldbank.org/curated/en/517981490766125612/pdf/ACS16340-WP-P158090-PUBLIC-Impact-of-Libya-Crisis-on-the-Tunisian-Economy-Long-Version.pdf</a> (4 April 2019)</li>
                        <li> Katherine Pollock and Frederic Wehrey, “The Tunisian-Libyan Border: Security Aspirations and Socioeconomic Realities”, Carnegie Endowment for International Peace, Washington, D.C., 21 August 2018. <a href="https://carnegieendowment.org/2018/08/21/tunisian-libyan-border-security-aspirations-and-socioeconomic-realities-pub-77087">https://carnegieendowment.org/2018/08/21/tunisian-libyan-border-security-aspirations-and-socioeconomic-realities-pub-77087</a> (4 April 2019)</li>
                        <li> Sami Zaptia, “After recent reactivation, Fuel Crisis Committee dissolved”, Libya Herald, 9 January 2019. <a href="https://www.libyaherald.com/2019/01/09/after-recent-reactivation-fuel-crisis-committee-dissolved/">https://www.libyaherald.com/2019/01/09/after-recent-reactivation-fuel-crisis-committee-dissolved/</a> (4 April 2019)</li>
                        <li> Agence France-Presse, “Oil theft ‘costing Libya $750 million annually’”, 19 April 2018. <a href="http://www.dailystar.com.lb/Business/Regional/2018/Apr-19/445914-oil-theft-costing-libya-over-750-mn-annually.ashx">http://www.dailystar.com.lb/Business/Regional/2018/Apr-19/445914-oil-theft-costing-libya-over-750-mn-annually.ashx</a> (4 April 2019) </li>
                        <li> Statistics Times, “List Of Countries By Projected GDP Growth”, 6 January 2019. <a href="https://statisticstimes.com/economy/countries-by-projected-gdp-growth.php">https://statisticstimes.com/economy/countries-by-projected-gdp-growth.php</a> (4 April 2019)</li>
                        <li> Aidan Lewis, “Libya won’t stabilize unless shadow economy smashed — U.N. envoy”, Reuters, 29 March 2018. <a href="https://www.reuters.com/article/us-libya-security-un-idUSKBN1H51FE">https://www.reuters.com/article/us-libya-security-un-idUSKBN1H51FE</a> (4 April 2019)</li>
                        <li> Emadeddin Badi, “An Onerous Endeavor — Navigating Libya’s Political Quicksands”, Friedrich Ebert Stiftung, Berlin, November 2018. <a href="https://library.fes.de/pdf-files/bueros/tunesien/14934.pdf">https://library.fes.de/pdf-files/bueros/tunesien/14934.pdf</a> (4 April 2019)</li>
                        <li> Badi, “An Onerous Endeavor”.</li>
                        <li> Edith M. Lederer, “UN adds 6 traffickers and smugglers to Libya sanctions list”, Associated Press, 8 June 2018. <a href="https://apnews.com/33fa5811cfa3406ebab0cf094ca946ff">https://apnews.com/33fa5811cfa3406ebab0cf094ca946ff</a> (4 April 2019)</li>
                        <li> Micallef and Reitano, “The Anti-Human Smuggling Business”.</li>
                        <li> Sami Zaptia, “UN report cites numerous sources of illegal funding for Libyan militias”, Libya Herald, 16 June 2017. <a href="https://www.libyaherald.com/2017/06/14/un-report-cites-numerous-sources-of-illegal-funding-for-libyan-militias/">https://www.libyaherald.com/2017/06/14/un-report-cites-numerous-sources-of-illegal-funding-for-libyan-militias/</a> (4 April 2019)</li>
                        <li> UN Panel of Experts, “Final Report Of The Panel of Experts On Libya Established Pursuant To Resolution 1973 (2011) (S/2017/466)”.</li>
                        <li> Ayman al-Warfalli and Ahmad Ghaddar, “Attack shuts major Libyan oil ports, slashing production”, Reuters, 14 June 2018. <a href="https://uk.reuters.com/article/uk-libya-security-oil/attack-shuts-major-libyan-oil-ports-slashing-production-idUKKBN1JA1C9">https://uk.reuters.com/article/uk-libya-security-oil/attack-shuts-major-libyan-oil-ports-slashing-production-idUKKBN1JA1C9</a> (4 April 2019)</li>
                        <li> Aidan Lewis, “How unstable is Libya’s oil production?”, Reuters, 16 July 2018. <a href="https://www.reuters.com/article/us-libya-oil-explainer-idUSKBN1K61Y6">https://www.reuters.com/article/us-libya-oil-explainer-idUSKBN1K61Y6</a> (4 April 2019)</li>
                        <li> Abdullah Ben Ibrahim, “NOC deplores handover of oil ports to parallel institution, saying ‘Haftar Is acting like criminal Jadran’”, Libya Observer, 26 June 2018. <a href="https://www.libyaobserver.ly/news/noc-deplores-handover-oil-ports-parallel-institution-saying-%E2%80%9Chaftar-acting-criminal-jadran%E2%80%9D">https://www.libyaobserver.ly/news/noc-deplores-handover-oil-ports-parallel-institution-saying-%E2%80%9Chaftar-acting-criminal-jadran%E2%80%9D</a> (4 April 2019)</li>
                        <li> Patrick Wintour, “East Libyan general hands back control of oil ports”, Guardian, 11 July 2018. <a href="https://www.theguardian.com/world/2018/jul/11/east-libyan-general-hands-back-control-of-oil-ports">https://www.theguardian.com/world/2018/jul/11/east-libyan-general-hands-back-control-of-oil-ports</a> (4 April 2019) </li>
                        <li> Chris Stephen and Patrick Wintour, “Four Libya oil ports closed amidst corruption allegations”, Guardian, 2 July 2018. <a href="https://www.theguardian.com/world/2018/jul/02/four-libya-oil-ports-closed-amid-corruption-allegations-allies-khalifa-haftar">https://www.theguardian.com/world/2018/jul/02/four-libya-oil-ports-closed-amid-corruption-allegations-allies-khalifa-haftar</a> (4 April 2019) </li>
                        <li> Safa Alharathy, “Ministry of Health confirms 117 killed 581 wounded in Tripoli fighting”, Libya Observer, 27 September 2018. <a href="https://www.libyaobserver.ly/inbrief/ministry-health-confirms-117-killed-581-wounded-tripoli-fighting">https://www.libyaobserver.ly/inbrief/ministry-health-confirms-117-killed-581-wounded-tripoli-fighting</a> (4 April 2019)</li>
                        <li> International Crisis Group, “Libya’s Economic Reforms Fall Short”, Brussels, 25 October 2018. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/libyas-economic-reforms-fall-short">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/libyas-economic-reforms-fall-short</a> (4 April 2019)</li>
                        <li> Sami Zaptia, “Libya’s economic reforms have been successful”, Libya Herald, 24 November 2018. <a href="https://www.libyaherald.com/2018/11/24/libyas-economic-reforms-have-been-successful/">https://www.libyaherald.com/2018/11/24/libyas-economic-reforms-have-been-successful/</a> (4 April 2019) </li>
                        <li> Ahmed Elumami, “Libya 1st-half 2018 oil revenue $11.4 bln — central bank”, Reuters, 11 July 2018. <a href="https://www.reuters.com/article/libya-economy-idUSL8N1U6638">https://www.reuters.com/article/libya-economy-idUSL8N1U6638</a> (4 April 2019) </li>
                        <li> Badi, “An Onerous Endeavor”.</li>
                        <li> US Department of the Treasury, “Press Release: Treasury Sanctions Militia Leader Responsible for Multiple Attacks on Libyan Capital”, Washington, D.C., 19 November 2018. https://home.treasury.gov/news/press-releases/sm551 (4 April 2019)</li>
                        <li> United Nations Special Mission in Libya, Twitter, 15 January 2018. <a href="https://twitter.com/UNSMILibya/status/952934969269157888">https://twitter.com/UNSMILibya/status/952934969269157888</a> (4 April 2019)</li>
                        <li> Abdulkader Assad, “Misrata municipality condemns UN’s pick-and-choose sanctions in Libya”, Libya Observer, 19 November 2018. <a href="https://www.libyaobserver.ly/news/misrata-municipality-condemns-uns-pick-and-choose-sanctions-libya">https://www.libyaobserver.ly/news/misrata-municipality-condemns-uns-pick-and-choose-sanctions-libya</a> (4 April 2019)</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
