<div class="right-panel right-panel--green">
    <div class="right-panel__back"><?php echo file_get_contents("parts/svg/close.svg"); ?></div>
    <div class="right-panel__wrapper">
        <div class="right-panel__part" data-panel="1">
            <div class="right-panel__heading" data-panel="heading">Legitimacy</div>
            <div class="right-panel__text" data-panel="text">
                <p>In early 2011, opposition to Libya’s longtime dictator Muammar Gaddafi gained momentum amid the popular uprisings roiling the Middle East. International recognition for his regime began to erode when the Arab League suspended Libya’s membership on 22 February.<sup>1</sup></p>
                <p>The uprising against the regime was further legitimised on 10 March, when France recognised Libya’s interim National Transitional Council (NTC) as the revolution’s political arm.<sup>2</sup> Other states soon followed suit. The international diplomacy culminated in the United Nations Security Council’s (UNSC) adoption of Resolution 1973 on 19 March, which allowed international forces to impose a no-fly zone and protect civilians by all means necessary.<sup>3</sup> The resolution underscored the NTC as the sole legitimate representative of the Libyan people, until the General National Congress (GNC) was elected in July 2014.</p>
                <p>Libyans emerged from over four decades of oppressive rule under the Gaddafi regime and his Jamahiriyya, or “state of the masses”. Gaddafi had claimed that the Jamahiriyya was a legitimate system of direct democracy. In reality, it served to prop up one-man rule<sup>4</sup>; indeed, Gaddafi had distributed bureaucratic jobs and basic services, and maintained a sprawling intelligence apparatus to keep citizens of the oil-rich nation quiet.</p>
                <p>The killing of Gaddafi in October 2011 intensified the battle for power. Heads of “revolutionary” forces and state institutions jockeyed to position themselves as representatives capable of bringing prosperity to Libya<sup>5</sup>, with some initially comparing the country’s potential to Dubai. Ever since, various armed groups and political leaders, bound together by tribe, ideology or geography, have used force and intimidation to coerce institutions into meeting their demands<sup>6</sup>. Competitors for political dominance in Tripoli were diverse. Some armed groups held political Islamist views, others were more secular; armed “revolutionary” groups opposed former regime technocrats; and military and security officials from Gaddafi’s regime competed with armed rebels from rival towns<sup>7</sup>.</p>
                <p>The struggle for legitimate rule over Libya endures today. In the post-Gaddafi era, and as a country in transition, the question of who should assume leadership was a new question for Libyans. Technocrats and former regime officials who defected and joined the uprising ended up holding leadership positions within the transitional government. They included Mustafa Abdul Jalil, Gaddafi’s Minister of Justice, who became the chairperson of the NTC; and Mahmoud Jebril, head of the Economic and Development Board under Gaddafi, who became head of the NTC Executive Office. On the other hand, some revolutionary groups from Misrata, mostly Islamist-leaning and hardliners, wanted a complete break from Gaddafi-era officials, including those who defected.</p>
                <p>Libya’s political transition has been primarily guided by the Interim Constitutional Declaration (ICD) and its subsequent amendments, and later by the UN-backed Libyan Political Agreement (LPA). However, the first transition came to an abrupt end in August 2014, when a major battle for Tripoli broke out. The fighting destroyed much of the city’s oil infrastructure as well as its international airport, and marked the beginning of the second period of post-2011 civil strife.</p>
                <p>On one side, the Operation Dignity military alliance emerged, led by the Libyan National Army (LNA), headed by Field Marshal Khalifa Haftar in the east, and backed by Egypt, the United Arab Emirates and, to a lesser extent, France and Saudi Arabia. On the other side stood the Libya Dawn coalition in the west, primarily drawn from political Islamists and fighters mainly from Misrata, Tripoli, Zawiyah and Zuwara, with external support from Qatar and Turkey, and cooperation from Italy and Sudan. The armed groups were vying for political power, and with it control of lucrative resources and vital institutions such as the Central Bank of Libya (CBL), the National Oil Corporation (NOC) and Libya’s sovereign wealth fund, known as the Libyan Investment Authority (LIA).</p>
                <p>In August 2014, Libya Dawn seized control of Tripoli after a month-long battle, retained the General National Congress (GNC)<sup>8</sup> and subsequently set up a so-called National Salvation government. The newly elected House of Representatives (HoR) moved to Tobruk in the east, near Prime Minister Abdullah al-Thinni’s cabinet and Haftar’s LNA.<sup>9</sup> Months later, Libya’s Supreme Court in Tripoli ruled that the HoR elections were unconstitutional due to procedural mistakes. The HoR and the Operation Dignity coalition rejected the Supreme Court’s verdict, claiming that it was made under pressure from rival forces in the capital<sup>10</sup>.</p>
                <p>What was evident at the time — and remains valid today — is that national elections alone could not solve deep-rooted problems related to decades of Gaddafi’s dictatorship, which pitted tribes and communities against one another. Since the revolution, the lack of both a transitional justice reconciliation process and a disarmament, demobilisation and reintegration programme, to address grievances and remove weapons from armed groups, has contributed to a winner-takes-all culture and a predominantly corrupt and lawless environment.</p>
                <p>The drawn-out political dialogue and consensus-building mediated by the United Nations Support Mission in Libya (UNSMIL) between parties since 2014 has made progress, but the bitter political splits have mostly endured, despite shifting alliances. In the absence of a single central government and unified security institutions, municipalities have stepped in to assume a key role in providing essential services and mediating local peace.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="2">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">February and March 2011</div>
                The uprising against the Gaddafi regime begins</div>
            <div class="right-panel__text" data-panel="text">
                <p>In February 2011, after over four decades of Muammar Gaddafi’s rule, the ripple effect of the popular uprisings in Tunisia and Egypt reached Libya. Peaceful protests calling for political reform, social justice and human rights were met with violence as the regime targeted civilians in Bayda and Benghazi in the east, and Misrata and Zintan in the west. </p>
                <p>Libya was a UN member state and, apart from the voices of opposition members exiled abroad, Libyans did not have a say on whether Gaddafi’s rule was legitimate or not. However, the seeds of dissent were being sown across the region, and in Libya both the people and the international community started to question the viability of the regime.<sup>11</sup></p>
                <p>The protests rapidly grew into a revolution with the proliferation of armed opposition groups and the defection of key Libyan officials and lower-ranking government staff<sup>12</sup>. Additionally, the Arab League’s decision on 20 February to suspend Libya’s membership dealt a major blow to the regime’s status<sup>13</sup>. Gaddafi responded by intensifying the crackdown on dissent that had spread to other key cities, including Tripoli and Zawiyah in the west, triggering further domestic and international condemnation<sup>14</sup>.</p>
                <p>In March, EU member states and institutions, in a step that significantly affected the course of the uprising, hosted Libya’s political opposition, which lobbied for Western support<sup>15</sup>. Mahmoud Jebril, who led the National Transitional Council (NTC), shuttled between European and Arab capitals to advocate for regime change as the only way to protect Libyan civilians<sup>16</sup>.</p>
                <p>On 10 March, France unilaterally declared its recognition of the NTC as Libya’s sole representative<sup>17</sup>. Together with the UK, France lobbied the US to join the coalition against Gaddafi, while persuading China and Russia to refrain from vetoing a UN Security Council (UNSC) resolution<sup>18</sup>. Despite protests by the African Union (AU), which called for a diplomatic approach towards Libya<sup>19</sup>, the UNSC on 19 March adopted Resolution 1973. It condemned the regime’s violence, permitted an international military coalition to impose a no-fly zone, and allowed the use of all necessary means to protect civilians. The Responsibility to Protect mandate became indistinguishable from a mission to remove Gaddafi.<sup>20</sup></p>
                <p>In the years following Gaddafi’s ouster, some major international supporters of the uprising, including the UAE, Qatar, Turkey, France and Italy, emerged as primary backers of political factions and armed groups in the conflict. Later on, Egypt and Russia followed suit.<sup>21</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="3">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August 2011</div>
                The National Transitional Council adopts the Interim Constitutional Declaration</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 3 August 2011, under pressure from the Libyan public and the international community, the National Transitional Council (NTC) adopted the Interim Constitutional Declaration (ICD) as a roadmap for the transition. The ICD included articles on the Libyan state and the interim government, an independent judiciary, and civil rights and freedoms.</p>
                <p>The ICD set an overly ambitious timetable to reach milestones in Libya’s transition, including national elections scheduled 240 days after Libya’s break with the Gaddafi regime. Interpretations of the ICD also diverged, especially those of Article 30, which covers Libya’s constitution, elections and governance. The contentious clause became the touchstone of dissent, and has been amended ten times over the years to fit various political agendas.<sup>22</sup></p>
                <p>In retrospect, the NTC and the international community underestimated the imperative of striking a balance between democratisation and security. In a country awash with armed groups and weapons — and no history of inclusive government — the transition faced major challenges from the start.<sup>23</sup> Additionally, there was no mechanism for Libyans to come to terms with the country’s recent past and the conflicting experiences under the Gaddafi regime. The absence of a transitional justice and reconciliation process promoted the post-2011 narrative of winners versus losers, which only exacerbated divisions.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="4">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">March 2012</div>
                The birth of the east’s federalist movement</div>
            <div class="right-panel__text" data-panel="text">
                <p>The birth of the Higher Interim Council for Barqa, otherwise known as the “federalist movement”, gave shape to an emerging struggle over state institutions and resources in the country’s east. The federalists argued for more participation in Libya’s central institutions, increased economic opportunities and recognition of cultural rights.<sup>24</sup> After decades of neglect in the east under the Gaddafi regime, and with the majority of Libya’s population in the west, the federalists found themselves threatened by the possibility of one political or regional faction dominating the political landscape. Those fears have not dissipated. According to a poll conducted in 2013, respondents from Benghazi favoured a federal system over a unitary one, while respondents from Tripoli and Sebha preferred decentralisation.<sup>25</sup></p>
                <p>The federalist movement in the east is symptomatic of the cumulative neglect resulting from deliberate political decisions and/or from the failure of a highly centralised government to serve all regions equally. Their grievances are shared by many Libyans in other parts of the country.</p>
                <p>In March 2012, federalist activists and tribal leaders gathered in Benghazi and appointed Ahmed Al-Zubair al-Senussi as the chair of their movement. They sought to sow the seeds of doubt in the legitimacy of the National Transitional Council (NTC) and the Interim Constitutional Declaration (ICD), which was intended as a transitional roadmap for Libya’s democratic transition.<sup>26</sup></p>
                <p>The federalists reverted to intimidation to pressure the NTC into adopting a constitutional amendment in their favour. On 12 March, their threats of violence and of Libya’s partition forced the NTC to appease them by passing the first amendment to Article 30 of the ICD. The amendment directed the elected General National Congress (GNC) to appoint 60 members, drawn equally from the historic regions of Barqa, Fezzan and Tripolitania, and tasked with writing Libya’s permanent constitution on the Constitutional Drafting Assembly (CDA).<sup>27</sup></p>
                <p>A few weeks before the national GNC elections on 7 July, the federalists again relied on force to push through their demands, a method that would be used repeatedly by political and armed groups in the future. In June 2012, the federalists shut down the main road linking eastern Libya to the west at Wadi-al-Ahmar, demanding that the GNC’s 200 seats be distributed equally among representatives of Cyrenaica, Fezzan and Tripolitania.<sup>28</sup></p>
                <p>Wadi-al-Ahmar is the administrative demarcation line between Cyrenaica and Tripolitania. According to the federalists, closure of this corridor was intended not only to protest against the distribution of GNC seats but also to voice local grievances pertaining to indemnities and de-mining. These strong-arm tactics had been used before by militant groups in both Misrata and Zintan, causing the government to make concessions. A few weeks into the road closure, the federalists realised the heavy toll their actions were taking on their people and their interests. Thousands of citizens could not travel by land and the worn-out domestic air-transport facilities fell under tremendous stress. As a result, the closure was lifted<sup>29</sup>.</p>
                <p>The federalists resorted again to force just two days before the GNC elections, pressuring the NTC to rapidly introduce another amendment to Article 30<sup>30</sup>. The newly amended article stipulated that citizens would directly elect CDA members based on equal representation of the three historical regions, taking away powers granted to the GNC to appoint the body.</p>
                <p>Although the amendment required the GNC to ensure representation of “linguistic and cultural components”, the guarantees of adequate representation of minorities and women in the CDA were controversial. The electoral law of 16 July 2013 stipulated that of a total of 60 CDA seats, six would be reserved for women and six for ethnic minorities: two for the Tebu, two for the Tuareg and two for the Amazigh<sup>31</sup>.</p>
                <p>The election of the CDA members was described by the Carter Center as “soundly administered”, yet it failed to produce an inclusive and a “truly representative” body.<sup>32</sup> A total of 649 candidates competed, of which 65 were women. Violence broke out at some 80 polling stations, which prevented people from voting. By the end of the re-runs, 13 seats remained empty across Libya. Nine were later filled, but the two for the Amazigh and the two for Derna stayed empty, as the Amazigh boycotted the elections and the security situation in Derna remained grave.</p>
                <p>Some of the elected representatives, while enjoying a public backing, lacked the expertise required for the task. In November, the Supreme Court dismissed the amendment as void, because the NTC had not met their quorum when hastily passing the vote. However, less than a year later, on 11 April 2013, the amendment was reinstated by the GNC, this time after meeting the legal quorum.<sup>33</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="5">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2012</div>
                Libya holds its first democratic elections in over 40 years</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 7 July 2012, Libya held its first national elections for a 200-seat General National Congress (GNC), which would serve until the country’s permanent constitution was passed. The elections ran relatively smoothly despite the complexities of the electoral system, shortcomings of the electoral law and the controversy of the districting and seat allocation.</p>
                <p>The country was divided into 13 administrative districts and 73 constituencies, which were grouped into 20 electoral districts. Districting took three key factors into consideration: the size of the population, the geographical area, and the historical and social particularities of the country. Hence, the NTC allocated 106 seats to Tripolitania, 60 to Cyrenaica and 34 to Fezzan. This boundary delimitation seemed to have addressed the political interests and concerns voiced before the elections.</p>
                <p>For the 2012 GNC elections, Libya chose a complex electoral system with the hope of electing a legitimate parliament to put the country on course for political transition.</p>
                <p>A hundred and twenty seats were elected through a first-past-the-post system or a single non-transferable vote. In the former case, the candidate who received the highest number of votes won; in the latter, candidates were elected by plurality vote in multimember districts.<sup>34</sup> The remaining 80 seats were reserved for political entities and elected via a closed-list proportional representation system. As per the elections law, seats were allocated on a proportional basis, with vacant seats distributed according to the highest-remainder system.</p>
                <p>A quota for women was introduced to increase their representation in the GNC, in an attempt to rectify decades of blocked access of women to high-level government and decision-making positions. The original law set forth a quota of 10%, but civil society strongly opposed it and demanded more. Instead, a “zipper model” was applied to all 80 political party lists. Of the 1,200 candidates registered to run on the proportionate lists, 545 (45.2%) were women. Only 84 of the 25,001 candidates registered to run as individual candidates were women, largely due to financial resources and societal constraints.<sup>35</sup></p>
                <p>Thirty-three seats were awarded to women in the GNC elections, one of which was won by an individual candidate. This equated to about 16.5% of the GNC, meaning Libya now had a relatively high representation of women, though it remained lower than that of its neighbour, Tunisia, where women accounted for 26.6% of the parliament. The zipper system ensured Libyan women had better access to the representative body and encouraged further participation in the public sphere.<sup>36</sup></p>
                <p>The results of the GNC elections showed Mahmoud Jebril’s National Forces Alliance (NFA) winning a plurality of the 80 proportional list seats, with 39, the Muslim Brotherhood’s political branch, the Justice and Construction (JaC) party, winning 17, and the National Front winning only three. Three parties won two seats each and 15 other lists each won a single seat.</p>
                <p>Despite the success of Jebril’s party in most of the proportional list constituencies, neither the NFA nor the JaC managed to win the majority of the 200-seat GNC. The remaining 120 first-past-the-post and single non-transferable vote seats were won by individuals of no clear political affiliation<sup>37</sup>.</p>
                <p>After the elections, Libya's district courts received 37 complaints challenging the preliminary results. All but one were rejected: the District Court of Gharyan disqualified an elected candidate for being a member of the NTC. However, the verdict was subsequently overturned by a higher court because the complaint had been submitted after the deadline<sup>38</sup>.</p>
                <p>The composition of the GNC and the competing interests of the various parties and individuals made it difficult to form majoritarian blocs or reach compromises. Instead of establishing an inclusive reconciliation and transitional justice process, many GNC members got locked in zero-sum exclusionary politics. These included introducing damaging legislation such as the Political Isolation Law (PIL) and succumbing to intimidation by armed groups seeking to influence politics and government institutions.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="6">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">September 2012</div>
                The General National Congress amends the Interim Constitutional Declaration to lower the vote threshold</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 1 September 2012, the newly elected General National Congress (GNC) introduced a fourth amendment to Article 30 of the Interim Constitutional Declaration (ICD), seeking to reduce the threshold to pass legislation from 134 to 120 votes (of a total of 200 members)<sup>39</sup>. Its predecessor, the National Transitional Council (NTC), under federalist pressure from the east, had created the two-thirds threshold. However, due to heightened tensions and increasing polarisation among the members, the GNC was paralysed. It was unable to enact any legislation, including its own bylaws.<sup>40</sup> Though the downsized 120-vote threshold was approved, it was inapplicable to issues that required wide support across the political divide, including those for elections and the constitution-drafting process.<sup>41</sup></p>
                <p>The debate leading up to the vote illustrated the diminishing trust between the political groups. For example, the National Forces Alliance (NFA) was opposed to lowering the threshold. It feared it would pave the way for the passage of the Political Isolation Law (PIL), which later materialised, and that the call to banish former regime officials from public life could put their party leader, Mahmoud Jebril, at risk.<sup>42</sup></p>
                <p>The debate also exposed the dangerous zero-sum game and exclusionary politics that dominated Libya’s first democratic parliament. There was a clear struggle for power between the NFA, the political coalition that won 39 of the 80 allocated seats, and revolutionary and political Islamist factions, including the Muslim Brotherhood’s Justice and Construction bloc, and the Martyr’s bloc, which included representatives from the National Salvation Party, the Homeland Party and revolutionary politicians from Misrata, Zawiyah and Benghazi.<sup>43</sup></p>
                <p>Libya was in dire need of consensus to build trust and inclusivity. The NFA and its allies argued that they had won a democratic majority and should be able to form and run the government. In turn, revolutionary factions maintained that their long-term resistance to the Gaddafi regime earned them the right to push their agenda through. Libya was being drawn into a struggle for power and resources between the same factions that had fought side by side to oust Gaddafi.<sup>44</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="7">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">April and May 2013</div>
                The General National Congress passes the Political Isolation Law</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 11 April 2013, the General National Congress (GNC) passed a fifth amendment to the Interim Constitutional Declaration (ICD), paving the way for the controversial Political Isolation Law (PIL). The legislation was geared towards banning all former high-ranking Gaddafi-era officials from public life. The amendment stipulated that, as an exception, the number of votes required to pass the law could be lowered to 101, instead of the threshold of 120 previously agreed.<sup>45</sup> It passed amid mounting pressure from revolutionary forces and political Islamist groups seeking retribution for decades of persecution by the regime.<sup>46</sup></p>
                <p>However, the effort of the PIL’s proponents to lower the vote threshold proved unnecessary, as momentum behind the highly controversial and divisive law grew. Opponents of the PIL started to lose faith in the legitimacy of the political process as they faced a barrage of threats by armed groups, which had besieged many of Tripoli’s government buildings, including the Ministry of Justice.<sup>47</sup> On 6 May 2013, the GNC passed the PIL by a majority of 164 members of the 187 present. Of the minority, four members voted against the law, while nine simply did not show up<sup>48</sup>.</p>
                <p>The turbulent and intimidating circumstances of the PIL’s passage undermined both the public’s and politicians’ trust in their new democracy. Political decisions were being held hostage by self-interested armed groups, which exacerbated further divisions. The PIL also appeared to fit a precarious pattern of post-conflict recrimination and vengeance. Blamed for their association with the former regime, many officials with specialist skills were stripped of their government posts.<sup>49</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="8">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">November 2013 to 2019</div>
                Libya’s municipalities as valuable players</div>
            <div class="right-panel__text" data-panel="text">
                <p>With Libya’s central government and national institutions in political-crisis mode and unable to supply basic services and security across the country, local communities increasingly looked to municipality leaders to solve daily problems. Municipal officials worked to keep government offices, schools, hospitals and banks running, to oversee the upkeep of roads and rubbish collection, and to provide power, petrol, water and food supplies. Despite financial and geographical constraints, many local committees acted as key brokers in grassroots mediation and reconciliation efforts between tribes and armed groups.</p>
                <p>In November 2013, Libya held its first municipal elections, in the eastern city of Bayda<sup>50</sup>. By 22 October 2014, 71 out of 82 municipal councils had been elected as part of Libya’s devolution efforts. Though municipal councils, which have a four-year term, enjoyed public support, the legitimacy of some were challenged. On 19 June 2016, Agilah Saleh, the Speaker of the House of Representatives (HoR), declared a state of emergency in the east. He appointed the LNA’s chief of staff, Abdulrazaq Nadori, as military governor charged with overseeing territory from Bin Jawad in the central oil crescent, to Derna in the northeast<sup>51</sup>. Nadori abolished ten democratically elected municipal councils, and controversially replaced them with military rule.</p>
                <p>Two years later, after the fighting in Benghazi and Derna had subsided, as President of the HoR, Saleh abolished the post of military governor. The interim government in Bayda, headed by Prime Minister Abdullah al-Thinni, sought to appoint civilian caretakers for the municipalities or to reinstate those who had been democratically elected.<sup>52</sup></p>
                <p>In 2018, the Central Commission for Municipal Council Elections (CCMCE) oversaw successful municipal elections in the western towns of Zawiyah, Bani Walid and Dirj. In the first half of 2019, elections are due to take place in some 70 municipalities. However, because of the chronic political and institutional divide, the democratic process continues to face enormous challenges. For instance, last December, al-Thinni’s government warned municipalities in the east not to cooperate with the CCMCE, because it was affiliated with the rival Government of National Accord based in Tripoli.<sup>53</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="9">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">November 2013</div>
                The General National Congress paves the way for parliamentary elections </div>
            <div class="right-panel__text" data-panel="text">
                <p>A constitutional crisis erupted in November 2013 when the General National Congress (GNC) ignored the Interim Constitutional Declaration (ICD) roadmap and extended its term from February 2014 to December of the same year.<sup>54</sup> Frustration and disillusionment with the GNC politicians grew among the population, as did threats of violence against the body.</p>
                <p>One non-partisan peaceful youth movement — No Extension, No Renewal — coordinated nationwide protests over several weeks, until the GNC yielded to public pressure and agreed to hold new parliamentary elections on 25 June 2014<sup>55</sup>. It was a clear victory for civil society and showed that peaceful protests were capable of effecting change, in stark contrast to the brute force used by armed groups. Though its cause was vulnerable to takeover by special interests, the movement managed to set a positive precedent and reinforce the legitimacy of the democratic will of the people.</p>
                <p>This paved the way for the June elections of the new parliament, which would oversee the next phase of Libya’s transition and provide a mechanism to select the president. However, the challenge of holding new elections was tremendous in an increasingly polarised and cynical society saturated with weapons. It soon became clear that losing candidates were more likely to reject the results than accept them peacefully. The elections would lead to Libya’s ruinous political and institutional split, and escalate the devastating conflict.</p>
                <p>On 11 March, the GNC passed a seventh amendment to Article 30 of the Interim Constitutional Declaration (ICD). It allowed for a no-confidence vote to be introduced in an effort to oust controversial Prime Minister Ali Zeidan from office<sup>56</sup>. Political Islamist blocs were opposed to Zeidan, who represented a challenge to their domination of Tripoli’s governing institutions. They ensured the amendment’s success in exchange for his removal, after previous attempts to unseat him had failed. On 11 March, Zeidan was voted out, triggering a power struggle between political blocs within the GNC<sup>57</sup>, which soon turned into a legal battle. The politicisation of the courts would have a detrimental impact on the legitimacy and neutrality of Libya’s judiciary<sup>58</sup>, while the threat of violence saw Prime Minister Abdullah al-Thinni’s interim government relocate to the relatively safer town of Bayda.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="10">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">April 2014</div>
                The Constitution Drafting Assembly initiates the drafting process</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 20 February 2014, 56 members were elected to the Constitution Drafting Assembly (CDA). They were charged with writing Libya's permanent constitution<sup>59</sup>. Led by appointed chair Ali Tarhuni, the CDA held its first session in Bayda on 21 April. It needed two-thirds of its members for a quorum. The indigenous Amazigh community boycotted their two seats, in protest against their language and rights being overlooked — a stance similar to the one later adopted by the Tebu. Two members from Derna failed to be elected because their city was under the control of extremist armed groups.</p>
                <p>The CDA’s most contentious debates concerned the government structure, distribution of wealth and the rights of Libya’s indigenous communities, namely the Amazigh, the Tuareg and the Tebu<sup>60</sup>. The country’s wider conflict and political splits would raise legal challenges<sup>61</sup> to the legitimacy of the CDA<sup>62</sup>, and threaten to split the institution itself.</p>
                <p>Though hopes persisted that the CDA could be a positive development in Libya’s turbulent transition,<sup>63</sup> its critical work was quickly overshadowed by the security crises in nearby Benghazi. In May 2014, the Libyan National Army (LNA) led by Khalifa Haftar announced the start of its lengthy Operation Dignity military campaign, with the goal of purging Islamist extremist groups, including the Shura Council of Benghazi Revolutionaries, Ansar al-Sharia and Islamic State, from Benghazi. The offensive began a few weeks before the HoR elections in June.</p>
                <p>The CDA was scheduled to deliver a constitutional draft within 120 days of its first session. But it would take three years before the CDA approved a final draft, in July 2017. The delay led to increasing doubt about the CDA’s legitimacy and mandate. Members, activists and lawyers submitted many of the lawsuits filed against the CDA, challenging the body’s procedures and the draft’s content. The procedure of the final vote and the legitimacy of the draft remain contested too.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="11">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">May 2014</div>
                The General National Congress struggles to appoint a successor to Prime Minister Ali Zeidan</div>
            <div class="right-panel__text" data-panel="text">
                <p>After the ouster of Prime Minister Ali Zeidan on 4 May, the GNC was locked in an internal struggle over the appointment of his successor. Ahmad Mitig, a prominent businessman from Misrata who had the backing of revolutionary blocs, was appointed prime minister. But some parties, including the National Forces Alliance (NFA), challenged the vote. They accused some members of contravening the rules of procedure, and of casting their vote by telephone. The struggle over the political appointment became a legal case that reached the Supreme Court in Tripoli.<sup>64</sup></p>
                <p>To further complicate matters, on 29 May, caretaker Prime Minister Abdullah al-Thinni announced that he would not relinquish power, citing constitutional violations in Mitig’s appointment. Instead, he would wait until the Supreme Court had ruled on the matter. This manipulation of the justice system to settle political disputes set a precedent for legal and constitutional challenges. An ambiguous legal framework and threats by armed groups added to the judicial system’s inability to function properly.</p>
                <p>On 9 June, the Supreme Court ruled that Mitig’s appointment as prime minister was “unconstitutional”. The ruling further split Libyans: those who supported Mitig rejected the ruling, while others encouraged al-Thinni to hold on to his post. This political standoff left Libya with two prime ministers and a divided GNC.<sup>65</sup> GNC proponents remained in Tripoli, while al-Thinni and the HoR relocated to Bayda.</p>
                <p>The split was not simply about east versus west, as it is often portrayed, but political and ideological clashes. For instance, the Tripoli-based government viewed Haftar’s LNA military campaign in Benghazi as a coup attempt to disrupt Libya’s democratic transition. Nationalists in the east defended Haftar for ridding Benghazi of extremist groups that terrorised citizens and were involved in the killing of US Ambassador Christopher Stevens in 2012.</p>
                <p>On a positive note, both sides of the political divide respected the Supreme Court ruling. However, while some hailed it as a significant victory for the rule of law, others feared that a precedent to settle political issues through the courts could undermine the judiciary’s reputation as an impartial arbiter. </p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="12">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">June 2014</div>
                Elections and the emergence of two parliaments</div>
            <div class="right-panel__text" data-panel="text">
                <p>The elections for the House of Representatives (HoR) were held on 25 June. The low turnout of approximately 18% of eligible<sup>66</sup> voters reflected public disillusionment with Libya’s flawed political process.<sup>67</sup> Instead of bolstering democracy, the third election since Gaddafi’s overthrow accelerated the country’s political and armed struggle. It revealed the tremendous financial gains made by armed groups as security and economic conditions continued to deteriorate.</p>
                <p>The HoR elections resulted in the defeat of political Islamist factions. Rival armed groups battled for control of the international airport in Tripoli amid the threat of fully fledged civil war. The elections and the fighting in Tripoli were intimately linked. The political Islamists feared a legislative backlash that could include new anti-terrorism laws and sanctions, political and financial support for Khalifa Haftar’s military coalition, the direct election of a national president, and the repeal of the controversial Political Isolation Law (PIL), which excluded ex-regime officials from holding public office. They were convinced that such measures could severely limit their influence in Libya’s political future. Indeed, their fears materialised in the following months and years.</p>
                <p>The struggle between the political Islamists and their opponents within the General National Congress (GNC) weakened the institution. National demonstrations erupted near the end of the GNC’s term, with protesters demanding elimination of party lists in favour of independent candidates. The committee tasked by the GNC to draft the new electoral law incorporated these demands ahead of the HoR elections. But the elimination of political parties led to an unintended setback for democracy. Eliminating them gave rise to a personality-driven politics that could pave the way for a new autocratic regime in Libya.<sup>68</sup></p>
                <p>Political parties were banned in the Gaddafi era. In 2012, the National Transitional Council (NTC) enacted Law 14 of 2012, decriminalising the formation of political parties. This was followed by Law 29 of 2012, which regulates the formation, registration, activities and membership of political parties. In the 2012 GNC elections, parties performed well as they competed over the proportional representation seats. However, they could not form larger parliamentary blocs within the parliament or attract individual members to join them.</p>
                <p>The peaceful handover of power between parliaments was a crucial test of Libya’s democracy. Unfortunately, it failed. The GNC argued that its term had not expired in accordance with the Interim Constitutional Declaration (ICD), and it refused to relinquish power to the newly elected HoR on 4 August.<sup>69</sup> The UN-backed Libyan Political Agreement (LPA) later legitimised the parallel bodies through a power-sharing arrangement.</p>
                <p>On 6 August, the HoR adopted an eighth amendment to Article 30 of the ICD to delay the elections of a president.<sup>70</sup> While the High National Election Commission (HNEC) was technically and logistically ready to hold presidential elections, the security situation was deteriorating and the political environment was not conducive to holding free and fair elections. Intense fighting in Tripoli and Benghazi, as well as elsewhere in Libya, including in the south, meant that the national election turnout would be too low to appear legitimate.</p>
                <p>The Tobruk-based HoR and Speaker Agilah Saleh assumed presidential powers until a president could be elected. Meanwhile, the defiant GNC in Tripoli appointed Prime Minister Omar al-Hassi as head of their new National Salvation government. Libya now had two parliaments and two governments, with each side supported by a different armed coalition. The split affected institutions crucial to Libya’s economic survival, including the National Oil Corporation (NOC), the Central Bank of Libya (CBL) and the Libyan Investment Authority (LIA)<sup>71</sup>.</p>
                <p>Libya’s political transition had disintegrated. Armed groups extorted millions of dollars through intimidation and violence, and their influence over government institutions and policy became the new status quo. The absence of a legitimate central government, and unified state institutions and security apparatuses, undermined the rule of law, the economy and state building. The environment was also conducive to the proliferation of extremist groups such as Islamic State, which seized its opportunity to profit from the chaos<sup>72</sup>.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="13">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">September 2014</div>
                UNSMIL initiates dialogue between political rivals in Ghadames</div>
            <div class="right-panel__text" data-panel="text">
                <p>In September 2014, the UN Support Mission in Libya (UNSMIL) brokered what would become a lengthy dialogue between rival factions.<sup>73</sup> Initially, UNSMIL moderated talks in the desert town of Ghadames between members of the Tobruk-based House of Representatives (HoR) and the Misrata and Tripoli-based HoR members who had boycotted the body’s sessions in Tobruk.</p>
                <p>Spearheaded by UN envoy Bernardino León, the preliminary meeting aimed to bring the opposing sides together, build trust and encourage dialogue. Afterwards, the two groups of parliamentarians agreed to meet for a second round of talks to resolve the outstanding differences over the political process and to call for an immediate national ceasefire. The participants also agreed on confidence-building measures. These included working together to address urgent humanitarian needs, especially treating casualties on both sides of the conflict, and to resume flights at the country’s major airports.<sup>74</sup></p>
                <p>The Ghadames session occurred just weeks after the destruction of Tripoli’s international airport by rival Operation Dignity and Libya Dawn military coalitions which were vying for control of the lucrative asset.<sup>75</sup> The month-long battle had resulted in the parallel political institutions described above. Initially, the international community recognised Prime Minister Abdullah al-Thinni and the HoR, based in Bayda and Tobruk, as Libya’s legitimate government, rather than Prime Minister Omar al-Hassi of the National Salvation government and the rehabilitated General National Congress (GNC) in Tripoli. In fact, GNC members criticised the Ghadames talks, arguing that the UN wanted to legitimise the HoR, which they said they had defeated politically and militarily.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="14">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">November 2014</div>
                The Supreme Court in Tripoli nullifies the House of Representatives elections</div>
            <div class="right-panel__text" data-panel="text">
                <p>In August 2014, shortly after the newly elected House of Representatives (HoR) convened in Tobruk, two lawsuits reached the Supreme Court in Tripoli contesting the constitutionality of the HoR elections. The claimants, a boycotting member of the HoR and a General National Congress (GNC) representative, asked the court to nullify paragraph 11 in the seventh amendment to the Interim Constitutional Declaration (ICD). The clause stated that the HoR should appoint or hold direct elections of a president by popular vote within 45 days of the HoR’s first session. They argued that the paragraph had been adopted in violation of ICD provisions and GNC rules of procedure.<sup>76</sup></p>
                <p>On 6 November, the Supreme Court upheld the claimants’ controversial argument. Some members of the GNC, led by Speaker Nuri Abu Sahmain, declared that the ruling not only dissolved the HoR, but also established the GNC as the legitimate legislature of Libya. Two months before the Supreme Court’s verdict, the GNC had been resurrected by the Libya Dawn military alliance, with Omar al-Hassi as prime minister.</p>
                <p>The Supreme Court’s verdict raised concerns among the opposition about transparency and the potential intimidation of judges in Tripoli, where the court was based. The HoR in Tobruk subsequently rejected the ruling, accusing the Supreme Court judges of reaching a decision under duress.<sup>77</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="15">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">January and February 2015</div>
                UNSMIL holds talks in Geneva and Ghadames</div>
            <div class="right-panel__text" data-panel="text">
                <p>The legal challenge that resulted in the Supreme Court ruling to invalidate the House of Representatives (HoR) elections in June 2014 had effectively determined the trajectory of Libya’s transition. The judicial ruling added another layer of complexity to the crisis. It left Libya without a legally recognised government and widened the gap between competing tribes and nationalist factions that had already been embroiled in conflict for months.</p>
                <p>On 15 January, a new round of talks brokered by the UN Support Mission in Libya (UNSMIL) convened in Geneva with a goal to end the country's political and security crisis.<sup>78</sup> However, the General National Congress (GNC) set conditions for participation. They asked that the Supreme Court ruling be respected, and that the GNC — until then unrecognised by the international community — be treated as equal partners in the talks. Finally, the GNC requested that dialogue resume in the desert town of Ghadames.</p>
                <p>In addition to the talks between the GNC and the HoR, UNSMIL broadened its approach by setting up a simultaneous dialogue that included representatives of municipalities and armed groups, women and youth, as well as political parties, tribal leaders and civil society.</p>
                <p>Consequently, on 12 February, another round of talks was held in Ghadames. It was the first time that the GNC took part in the UNSMIL process. However, HoR and GNC representatives refused to meet in the same room.<sup>79</sup> Instead, the UN’s envoy Bernardino León held simultaneous caucuses. This proved to be a challenging and lengthy process, and eroded the legitimacy of the political institutions engaged in the talks. They were accused of prolonging the process to hold on to power. It also damaged the legitimacy of dialogue. The results of the negotiations were disputed as the status quo continued to undermine Libya’s security and living conditions.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="16">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">March 2015</div>
                The General National Congress fires Prime Minister Omar al-Hassi and replaces him with Khalifa Ghwell </div>
            <div class="right-panel__text" data-panel="text">
                <p>On 31 March, the General National Congress (GNC) dismissed Prime Minister Omar al-Hassi after six months in office, citing his poor performance as the reason for its decision. They also blamed him for government divisions.<sup>80</sup> The GNC viewed al-Hassi’s statements about the dire state of Libya’s finances as an attempt to cause a public outcry, and were disappointed that the international community refused to recognise and aid the cash-strapped and isolated Tripoli-based government.</p>
                <p>Meanwhile, the fight for assets and power between forces allied to rival governments raged in communities across Libya’s west, east and south. Armed groups were stretched thin and poorly paid, and lacked medical support. Economic conditions and services for civilians continued to nosedive, and journalists and activists were silenced.</p>
                <p>The appointment of Khalifa Ghwell as prime minister, al-Hassi’s deputy and one of Misrata’s revolutionary commanders meant that the GNC wanted an assertive leader who would be able to obtain necessary funds from the Central Bank of Libya (CBL) to pay for the state budget.</p>
                <p>It was also assumed that Ghwell’s appointment would help reach a political settlement with the rival government in the east. This assumption proved wrong. Ghwell and his GNC allies refused to recognise the UN-brokered Libyan Political Agreement (LPA) to be signed in Skhirat, Morocco that December.<sup>81</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="17">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July to October 2015</div>
                The General National Congress rejects the Libyan Political Agreement’s fourth draft</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 7 July, the General National Congress (GNC) rejected the fourth and final draft of the Libyan Political Agreement (LPA), after UN envoy Bernardino León announced that up to 99 percent of the contentious issues between both parties had been resolved, enabling them to form a unified Government of National Accord (GNA). However, the GNC delegation did not sign the final agreement<sup>82</sup>.</p>
                <p>GNC spokesperson Omar Hmaidan said the agreement did not take into account their amendments. These included a power-sharing legislative role with the House of Representatives (HoR), authority over the new GNA’s appointments, a say in the constitution-making process and electoral law, and a review of HoR decisions on high-ranking appointments. The HoR had resisted the GNC’s demands for months, insisting they were the sole legitimate legislators. Additionally, the HoR and President Agilah Saleh said they would consider handing the role of armed forces commander to the GNA, if they could choose the prime minister and one of two deputies.<sup>83</sup></p>
                <p>The power struggle concerning the formation of the future GNA would have a significant negative impact. The government’s legitimacy and performance would be undermined by a complex structure and embedded patronage system. For instance, the executive Presidential Council (PC) expanded from three to nine members during the negotiations.<sup>84</sup></p>
                <p>The cronyism and power struggle between the HoR and GNC representatives during the talks fed into the Libyan public’s deep alienation and distrust of the UN-backed political process, which involved myriad members of the international community and conferences held in foreign locales. Libyan citizens felt hostage to both greedy armed groups and dismal living standards.<sup>85</sup> Unfortunately, the political infighting would extend far beyond the signing of the LPA.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="18">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">November 2015</div>
                The abrupt exit of UN envoy Bernardino León</div>
            <div class="right-panel__text" data-panel="text">
                <p>UN envoy Bernardino León, the diplomat who initiated and oversaw the Libyan Political Agreement (LPA) negotiations, retired on 6 November. Supervision of the last round of the talks fell to his successor, German diplomat Martin Kobler. However, the legitimacy of the UN as an honest broker suffered a considerable blow when León moved to the UAE, a state that was repeatedly accused of meddling in Libyan affairs, for a well-paid job that he had negotiated during his role as UN envoy in Libya.<sup>86</sup></p>
                <p>The controversy cast serious doubt on the neutrality of the UN in brokering a peace for Libya and led to calls from affiliated factions with the General National Congress (GNC) to restructure the peace deal. Kobler had little choice but to rapidly push through the LPA to try to mitigate the damage. The majority of Libya’s stakeholders signed, but not all of them. The GNC and its National Salvation government, led by Prime Minister Khalifa Ghwell, refused to recognise the LPA and the subsequent GNA, and called instead for a renewed peace initiative.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="19">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">December 2015</div>
                The signing of the Libyan Political Agreement in Skhirat</div>
            <div class="right-panel__text" data-panel="text">
                <p>Through last-minute shuttle diplomacy in December 2015, UN envoy Martin Kobler attempted to convince members of the House of Representatives (HoR), the General National Congress (GNC), and other key players such as Khalifa Haftar of the Libyan National Army (LNA) to sign off on the Libyan Political Agreement (LPA).</p>
                <p>To appease as many key factions as possible, the structure of the Presidential Council (PC) was increased from one prime minister and two deputies to a nine-member team of prime minister, four deputies and four state ministers. The members of the expanded PC were chosen to represent geographic regions and cities such as Barqa, Fezzan, Misrata, Zintan and Tripoli, political institutions such as the HoR and the GNC, ideological groups, and the Libyan National Army (LNA).<sup>87</sup></p>
                <p>On 16 December, just one day before the signing of the LPA in Skhirat, Morocco, Kobler visited Haftar’s headquarters in Marj, eastern Libya. He sought to convince Haftar to support the LPA and nominate a candidate to the PC. The last-minute visit came as Haftar signalled his lack of support for the expanded PC because some of its members were allegedly associated with armed groups that the LNA was battling in Benghazi. Finally, Haftar agreed to nominate one of four deputies to the PC. After more than a year and a half of challenging negotiations, the LPA was finally signed on 17 December 2015 by the negotiators, with some abstentions<sup>88</sup>.</p>
                <p>The lack of trust and deep-rooted tensions in the negotiating process prevented the PC from functioning effectively, casting serious doubt on its legitimacy as the sole governing authority to represent Libyans. Instead, it marked the beginning of a new phase in the struggle between Libya’s competing governments and divided institutions, and left unresolved many legal disputes challenging the legality and constitutionality of the GNA and LPA.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="20">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">January 2016</div>
                The House of Representatives endorses the Libyan Political Agreement but drops contested Article 8 and rejects the proposed GNA cabinet</div>
            <div class="right-panel__text" data-panel="text">
                <p>The Libyan Political Agreement (LPA) established three governing bodies: 1) the House of Representatives (HoR) in Tobruk; 2) the High Council of State in Tripoli; and 3) the Presidential Council (PC) and Government of National Accord (GNA) based in Tripoli. These bodies are locked in a struggle over power sharing to this day<sup>89</sup>.</p>
                <p>On 25 January 2016, the HoR convened in Tobruk to vote on the LPA. While its members endorsed the document in principle, the HoR dropped one of the additional provisions, Article 8. This controversial clause stated that all senior military, civil and security posts should immediately be transferred to the PC upon the signing of the LPA. Khalifa Haftar and his supporters realised that the provision would sideline his ambitions to remain general commander of Libya’s armed forces.<sup>90</sup></p>
                <p>By annulling Article 8, the HoR pitted itself against the newly formed State Council over its interpretation of the agreement’s text, and the extent of power-sharing within it. In addition, the HoR voted to reject the GNA cabinet’s 32 ministries, requesting a smaller number to replace its bloated composition. An agreement among the nine members of the PC had produced the large number of ministries to satisfy various constituencies and to give President Fayez al-Serraj power to appoint a number of portfolios.</p>
                <p>Though the GNA would become Libya’s internationally recognised government, it would never receive full confidence or legitimacy from the HoR. Instead of unifying the country, the LPA led to further complex legal and political disputes.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="21">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">March 2016</div>
                The Presidential Council arrives in Tripoli by sea</div>
            <div class="right-panel__text" data-panel="text">
                <p>On 30 March 2016, after more than three months in exile in Tunis, and failing in various attempts to land at Tripoli’s Mitiga International Airport, the Presidential Council (PC) of the Government of National Accord (GNA) arrived at Tripoli’s Abu Sita naval base in a convoy of ships.</p>
                <p>Prime Minister Khalifa Ghwell’s National Salvation government had rejected the Libyan Political Agreement (LPA) and refused to recognise the GNA. It vowed to arrest members of the PC and the GNA cabinet. This meant that the newly arrived PC remained cloistered at the naval base, while the National Salvation government still controlled government offices in Tripoli. The GNA had to pay Tripoli-based armed groups, especially at Mitiga airport and around the naval base, to secure their operations.<sup>91</sup></p>
                <p>The arrival of the PC would spark months of tensions within Tripoli, which now had dual governments and ministries operating inside it. This eventually led to two coup attempts against the GNA by armed groups aligned with the National Salvation government. From October 2016 to March 2017, forces loyal to the National Salvation government had the upper hand in Tripoli by outmanoeuvring GNA forces, securing support from armed groups from Misrata, and controlling key districts of Tripoli.</p>
                <p>However, the GNA finally gained control of the capital through brokered alliances with local armed groups from Tripoli, who managed to oust the National Salvation government. But challenges to the GNA’s legitimacy and authority through force and the justice system continued well into 2018.<sup>92</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="22">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October 2016</div>
                Bayda’s Court of Appeals rules the Presidential Council unconstitutional</div>
            <div class="right-panel__text" data-panel="text">
                <p>Libya’s legitimacy crisis is multifaceted, and not strictly rooted in legal or constitutional claims. It stems from the legacy of four decades of dictatorship, a dysfunctional governance structure, and an uprising which laid bare the deep rifts and trust deficit between Libyans.</p>
                <p>The judicial system has contributed to the dysfunction. The trend of exploiting the judiciary for political means had been set back in 2014, hindering future prospects for a stable national government. Then, on 19 October 2016, the appeals court in Bayda upheld a legal challenge brought by Prime Minister Abdullah al-Thinni that claimed that the Tripoli-based Presidential Council (PC), the Government of National Accord (GNA) and all their decisions were null and void.</p>
                <p>The claim stated that the Libyan Political Agreement (LPA) had not properly followed the Interim Constitutional Declaration (ICD), and the House of Representatives (HoR) had not endorsed the GNA, as required by the LPA.</p>
                <p>Today, the interim government in Bayda continues to operate in the east, while the GNA has yet to extend its authority beyond Tripoli and some territory in the west and south.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="23">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2017</div>
                The Constitutional Drafting Assembly votes in favour of a draft constitution</div>
            <div class="right-panel__text" data-panel="text">
                <p>The Constitutional Drafting Assembly (CDA), which was tasked with drawing up a permanent constitution for Libya, was mired in internal divisions. Some members were federalists, and concerned that their rights would be threatened by Libya’s majority population living in Tripolitania. An opposing group of members worried about Libya’s unity, and proposed a strong, united but decentralised governing system. Indigenous representatives of the Amazigh and Tebu communities boycotted the process over grievances related to cultural, heritage and identity rights.</p>
                <p>More than one year before the draft was adopted, CDA meetings had been stalled by crucial issues, including whether the government should be decentralised and how to distribute wealth. The UN intervened in March 2016 and moved the meetings from Libya to Salalah, in Oman. However, the Salalah meetings led to further tensions within the CDA, with some members refusing to endorse the draft constitution.</p>
                <p>Bayda’s court of appeals accepted the legal challenge to the Salalah draft. To confuse matters further, in mid-2017, Agilah Saleh, the president of the House of Representatives (HoR), announced that the CDA’s mandate had expired, as it had gone well beyond the 120 days required to do its work pursuant to the Interim Constitutional Declaration (ICD). He declared that the HoR would consider dissolving the current CDA team, and appoint a new committee for the task.</p>
                <p>On 29 July 2017, this series of challenges unified CDA committee members, who voted in favour of their completed draft. Saleh’s statement about reconsideration of the constitution-drafting process and possible dissolution of the CDA was a strong enough motivation for 43 CDA members to vote for the draft constitution, thus securing the two-thirds majority required to put it up for referendum. </p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="24">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October 2017 to February 2018</div>
                The draft constitution faces more legal challenges</div>
            <div class="right-panel__text" data-panel="text">
                <p>Months after the Constitutional Drafting Assembly (CDA) passed the draft constitution, legal challenges continued to cast doubt on the legitimacy of the drafting process and the document it produced. On 12 October 2017, Bayda’s court of appeals ruled on a case brought by several CDA members who claimed procedural irregularities took place when the draft was voted on. The court annulled the CDA vote that took place on 29 July. The ruling was challenged by the CDA at the Supreme Court in Tripoli, and on 14 February 2018 the Supreme Court ruled in favour of the CDA, arguing that the court of appeals in Bayda had no jurisdiction over matters related to the activities of a democratically elected body.</p>
                <p>In total, there were four legal challenges that disrupted the CDA’s work and questioned the legitimacy of the constitution-drafting process.</p>
                <p>Legal challenges are not the only obstacles to the realisation of a permanent constitution. On 26 November 2018, the House of Representatives (HoR) adopted the tenth constitutional amendment to Article 30 of the Interim Constitutional Declaration (ICD). Initially, the article stated that once the constitutional draft was adopted by the CDA, it would be put up for a two-thirds vote in a public referendum. The new amendment has added an additional requirement: for the constitution draft to pass it must obtain 50% plus one vote in each of the three regions of Cyrenaica, Fezzan and Tripolitania.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="25">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">November 2018</div>
                The UN’s way forward and the House of Representatives objection to the Interim Constitutional Declaration</div>
            <div class="right-panel__text" data-panel="text">
                <p>In 2018, the UN envoy to Libya, Ghassan Salamé, realised that the House of Representatives (HoR) and the State Council were holding the political process hostage. They had repeatedly failed to amend the Libyan Political Agreement (LPA) and agree on a mechanism to choose a new unity government, a Presidential Council (PC) with three members, and a prime minister.</p>
                <p>On 5 September 2018, Salamé informed the United Nations Security Council (UNSC) that his efforts to amend the LPA had been unsuccessful because of the negotiators’ inability to compromise and pave the way for a unity government, a national referendum, and constitutional elections. Under the circumstances, Salamé proposed bypassing the obstructive parties and moving to the next phase of his plan: a National Conference in Libya, where participating citizens would agree on a new way forward.</p>
                <p>On 8 November 2018, Salamé informed the UNSC that the National Conference would be held in January 2019. On 12 and 13 November 2018, at an international conference on Libya in Palermo, Salamé reiterated his idea of bypassing the HoR and the State Council. Instead, he maintained that the National Conference would establish a new legal framework that would pave the way for elections to appoint a new unity government by June 2019.</p>
                <p>Salamé’s assertiveness angered some members of the HoR and the State Council, leading to accusations that he was imposing international aspirations on Libyans and bypassing democratically elected Libyan institutions.</p>
                <p>On 29 November 2018, the HoR enacted a constitutional amendment that would integrate the LPA into the Interim Constitutional Declaration (ICD), and lead to a referendum on the CDA’s draft constitution. The HoR’s initiative, pushed through by President Agilah Saleh, is meant to work against Salamé’s efforts to bypass the HoR and the State Council to hold the National Conference.</p>
            </div>
        </div>
        <div class="right-panel__part">
            <div class="footnotes">
                <div class="footnotes__line"></div>
                <div class="footnotes__wrapper">
                    <ol class="footnotes__list">
                        <li> Reuters, “Arab League suspends Libya delegation – TV”, 22 February 2011. <a href="https://www.reuters.com/article/libya-protests-league-idUSLDE71L2GK20110222">https://www.reuters.com/article/libya-protests-league-idUSLDE71L2GK20110222</a> (15 April 2019)</li>
                        <li> Alan Cowell and Steven Erlanger, “France Becomes First Country to Recognize Libyan Rebels”, New York Times, 10 March 2011. <a href="https://www.nytimes.com/2011/03/11/world/europe/11france.html">https://www.nytimes.com/2011/03/11/world/europe/11france.html</a> (15 April 2019)</li>
                        <li> UN Security Council, “Security Council Approves ‘No-Fly Zone’ Over Libya, Authorizing ‘All Necessary Measures’ to Protect Civilians, by Vote Of 10 In Favor With 5 Abstentions”, New York, NY, 17 March 2011. </li>
                        <li> Max Fisher, “How Qaddafi Fooled Libya and the World”, The Atlantic, 20 October 2011. <a href="https://www.theatlantic.com/international/archive/2011/10/how-qaddafi-fooled-libya-and-the-world/247078/">https://www.theatlantic.com/international/archive/2011/10/how-qaddafi-fooled-libya-and-the-world/247078/</a> (15 April 2019)</li>
                        <li> International Crisis Group, “Libya: Ensuring A Smooth And Peaceful Transition Into The Post-Qaddafi Era”, Brussels, 23 August 2011. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/libya-ensuring-smooth-and-peaceful-transition-post-qaddafi-era">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/libya-ensuring-smooth-and-peaceful-transition-post-qaddafi-era</a> (15 April 2019)</li>
                        <li> Frederic Wehrey, “Why Libya’s Transition To Democracy Failed”, Washington Post, 17 February 2016. <a href="https://www.washingtonpost.com/news/monkey-cage/wp/2016/02/17/why-libyas-transition-failed/">https://www.washingtonpost.com/news/monkey-cage/wp/2016/02/17/why-libyas-transition-failed/</a> (15 April 2019)</li>
                        <li> Frederic Wehrey and Wolfram Lacher, “Libya’s Legitimacy Crisis”, Foreign Affairs, 6 October 2014. <a href="https://www.foreignaffairs.com/articles/middle-east/2014-10-06/libyas-legitimacy-crisis">https://www.foreignaffairs.com/articles/middle-east/2014-10-06/libyas-legitimacy-crisis</a> (15 April 2019) </li>
                        <li> Mohamed Eljarh, “Libya’s Islamists Go for Broke”, Foreign Policy, 22 July 2014. <a href="https://foreignpolicy.com/2014/07/22/libyas-islamists-go-for-broke/">https://foreignpolicy.com/2014/07/22/libyas-islamists-go-for-broke/</a> (15 April 2019)</li>
                        <li> Rebecca Murray, “Libya: A tale of two governments”, Al Jazeera, 4 April 2015. <a href="https://www.aljazeera.com/news/2015/04/libya-tale-governments-150404075631141.html">https://www.aljazeera.com/news/2015/04/libya-tale-governments-150404075631141.html</a> (15 April 2019)</li>
                        <li> Mohamed Eljarh, “The Supreme Court Decision That’s Ripping Libya Apart”, Foreign Policy, 6 November 2014. <a href="https://foreignpolicy.com/2014/11/06/the-supreme-court-decision-thats-ripping-libya-apart/">https://foreignpolicy.com/2014/11/06/the-supreme-court-decision-thats-ripping-libya-apart/</a> (15 April 2019) </li>
                        <li> Chris Good, “Obama's Answer To The Question, ‘Why Libya?’”, The Atlantic, 21 March 2011. <a href="https://www.theatlantic.com/politics/archive/2011/03/obamas-answer-to-the-question-why-libya/72811/">https://www.theatlantic.com/politics/archive/2011/03/obamas-answer-to-the-question-why-libya/72811/</a> (15 April 2019) </li>
                        <li> Reuters, “Factbox: Defections From Gaddafi's Libya”, 25 August 2011. <a href="https://www.reuters.com/article/us-libya-ministers-defections-idUSTRE77O33K20110825">https://www.reuters.com/article/us-libya-ministers-defections-idUSTRE77O33K20110825</a> (15 April 2019) </li>
                        <li> Ethan Bronner and David E. Sanger, “Arab League Endorses No-Flight Zone Over Libya”, New York Times, 12 March 2011. <a href="https://www.nytimes.com/2011/03/13/world/middleeast/13libya.html">https://www.nytimes.com/2011/03/13/world/middleeast/13libya.html</a> (15 April 2019) </li>
                        <li> Ron Synovitz and Richard Solash, “Pressure Grows On Libya's Qaddafi To Quit”, Radio Free Europe, 1 March 2011. <a href="https://www.rferl.org/a/libya_protests/2322692.html">https://www.rferl.org/a/libya_protests/2322692.html</a> (15 April 2019) </li>
                        <li> Jamey Keaten, “Libyan Rebel Envoy In Europe To Seek Frozen Funds”, Associated Press, 24 August 2011. </li>
                        <li> Associated Press, “Sec. Clinton meets with Libyan rebels in Paris”, 14 March 2011. <a href="https://www.cbsnews.com/news/sec-clinton-meets-with-libyan-rebels-in-paris/">https://www.cbsnews.com/news/sec-clinton-meets-with-libyan-rebels-in-paris/</a> (15 April 2019) </li>
                        <li> Cowell and Erlanger, “France Becomes First Country to Recognize Libyan Rebels”.</li>
                        <li> Steven Erlanger, “France and Britain Lead Military Push on Libya”, New York Times, 18 March 2011. <a href="https://www.nytimes.com/2011/03/19/world/africa/19europe.html">https://www.nytimes.com/2011/03/19/world/africa/19europe.html</a> (15 April 2019)</li>
                        <li> Alex DeWaal, “The African Union and the Libya Conflict of 2011”, Tufts University/The Fletcher School: World Peace Foundation, Boston, MA, 19 December 2012. <a href="https://sites.tufts.edu/reinventingpeace/2012/12/19/the-african-union-and-the-libya-conflict-of-2011/">https://sites.tufts.edu/reinventingpeace/2012/12/19/the-african-union-and-the-libya-conflict-of-2011/</a> (15 April 2019)</li>
                        <li> Micah Zenko, “The Big Lie About the Libyan War”, Foreign Policy, 22 March 2016. <a href="https://foreignpolicy.com/2016/03/22/libya-and-the-myth-of-humanitarian-intervention/">https://foreignpolicy.com/2016/03/22/libya-and-the-myth-of-humanitarian-intervention/</a> (15 April 2019) </li>
                        <li> Karim Mezran and Elissa Miller, “Libya: From Intervention To Proxy War”, The Atlantic Council’s Rafik Hariri Center for the Middle East, Washington, D.C., July 2017. <a href="https://issuu.com/atlanticcouncil/docs/libya_from_intervention_to_proxy_wa">https://issuu.com/atlanticcouncil/docs/libya_from_intervention_to_proxy_wa</a> (15 April 2019) </li>
                        <li> Al Jazeera Center for Studies, “Libya's Transition without A Constitutional Map”, 4 April 2013. <a href="http://studies.aljazeera.net/en/positionpapers/2013/04/20134282438798512.html">http://studies.aljazeera.net/en/positionpapers/2013/04/20134282438798512.html</a> (15 April 2019) </li>
                        <li> Libya Observer, “UN envoy to Libya: More than 20 million pieces of arms are held by Libyans”, 8 February 2018. <a href="https://www.libyaobserver.ly/news/un-envoy-libya-more-20-million-pieces-arms-are-held-libyans">https://www.libyaobserver.ly/news/un-envoy-libya-more-20-million-pieces-arms-are-held-libyans</a> (15 April 2019)</li>
                        <li> Sean Kane, “Barqa Reborn? Eastern Regionalism and Libya’s Political Transition”, in The Libyan Revolution And Its Aftermath, eds. Peter Cole and Brian McQuinn (Oxford: Hurst Publishers/Oxford University Press, 2015), p. 205.</li>
                        <li> International Foundation for Electoral Systems, “Voters’ opinions of the election process in Libya”, Washington, D.C., March 2013. <a href="https://www.ifes.org/sites/default/files/libya_fg_report_final_2.pdf">https://www.ifes.org/sites/default/files/libya_fg_report_final_2.pdf</a> (15 April 2019)</li>
                        <li> Mohamed Eljarh, “The Federalist Movement In A Deeply Divided Libya”, The Atlantic Council, Washington, D.C., 4 September 2014. <a href="https://www.atlanticcouncil.org/blogs/menasource/the-federalist-movement-in-a-deeply-divided-libya">https://www.atlanticcouncil.org/blogs/menasource/the-federalist-movement-in-a-deeply-divided-libya</a> (15 April 2019)</li>
                        <li> Mohamed Eljarh, “The Federalist Movement In A Deeply Divided Libya”, The Atlantic Council, Washington, D.C., 4 September 2014. <a href="https://www.atlanticcouncil.org/blogs/menasource/the-federalist-movement-in-a-deeply-divided-libya">https://www.atlanticcouncil.org/blogs/menasource/the-federalist-movement-in-a-deeply-divided-libya</a> (15 April 2019)</li>
                        <li> Libya Herald, “Coastal road blocked by Cyrenaica federalists: report”, 20 June 2012. <a href="https://www.libyaherald.com/2012/06/20/coastal-road-block-by-cyrenaica-federalists-report/">https://www.libyaherald.com/2012/06/20/coastal-road-block-by-cyrenaica-federalists-report/</a> (15 April 2019) </li>
                        <li> Frederic Wehrey, “The Struggle for Security in Eastern Libya”, Carnegie Endowment for International Peace, Washington, D.C., 19 September 2012. <a href="https://carnegieendowment.org/2012/09/19/struggle-for-security-in-eastern-libya-pub-49425">https://carnegieendowment.org/2012/09/19/struggle-for-security-in-eastern-libya-pub-49425</a> (15 April 2019)</li>
                        <li> Wehrey, “The Struggle For Security In Eastern Libya”.</li>
                        <li> International Commission of Jurists, “The Draft Libyan Constitution: Procedural Deficiencies, Substantive Flaws”, Geneva, December 2015. <a href="https://www.icj.org/wp-content/uploads/2016/07/Libya-Draft-Constitution-Flaws-Deficiencies-Publications-Reports-2015-ENG.pdf">https://www.icj.org/wp-content/uploads/2016/07/Libya-Draft-Constitution-Flaws-Deficiencies-Publications-Reports-2015-ENG.pdf</a> (15 April 2019)</li>
                        <li> The Carter Center, “The 2014 Constitutional Drafting Assembly Elections in Libya”, Atlanta, GA, 2014. <a href="https://www.cartercenter.org/resources/pdfs/news/peace_publications/election_reports/libya-06112014-final-rpt.pdf">https://www.cartercenter.org/resources/pdfs/news/peace_publications/election_reports/libya-06112014-final-rpt.pdf</a> (15 April 2019)</li>
                        <li> The Carter Center, “The 2014 Constitutional Drafting Assembly Elections in Libya”.</li>
                        <li> The Carter Centre, “General National Congress Elections in Libya — Final Report”, Atlanta, GA, 7 July 2012. <a href="https://www.cartercenter.org/resources/pdfs/news/peace_publications/election_reports/libya-070712-final-rpt.pdf">https://www.cartercenter.org/resources/pdfs/news/peace_publications/election_reports/libya-070712-final-rpt.pdf</a> (15 April 2019)</li>
                        <li> Gender Concerns International, “Gender Election Monitoring (GEM) Mission in Libya — Final Report”, The Hague, 7 July 2012. <a href="http://www.genderconcerns.org/pdfs/Final%20Report%20GEM%20Mission%20Libya_Gender%20Concerns%20International_English%20version.pdf">http://www.genderconcerns.org/pdfs/Final%20Report%20GEM%20Mission%20Libya_Gender%20Concerns%20International_English%20version.pdf</a> (15 April 2019)</li>
                        <li> Gender Concerns International, “Gender Election Monitoring (GEM) Mission in Libya”.</li>
                        <li> European Union Election Assessment Team, “Libya — Final Report — General National Congress Election”, Brussels, 2012. <a href="https://eeas.europa.eu/archives/docs/eueom/missions/2012/libya/pdf/eueat-libya-2012-final-report_en.pdf">https://eeas.europa.eu/archives/docs/eueom/missions/2012/libya/pdf/eueat-libya-2012-final-report_en.pdf</a> (15 April 2019)</li>
                        <li> European Union Election Assessment Team, “Libya — Final Report”.</li>
                        <li> Libyan Security Sector Legislation, “Constitutional Amendment No. (4) of 2012”. </li>
                        <li> A. Aljanin, former GNC member, interviewed by author, Tripoli, Libya, December 2018. </li>
                        <li> Author interview with Aljanin.</li>
                        <li> Author interview with Aljanin.</li>
                        <li> Mary Fitzgerald, “Finding Their Place: Libya’s Islamists During and After the Revolution”, in The Libyan Revolution And Its Aftermath, eds. Peter Cole and Brian McQuinn (Oxford: Hurst/Oxford University Press, 2015), p. 177.</li>
                        <li> Mohamed Eljarh, “Struggling to Advance in Post-Spring Libya”, in Beyond Islamists and Autocrats: Struggling To Advance In Post-Spring Libya, The Washington Institute, Washington, D.C., January 2017.</li>
                        <li> Libyan Security Sector Legislation, “Constitutional Amendment No. (5) of 2013”. </li>
                        <li> Mohamed Eljarh, “Isolation Law harms Libya’s democratic transition”, Foreign Policy, 8 May 2013. <a href="https://foreignpolicy.com/2013/05/08/isolation-law-harms-libyas-democratic-transition/ ">https://foreignpolicy.com/2013/05/08/isolation-law-harms-libyas-democratic-transition/</a> (15 April 2019) </li>
                        <li> Eljarh, “Isolation Law harms Libya’s democratic transition”.</li>
                        <li> Eljarh, “Isolation Law harms Libya’s democratic transition”.</li>
                        <li> Eljarh, “Isolation Law harms Libya’s democratic transition”.</li>
                        <li> France 24, “Libya Holds First Municipal Elections”, 30 November 2013. </li>
                        <li> Al-Wasat, “Agilah Saleh Declares State of Emergency And Appoints Nadori As A Military Governor”, 19 June 2016. </li>
                        <li> Al-Wasat, “Seven Democratically Elected Mayors Call For Reinstating Democratically Elected Municipal Councils”, 22 August 2018.</li>
                        <li> Frank Talbot and David Denehy, “Is it time for municipal elections in Libya?”, Italian Institute For International Political Studies, Milan, 13 December 2018. <a href="https://www.ispionline.it/en/pubblicazione/it-time-municipal-elections-libya-21779">https://www.ispionline.it/en/pubblicazione/it-time-municipal-elections-libya-2177</a> (15 April 2019)</li>
                        <li> Patrick Markey and Ghaith Shennib, “In standoff, Libyans protest over parliament extension”, Reuters, 7 February 2014. <a href="https://ca.news.yahoo.com/libyans-oppose-congress-extension-amid-political-confusion-190137705.html">https://ca.news.yahoo.com/libyans-oppose-congress-extension-amid-political-confusion-190137705.html</a> (15 April 2019)</li>

                        <li> Eljarh, “Struggling to Advance in Post-Spring Libya”.</li>
                        <li> Libyan Security Sector Legislation, “Constitutional Amendment No. (7)”, 10 March 2014.</li>
                        <li> Author interview with Aljanin.</li>
                        <li> MC-Aldaouliya, “Libya’s Islamists Take Full Control Of The Government After The Ousting Of Prime Minister Zeidan”, 13 March 2014.</li>
                        <li> Ulf Laessing and Ghaith Shennib, “Poor turnout in Libyan vote for constitution-drafting body”, Reuters, 20 February 2014. <a href="https://ca.news.yahoo.com/libyans-vote-constitution-body-amid-bombs-tensions-125119460--finance.html">https://ca.news.yahoo.com/libyans-vote-constitution-body-amid-bombs-tensions-125119460--finance.html</a> (15 April 2019) </li>
                        <li> Rebecca Murray, “Libya’s Tebu: Living on the Margins”, in The Libyan Revolution And Its Aftermath, eds. Peter Cole and Brian McQuinn (Oxford: Hurst/Oxford University Press, 2015), p. 303.</li>
                        <li> Reuters, “Libya’s supreme court blocks legal challenges to draft constitution”, 14 February 2018. <a href="https://www.reuters.com/article/us-libya-security-constitution-idUSKCN1FY2CB">https://www.reuters.com/article/us-libya-security-constitution-idUSKCN1FY2CB</a> (15 April 2019) </li>
                        <li> Libya Herald, “CDA vote on draft constitution ruled invalid by Beida court”, 17 August 2017. <a href="https://www.libyaherald.com/2017/08/17/cda-vote-on-draft-constitution-ruled-invalid-by-beida-court/">https://www.libyaherald.com/2017/08/17/cda-vote-on-draft-constitution-ruled-invalid-by-beida-court/</a> (15 April 2019) </li>
                        <li> Ansamed, “Libya: Liberal Tarhuni Elected Constituent Assembly Chief”, 22 April 2014.</li>
                        <li> Mohamed Eljarh, “Libya’s Supreme Court Saves The Day”, Foreign Policy, 11 June 2014. <a href="https://foreignpolicy.com/2014/06/11/libyas-supreme-court-saves-the-day/">https://foreignpolicy.com/2014/06/11/libyas-supreme-court-saves-the-day/</a> (15 April 2019)</li>
                        <li> Eljarh, “Libya’s Supreme Court Saves The Day”.</li>
                        <li>According to the High National Elections Commission (HNEC), the number of voters registered for the 2014 HoR elections fell by nearly 47%  to 1,509, 317 from 2,865,937  in the 2012 GNC elections . The turnout in 2014 was 630,000 constituting of 41% of the registered voters.  see HNEC website for 2012 and 2014 elections numbers <a href="https://hnec.ly/?page_id=7537">https://hnec.ly/?page_id=7537</a> and <a href="https://hnec.ly/?page_id=7454">https://hnec.ly/?page_id=7454</a></li>
                        <li> Eljarh, “Struggling To Advance In Post-Spring Libya”.</li>
                        <li> International Crisis Group, “Libya’s Unhealthy Focus On Personalities”, Washington, D.C., 8 May 2018. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/b57-libyas-unhealthy-focus-personalities">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/b57-libyas-unhealthy-focus-personalities</a> (15 April 2019)</li>
                        <li> AfricaGate, “Nuri Abusahmain Refuses To Hand Over Power In Tobruk And Calls For A Session In Tripoli”, 3 August 2014. </li>
                        <li> Libyan Security Sector Legislation, “Constitutional Amendment No. (8)”, 6 March 2014.</li>
                        <li> Ulf Laessing, “Libya’s Runaway Parliament Seeks Refuge In Tobruk Bubble”, Reuters, 2 October 2014. <a href="https://www.reuters.com/article/us-libya-security-insight-idUSKCN0HR1GO20141002">https://www.reuters.com/article/us-libya-security-insight-idUSKCN0HR1GO20141002</a> (15 April 2019) </li>
                        <li> Martin Reardon, “Libya, extremism and the consequences of collapse”, Al Jazeera, 28 January 2016. <a href="https://www.aljazeera.com/indepth/opinion/2016/01/libya-extremism-consequences-collapse-160128054629594.html">https://www.aljazeera.com/indepth/opinion/2016/01/libya-extremism-consequences-collapse-160128054629594.html</a> (15 April 2019) </li>
                        <li> United Nations, “Launching Strategy To End Protracted Libya Crisis, Secretary-General Says United Nations Will Increase In-Country Presence”, New York, NY, 20 September 2017. <a href="https://www.un.org/press/en/2017/sgsm18707.doc.htm">https://www.un.org/press/en/2017/sgsm18707.doc.htm</a> (15 April 2019) </li>
                        <li> AfricaGate, “Positive Start To The Libyan Dialogue: Agreement For Ceasefire and Reopening of Airports”, 30 September 2014.</li>
                        <li> Heba al-Shibani and Ahmed Elumami, “War planes attack Libyan capital again and airport terminal is destroyed”, Reuters, 24 August 2014. <a href="https://www.reuters.com/article/us-libya-security-idUSKBN0GN0AS20140824">https://www.reuters.com/article/us-libya-security-idUSKBN0GN0AS20140824</a> (15 April 2019)</li>
                        <li> Libyan Security Sector Legislation, “Constitutional Amendment No. (7)”, 3 October 2014.</li>
                        <li> BBC News, “Libya supreme court ‘invalidates’ elected parliament”, 6 November 2014. <a href="https://www.bbc.com/news/world-africa-29933121">https://www.bbc.com/news/world-africa-29933121</a> (15 April 2019)</li>
                        <li> UN Security Council, “Report of the Secretary General on the United Nations Support Mission In Libya”, New York, NY, 26 February 2015.</li>
                        <li> UNSMIL, “Political Dialogue Convenes in Ghadames with All Parties Attending; Discussions to Continue in Days”, Ghadames, 11 February 2015. <a href="https://unsmil.unmissions.org/political-dialogue-convenes-ghedames-all-parties-attending-discussions-continue-days">https://unsmil.unmissions.org/political-dialogue-convenes-ghedames-all-parties-attending-discussions-continue-days</a> (15 April 2019)</li>
                        <li> BBC News, “Libya Crisis: Head of Islamist Tripoli Government Fired”, 31 March 2015. <a href="https://www.bbc.com/news/world-middle-east-32137285">https://www.bbc.com/news/world-middle-east-32137285</a> (15 April 2019)</li>
                        <li> International Crisis Group, “The Libyan Political Agreement: Time For A Reset".</li>
                        <li> International Crisis Group, “The Libyan Political Dialogue: An Incomplete Consensus”, 16 July 2015. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/libyan-political-dialogue-incomplete-consensus">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/libyan-political-dialogue-incomplete-consensus</a> (15 April 2019)</li>
                        <li> International Crisis Group, “The Libyan Political Agreement: Time For A Reset". </li>
                        <li> International Crisis Group, “The Libyan Political Agreement: Time For A Reset".</li>
                        <li> Rebecca Murray, “Libya anniversary: ‘The situation is just terrible’”, Al Jazeera, 16 February 2015. <a href="https://www.aljazeera.com/news/2015/02/libya-anniversary-situation-terrible-150216082028555.html">https://www.aljazeera.com/news/2015/02/libya-anniversary-situation-terrible-150216082028555.html</a> (15 April 2019)</li>
                        <li> Randeep Ramesh, “UN Libya envoy accepts £1,000-a-day job from backer of one side in civil war”, Guardian, 4 November 2015. <a href="https://www.theguardian.com/world/2015/nov/04/un-libya-envoy-accepts-1000-a-day-job-from-backer-of-one-side-in-civil-war">https://www.theguardian.com/world/2015/nov/04/un-libya-envoy-accepts-1000-a-day-job-from-backer-of-one-side-in-civil-war</a> (15 April 2019)</li>
                        <li> International Crisis Group, “The Libyan Political Agreement: Time For A Reset".</li>
                        <li> International Crisis Group, “The Libyan Political Agreement: Time For A Reset".</li>
                        <li> UNSMIL, “The Libyan Political Agreement”, Ghadames, 17 December 2015. <a href="https://unsmil.unmissions.org/sites/default/files/Libyan%20Political%20Agreement%20-%20ENG%20.pdf">https://unsmil.unmissions.org/sites/default/files/Libyan%20Political%20Agreement%20-%20ENG%20.pdf</a> (15 April 2019)</li>
                        <li> Karim Mezran, “Is Libya’s ‘Skhirat’ Agreement Really Dead?”, The Atlantic Council, Washington, D.C., 13 March 2017. <a href="https://www.atlanticcouncil.org/blogs/menasource/is-libya-s-skhirat-agreement-really-dead">https://www.atlanticcouncil.org/blogs/menasource/is-libya-s-skhirat-agreement-really-dead</a> (15 April 2019)</li>
                        <li> Wolfram Lacher and Alaa al-Idrissi, “Capital of Militias: Tripoli’s Armed Groups Capture the Libyan State”, Small Arms Survey, Geneva, June 2015. <a href="https://www.academia.edu/36954401/CAPITAL_OF_MILITIAS_-_Tripolis_Armed_Groups_Capture_the_Libyan_State_2018">https://www.academia.edu/36954401/CAPITAL_OF_MILITIAS_-_Tripolis_Armed_Groups_Capture_the_Libyan_State_2018</a> (15 April 2019)</li>
                        <li> Mary Fitzgerald and Mattia Toaldo, “A Quick Guide to Libya’s Main Players”, European Council on Foreign Relations, London, January 2018. <a href="https://www.ecfr.eu/mena/mapping_libya_conflict">https://www.ecfr.eu/mena/mapping_libya_conflict</a> (15 April 2019)</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
