<div class="right-panel right-panel--purple">
    <div class="right-panel__back"><?php echo file_get_contents("parts/svg/close.svg"); ?></div>
    <div class="right-panel__wrapper">
        <div class="right-panel__part" data-panel="1">
            <div class="right-panel__heading" data-panel="heading">Power and Violence</div>
            <div class="right-panel__text" data-panel="text">
                <p>The dynamics of power and violence in Libya have been inextricably linked during the transitional period that followed the ouster of Muammar Gaddafi. Much of this is rooted in the trajectory of the 2011 uprising. A majority of the armed groups operating in Libya today either entirely originated or partly originated from the revolutionary brigades that sprang up in opposition to Gaddafi that year.</p>
                <p>In July 2011, the killing of Abdel Fatah Younis, the commander of forces opposed to Gaddafi, revealed a darker undertow to the rebel side, one that still reverberates today. Similarly, the chaotic manner in which Tripoli fell to rebel forces the following month set in motion a series of developments that ultimately birthed the militia culture that dominates the capital.</p>
                <p>The seizure of key infrastructure in Tripoli, including airports, military bases and government offices, by rebels already competing for power when Gaddafi was still at large gave armed groups 14outsized influence on government decision-making in the years that followed. A series of fateful decisions by the National Transitional Council (NTC) to put those who claimed to have been revolutionary fighters on the public payroll ultimately led to the present situation, where adversaries on all sides of the current conflicts continue to receive state salaries.</p>
                <p>Many of the conflicts — both national and more localised — that roil Libya today can be traced back to factional or personal rivalries that were sparked during the 2011 uprising. The first example of major political concessions being granted due to the use or threat of force occurred just before Libya’s first elections in July 2012. Faced with intimidation and blockades from armed “federalists” seeking a measure of regional autonomy, the transitional authorities made key changes to the planned constitution-drafting process. This lesson in force as a political tactic was cited the following year by armed groups that besieged government ministries in a bid to push through the sweeping Political Isolation Law, which effectively removed from office a wide range of experienced officials who had worked under the Gaddafi regime.</p>
                <p>Another lesson came in 2013, when Ibrahim Jadhran, a militia commander in the Petroleum Facilities Guard, blockaded key oil ports in eastern Libya for nine months, almost completely shutting down the country’s main revenue stream, only to be subsequently compensated in a government deal. Energy infrastructure continues to be hijacked by armed groups seeking concessions from Tripoli.</p>
                <p>Libya’s post-Gaddafi conflicts have been more scrambles for control of resources than they have been ideological. The widespread belief that real power in Libya comes not from elected institutions but from the barrel of a gun has not just undermined ordinary Libyans’ faith in their democratic experiment — compare how turnout for national elections more than halved between 2012 and 2014 — but also encouraged Khalifa Haftar, the would-be strongman in the east, who argues that Libya is not ready for democracy.</p>
                <p>The relationship between power and violence, and the question of who is prepared to use the latter to achieve the former is likely to challenge Libya’s transition prospects for the foreseeable future.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="2">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2011</div>
                The killing of Abdel Fatah Younis, commander-in-chief of the revolutionary forces
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Abdel Fatah Younis had held several senior roles in the Gaddafi regime’s security apparatus before he defected in late February 2011 to join the rebels. His defection at such an early stage gave momentum to the uprising and helped encourage more military figures to join it. Furthermore, Younis was from the Obeidat tribe, historically the most powerful in eastern Libya. He faced several challenges, including how to organise forces that included regime soldiers who defected but also untrained volunteers, among them Islamists of several hues. </p>
                <p>Many of the Islamists did not trust Younis due to his role in several major regime operations against opposition elements, including jihadists, in eastern Libya.<sup>1</sup> In particular, he oversaw a military operation in Derna — long a hotbed of anti-regime sentiment, much of it jihadist — that devastated the town in the 1990s. In late July 2011, Younis was reported dead by the National Transitional Council after he had been summoned from the frontline for questioning in Benghazi. His mutilated body was found in the city, but no one has ever been brought to justice for the killing.</p>
                <p>Many questions remain unanswered over who was responsible, though it is widely believed that Younis’s assassins were extremists bent on revenge for his role in Derna. His murder threatened to drive a fatal wedge between the rebels, though for the most part the revolutionaries remained united. It also revealed a darker undertow to the uprising.<sup>2</sup> Some Libyans believe the assassination ultimately hampered efforts to establish united military forces after Gaddafi’s fall. The killing remains a sore point today in eastern Libya, particularly among the Obeidat tribe.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="3">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August 2011</div>
                The battle of Tripoli
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Six months after the uprising against the Gaddafi regime began, rebel forces moved to take control of the Libyan capital. It involved forces outside Tripoli coordinating with elements within it, including sympathetic senior military and intelligence figures.<sup>3</sup> Tripoli fell within a few days, with the advancing rebels aided not only by allied officers within the security apparatus but also by NATO airstrikes, which targeted military facilities dotted around the city. Ordinary citizens also assisted by barricading streets. Rebel units that streamed into the capital included the Tripoli Revolutionaries Brigade, which consisted mostly of Tripolitanians who had trained in Libya’s western mountains, but also armed groups from the port city of Misrata, itself subjected to a months-long siege by regime forces, and Zintan, a town southwest of Tripoli.</p>
                <p>Some of the fiercest fighting took place in and around Gaddafi’s sprawling Bab al-Azizia compound. Gaddafi and his family had already fled the capital, as had thousands of residents fearing a protracted battle. Rebel fighters broke open Abu Salim, the notorious prison where dissidents had been incarcerated throughout Gaddafi’s rule, and where some 1,200 prisoners were killed by security forces in a 1996 massacre. Cracks that were already being felt within the revolutionary camp widened after the fall of Tripoli as rebel units quickly began competing for influence. They commandeered key infrastructure including military compounds, airports and government buildings, calculating — correctly, as it turned out — that physical control of such strategic locations would give them outsized influence, including on government decision-making. In a telling remark, one commander from Zintan, whose forces had control of Tripoli’s international airport until the summer of 2014, boasted that “the airport is worth a thousand [government] ministries”.<sup>22</sup> Local resentment grew towards the armed groups that came from outside the city to “liberate” it but then refused to leave. Already there were hints of the power struggles to come.<sup>5</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="4">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October 2011</div>
                Battle for Sirte — the regime’s last stand and Gaddafi’s killing
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Sirte, Gaddafi’s hometown and a loyalist bastion that had enjoyed his largesse for decades, was where he and his regime made their last stand. Gaddafi and his entourage, comprising family members and senior security personnel, had hidden out in Sirte after fleeing the rebels’ advance on Tripoli. The grinding month-long battle for the city, often fought street by street as NATO bombed military locations from the air, ended in late October when rebel forces killed Gaddafi. </p>
                <p>Grainy telephone footage of a disoriented Gaddafi being beaten and abused before he was killed left many Libyans uneasy. Many Libyans argued that Gaddafi should have faced justice in court and felt the manner of his death was a stain on their revolution.</p>
                <p>Following the fall of Sirte, NATO announced it would end operations in Libya on 31 October. The National Transitional Council declared Libya liberated on 23 October. The six-week battle for Sirte, one of the most protracted in the uprising and involving NATO airstrikes as well as street fighting, devastated the coastal town. While most of its civilian population had fled, much of Sirte’s infrastructure was damaged or completely destroyed. The fiercely loyalist Sirte received little sympathy in post-Gaddafi Libya, and its reconstruction was not a priority for Tripoli’s authorities. Grievances rooted in Sirte’s neglect and ostracisation post-2011 were factors that would later contribute to the emergence of the Islamic State militant group here.
                </p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="5">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October to December 2011</div>
                Financial reward for rebel fighters
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>The seeds of Libya’s current militia economy were sown during this period, particularly during the government of Abd al-Rahim al-Keeb, which was formed in November 2011.<sup>6</sup> However, the pattern of giving state funds to those who claimed to be revolutionary fighters began with National Transitional Council (NTC) decisions to provide Eid bonuses, and later another round of payments to fighters in the immediate post-liberation period. Some Libyans criticised these decisions because in not linking such payments to the surrender of weapons, the transitional authorities missed a unique opportunity for disarmament.</p>

                <p>In particular, the NTC established the Warriors Affairs Commission (WAC) as part of its efforts to reintegrate fighters via further education or skills training, or by conscripting them into the military or police force. As part of its mandate, the WAC made plans to collect weapons from former fighters and created a registry of self-declared revolutionaries, or thuwwar. However, although fewer than 100,000 men were estimated to have fought in the uprising, more than 200,000 signed up for the registry.</p>

                <p>The al-Keeb government later decided to pay monthly salaries to members of armed groups operating under the umbrella of either the Supreme Security Committee (SSC) — linked to the interior ministry — or the Libya Shield Force, ostensibly under the authority of the army chief of staff. Still other armed groups, particularly from Zintan, drew salaries as official units of the defence ministry, which was then headed by Osama al-Juwaili from Zintan. The introduction of state salaries for fighters caused armed groups to mushroom in size and clout, driving recruitment but also encouraging commanders to inflate membership figures in order to gain more funds. The fact that the pay scale of the regular army and police paled in comparison to the salaries given to those under the newly formed adjunct SSC and Libya Shield Force also bred resentment among military and police officers.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="6">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">June 2012</div>
                Federalist violence and threats lead to major political concessions
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>In early 2012, activists in eastern Libya seeking a measure of regional autonomy began to organise, and in March they announced the formation of the Higher Interim Council for Barqa. Largely motivated by past grievances emanating from the Gaddafi regime’s neglect of the east, the activists — widely known as federaliyya, Arabic for federalists — ranged from those who sought a decentralised system of government for Libya to a minority who advocated separatism. The Barqa Council also had an armed wing, known as Jaish Barqa, or Army of Barqa.</p> 
                <p>From an early stage, the federalists used intimidation and violence to press their case. For example, just weeks before Libya’s first democratic elections, in early July, they blockaded the coastal highway connecting the country’s east and west, and demanded both the allocation of seats in parliament and that a separate committee draft Libya’s first constitution in the post-Gaddafi era.</p>
                <p>Faced with the federalists’ threats — they also warned that they would disrupt the July ballot — the National Transitional Council’s (NTC) head, Mustafa Abdel Jalil, decided to change how the membership of the constitution-drafting committee would be chosen. While other armed groups had previously used strong-arm tactics to pressure the NTC, this was the first example in post-Gaddafi Libya of major political concessions being granted due to the use or threat of force. Despite the NTC’s concessions, armed federalists followed through with their threats to disrupt the 2012 parliamentary vote, attacking the electoral commission’s offices in Benghazi, shooting down a helicopter carrying election materials and attacking polling stations. They also shut oil terminals before the ballot.<sup>7</sup></p>
                <p>The following year, when armed groups in Tripoli besieged government buildings to push through a sweeping lustration law, they justified the tactic by citing the precedent set by the federalists.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="7">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">September 2012</div>
                Attack on the US diplomatic mission in Benghazi
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>On 11 September, an armed group attacked the US diplomatic mission in Benghazi and burned it down. Later that night, another US diplomatic annex in the city came under mortar and rocket fire. US Ambassador Christopher Stevens died of smoke inhalation, three other Americans were killed too, and more than 30 had to be evacuated.<sup>8</sup> At first, the culprits were believed to have been a mob responding to a video mocking Islam, but it was later determined to have been a terrorist attack.<sup>9</sup> In Benghazi, shock over the deaths prompted mass demonstrations against Ansar al-Sharia, an extremist group later designated by the UN as a terrorist organisation, and other Islamist armed groups. The growing power of Ansar al-Sharia, in particular, aggravated tensions in the city. They were also accused of carrying out a series of assassinations and bombings.</p>
                <p>The following year, criminal charges related to the attack were filed in the US. Ahmed Abu Khatallah, a well-known Benghazi Islamist militant commanding the Obeida Ibn Al Jarra militia with close ties to Ansar al-Sharia, was among those named. In June 2014, US special forces captured Khatallah in Benghazi, and three years later a federal jury in Washington, D.C. found Khatallah guilty on four counts for his role in the attack. He was sentenced to 22 years in prison.<sup>10</sup></p>
                <p>The attack in Benghazi shook Libya’s fragile transitional government and kicked off a political firestorm in the US that would affect relations between the two countries. Republicans accused the Obama administration of security lapses, and several Congressional investigations were launched into how then-US Secretary of State Hillary Clinton handled the matter. Benghazi became a toxic byword and US engagement with Libya suffered as a result, with development funding cut and in-country programming scaled back due to security concerns. Four years later, during the 2016 presidential campaign, Donald Trump used the Benghazi debacle to attack Clinton.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="8">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October 2012</div>
                The siege of Bani Walid
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Bani Walid, home to Libya’s largest tribe, the Warfalla, was one of the last pro-Gaddafi strongholds to surrender during the 2011 uprising. Historical animosities between the town and Misrata have shaped its place in post-Gaddafi Libya.</p>
                <p>In July 2012, Omran Ben Shaaban, a resident of Misrata who helped capture Gaddafi in Sirte, was kidnapped in Bani Walid, purportedly by Gaddafi sympathisers. Though Shaaban was eventually released, he died of injuries sustained in captivity. Amid public pressure to avenge Shaaban’s death, the newly elected General National Congress (GNC) accused elders in Bani Walid of missing a deadline to give up the killers.</p> 
                <p>The GNC issued Resolution No. 7, a controversial decree that authorised “allied forces” — including armed groups from Misrata — to take all necessary measures to apprehend those responsible for Shaaban’s death. Bani Walid was subjected to a weeks-long siege followed by a military offensive that involved indiscriminate shelling. Dozens of people were killed and property was damaged in the fighting.<sup>11</sup> The GNC was accused of overstepping its mandate and meting out collective punishment on the town.<sup>12</sup> This was one of the more prominent examples of how “victors’ justice” defined the early transitional period in the absence of a properly functioning judicial system.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="9">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">May 2013</div>
                The controversial passage of the Political Isolation Law
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Calls for some form of lustration to bar figures from the Gaddafi regime from holding positions in the transitional period culminated in the Political Isolation Law (PIL), approved by the General National Congress (GNC) on 5 May. Politicking between rival factions within the GNC resulted in a law that was far more sweeping than many had anticipated. The provisions and procedures for exclusion did not consider whether targets had already defected or continued to serve Gaddafi and his regime. The PIL was further criticised by Libyan and international human rights groups as too sweeping and vague.<sup>13</sup> Ultimately, the hollowing out of institutional expertise that resulted from the legislation’s enforcement would hobble Libya’s transition.</p>
                <p>The circumstances in which the PIL was passed were yet another reminder of how the use of violence or threat of force for political reasons was becoming a defining feature of the post-Gaddafi period. Several armed groups had besieged for weeks a number of key ministries, including the foreign ministry, the interior ministry and the justice ministry, in order to press for the bill’s approval. Militiamen targeted the state-owned Al Wataniya television station, driving its employees out and halting its live broadcast. On a number of occasions, intimidation by armed groups forced the GNC to suspend its debates on the PIL. As a result, in mid-March, the GNC met to discuss the proposed legislation away from its usual location. But militiamen also stormed that venue, trapping parliamentarians inside for several hours. The convoy of GNC president Mohammed al-Magariaf came under fire when he left.</p>
                <p>Some parliamentarians reported receiving individual threats. The PIL remained controversial in the years that followed, and some of its strongest proponents later admitted it had gone too far. In February 2015, the House of Representatives (HoR), elected the previous year to replace the GNC and based in the eastern town of Tobruk, voted to revoke the legislation.<sup>15</sup> Given the HoR’s limited powers, particularly in Tripoli, it remains unclear how this annulment of the PIL can be enforced.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="10">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August 2013 to April 2014</div>
                The blockade of eastern oil ports
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Armed federalists had shut down oil terminals in eastern Libya ahead of the 2012 parliamentary elections. In 2013, Ibrahim Jadhran, a commander of the Petroleum Facilities Guard (PFG) tasked with protecting oil infrastructure, went further. After he and other federalists formed their own self-declared government in eastern Libya, Jadhran launched a blockade of four oil ports there in a bid to get concessions from Tripoli. These included Es Sider and Ras Lanuf, two of Libya’s most important oil terminals. The blockade lasted nine months and deprived Libya of at least USD 7 million in oil revenues.<sup>16</sup> In March 2014, US Navy Seals stymied Jadhran’s bid to illegally export oil by seizing the Morning Glory tanker, which had been loaded with at least 234,000 barrels of crude oil at Es Sider.<sup>17</sup> The GNC subsequently sacked Prime Minister Ali Zeidan over his handling of the episode.</p>
                <p>The following month, a caretaker government headed by then-defence minister Abdullah al-Thinni forged a deal with Jadhran and his men aimed at ending the blockade. An undisclosed amount of money was given to the blockaders — ostensibly backpay for the PFG personnel who took part — and the government pledged to investigate their allegations of corruption in Libya’s energy sector. No assurances were given on Jadhran’s other demands for regional autonomy and a larger share of oil revenue for eastern Libya. Some federalists opposed Jadhran’s blockade, believing it ultimately damaged their cause.</p>
                <p>The fact that the Libyan government ended up essentially compensating rogue PFG personnel for maintaining oil ports during a shutdown that crippled the Libyan economy set a precedent for armed groups in other oil-rich parts of Libya. Much to the chagrin of the National Oil Corporation, there have been several other cases since where energy infrastructure, including oil fields and pipelines, has been hijacked to push for political and economic concessions.<sup>18</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="11">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">February 2014</div>
                Khalifa Haftar accused of attempting coup when he calls for the suspension of government
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Khalifa Haftar, who participated in the military coup that brought Gaddafi to power in 1969, defected in the late 1980s after he was involved in the regime’s disastrous war in neighbouring Chad. In 2011, Haftar returned to Libya to join the uprising. He tried to establish a support base after Gaddafi’s fall, particularly among circles of disgruntled military officers and his own Ferjani tribe.</p>

                <p>On 14 February 2014, the Al Arabiya satellite channel broadcast footage of Haftar in full uniform calling for the suspension of the Libyan government and its replacement by a military council.</p>

                <p>Prime Minister Ali Zeidan declared that the government was safe and that security was under control. Accusing Haftar of attempting a coup, Zeidan announced that legal proceedings would be taken against him. Haftar’s video call for the “rescue” of Libya by the army was perceived by some within the country’s Islamist milieu as a manoeuvre ominously echoing events in neighbouring Egypt the previous year, when the elected President Mohammed Morsi, a member of the Muslim Brotherhood, was overthrown in a military coup.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="12">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">May 2014</div>
                Haftar launches the Operation Dignity military campaign in Benghazi
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Haftar’s re-emergence in May 2014 took the country by surprise. The loose alliance of army units and anti-Islamist militias that emerged from his canvassing in the east following his attempted coup in February were united by the sense of a perceived common enemy: the Islamist militias and their alleged political allies in Tripoli.</p>
                <p>Security and military personnel were ready to back Haftar, as they had been the main target of an assassination campaign by jihadist groups in Benghazi. Furthermore, Haftar promised to address what the military perceived as problematic state policies of salary and rank provision to revolutionary commanders, which encouraged the formation and growth of militias.<sup>19</sup> Dubbing his military offensive Operation Dignity, or Karama in Arabic, Haftar launched air and ground assaults on armed bases in Benghazi on 16 May. Those targeted included the February 17th Martyrs Brigade, which had been the largest anti-Gaddafi armed group in eastern Libya during the 2011 uprising, and Ansar al-Sharia, an extremist group formed after the uprising, whose fighters were accused of involvement in the September 2012 attack on the US diplomatic mission in Benghazi.<sup>20</sup> The US State Department had designated Ansar al-Sharia a terrorist organisation in January 2014.</p>
                <p>At the outset of Operation Dignity, substantial parts of Benghazi were under the control of myriad Islamist armed groups, including the Rafallah al-Sahati militia, Ansar al-Sharia (ASL), the Libya Shield Brigade led by the Islamist commander Wissam bin Hamid, and the February 17th Martyrs Brigade.<sup>21</sup> Several months into Haftar's operation, Islamic State (IS) affiliates emerged in Benghazi, fighting alongside the anti-Haftar coalition, known as the Benghazi Revolutionaries Shura Council (BRSC), which served as an umbrella for an assortment of Islamist factions. The goal of fighting a common enemy encouraged Islamists of different ideological hues to join forces.2 Although the BRSC was meant to be a temporary measure, many BRSC fighters ended up converging on a more radical position.<sup>23</sup> Meanwhile, on the tactical side, the establishment of the BRSC improved the coordination among the different Islamist militias, which helped them achieve military successes in the subsequent months.<sup>24</sup></p>
                <p>The government in Tripoli condemned Haftar’s offensive as illegal, and Major General Abdulsalam Jadallah al-Obeidi, then chief of staff of the Libyan Army, also denounced him. Suspicions that Operation Dignity was about more than a purported war on extremists in Benghazi were fed by Haftar’s statement that he considered the Muslim Brotherhood to be the main enemy, and by the storming of the GNC on 18 May by LNA-allied al-Qa’qa and Sawa’iq militias from Zintan, who declared the legislative body dissolved.<sup>25</sup> The attack on the GNC had serious repercussions, as it exacerbated the  escalation of conflict in Libya.<sup>26</sup></p>
                <p>Operation Dignity prompted a range of political and armed factions and individuals to rally to Haftar's side. Several regular army units in eastern Libya, including most significantly the Saiqa special forces in Benghazi, declared their support. Many cited the spate of assassinations — widely blamed on radical Islamists — that not only targeted military and police officers but also civil society activists, as the reason for their initial endorsement of Haftar’s campaign.</p>
                <p>To show their support for the offensive, groups of citizens rallied in Benghazi.<sup>27</sup> On 19 May, residents of the Fashloum district of Tripoli took to the streets in support of Operation Dignity. They released a statement asking other forces to back the assault against “terrorist groups”.<sup>28</sup> Haftar used this public expression of support as part of his efforts to bestow greater legitimacy on the operation.<sup>29</sup></p>
                <p>This coalition of actors and interests would not remain static — a number of Haftar’s initial allies subsequently fell out with him — but it would later form the bedrock for Haftar's national ambitions.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="13">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July and August 2014</div>
                Battle for control of Tripoli and the emergence of Libya Dawn
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>With the seizing of strategic infrastructure and territory by armed groups after Tripoli fell to rebel forces in August 2011, the Libyan capital had become a patchwork of militias. Rivalries between the armed groups — many of which claimed affiliation with the interior or defence ministries — often flared into violence.<sup>30</sup> Tripolitanians resented fighters from outside the city who had stayed since 2011, particularly those from Misrata and Zintan, whose competition for influence frequently led to clashes. In November 2013, more than 40 people protesting against the presence of Misratan armed groups in the neighbourhood of Garghour were killed when militiamen opened fire on them.</p>
                <p>Longstanding tensions between Zintani armed groups and their rivals began to escalate in early 2014. Zintani militiamen, who controlled the international airport among other key locations, threatened and at times physically targeted the General National Congress (GNC). When the most powerful Zintani groups in Tripoli openly sided with Haftar in May and attacked GNC buildings with rockets in the name of Operation Dignity, those who feared Haftar’s power ambitions grew anxious.</p>
                <p>Among them were the Misrata-based Central Shield Force, the Knights of Janzour militia and fighters drawn from Libya’s Amazigh minority, along with political Islamists like the Muslim Brotherhood and members of the defunct Libyan Islamic Fighting Group (LIFG). These disparate currents would unite in what later became known as the Libya Dawn alliance, or Fajr Libya. Elections for the House of Representatives, which was to replace the GNC in June, resulted in the loss of the Islamist-Misratan political bloc.<sup>31</sup></p>
                <p>In mid-July, the coalition of militias that formed Libya Dawn moved to wrest control of Tripoli’s international airport from the Zintanis. In the month of fighting that ensued, the airport and other key infrastructure were destroyed, while the UN Support Mission in Libya, foreign embassies and international organisations, as well as many companies, evacuated. Zintani armed groups were eventually routed from Tripoli, thus changing the balance of militia power in the capital. The then-internationally recognised prime minister, Abdullah al-Thinni, fled to Bayda in eastern Libya, while a rump of the former GNC set up a rival government in Tripoli.<sup>32</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="14">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">October 2014</div>
                After losses, new momentum for Operation Dignity
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Allegedly bolstered with a fresh supply of weapons from Egypt and the UAE,<sup>33</sup> five months after Khalifa Haftar launched his Operation Dignity campaign in the name of fighting terrorism in Benghazi, his forces — a mix of military units and tribal militias under the banner of the Libyan National Army (LNA) — continued to face losses against the Benghazi Revolutionaries Shura Council (BRSC), a coalition of Islamists and other armed groups that had formed in opposition to Haftar’s offensive. In July, BRSC fighters had captured the headquarters of the Saiqa special forces in Benghazi, and attempted to wrest control of the city’s airport, key to the air power that Haftar had used against his opponents.</p> 
                <p>Despite the BRSC’s relative military successes, a rift between Islamists aligned with the GNC and hardliners within the BRSC led to an internal political division. A group of Benghazi-based Islamists with links to the Muslim Brotherhood’s Justice and Construction Party (JCP) announced on 16 August 2014 the formation of a Shura Council with the reconciliatory aim to “find solutions to the problems of the city”.<sup>34</sup> The BRSC asserted that it did not recognise this new council,<sup>35</sup> and that it would “not fight for the sake of democracy or the HoR”, but only “for the sake of God”.<sup>36</sup></p>
                <p>The BRSC’s offensive to consolidate its control over Benghazi resulted in a backlash from citizens, who blamed Islamist militias for the growing insecurity and absence of the rule of law in the city. In mid-October 2014, Haftar announced a new offensive in Benghazi and called for an armed youth uprising. Operation Dignity spokesperson Muhammed al-Hijazi appealed to Benghazi’s residents, who were wary and resentful of the Islamist militia’s control of the city, to secure their neighbourhoods and prevent the Islamist combatants from seeking refuge in them.<sup>37</sup> The BRSC had previously used the tactic of dissolving into residential districts once they were targeted by LNA fighter jets and artillery.<sup>38</sup></p>
                <p>Benghazi residents, particularly the youth, responded to the LNA’s appeal by erecting sand barriers to block access of Islamist militias to their districts. Those volunteers who helped tip the balance in neighbourhood battles were considered key gains on the ground for Operation Dignity in Benghazi. They were said to have provided intelligence to the LNA about locations of military targets.<sup>39</sup> Some youths took up arms and formed the Neighbourhood Youth watch groups, while others targeted the families of militants fighting alongside the BRSC and destroyed their homes.<sup>40</sup> </p>
                <p>By the end of the month, Haftar’s forces had gained momentum, though the battle for Benghazi would last for several more years and also draw in Islamic State (IS). Human rights groups accused both sides of launching indiscriminate attacks from and into residential areas, resulting in civilian deaths and injuries.<sup>41</sup> </p>
                <p>Haftar’s change in fortunes had much to do with the House of Representatives (HoR) decision to endorse his operation and an uptick in external military support. The following March, the HoR officially appointed Haftar as commander of the Libyan National Army (LNA). However, many senior military officers, particularly in western Libya, refused to recognise Haftar’s LNA. This divide continues today despite efforts to create unified national forces. External backing may have helped Haftar win Benghazi, but it was not enough for him to gain the support or trust of military personnel across the country.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="15">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2015</div>
                Islamic State militants driven out of Derna
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>A number of Libyans who had joined the Islamic State (IS) group in Syria were key to the formation of its first Libyan affiliate in Derna, an eastern town with a long history of jihadism.<sup>42</sup> In the 1990s, Gaddafi suppressed a local jihadist movement there known as the Libyan Islamic Fighting Group (LIFG). Hundreds of fighters who had travelled from Derna to Iraq to join al-Qaeda following the US invasion in 2003 ended up in IS.<sup>43</sup></p>
                <p>IS’s leadership in Syria sent messengers to sympathisers in Libya, encouraging the infiltration of jihadists into the country and rerouting financial resources to support the emergence of its Libyan franchise.<sup>44</sup> In April 2014, a group of jihadist young men who travelled to Syria — to fight with al-Battar Brigade — returned to Derna and joined the Islamic Youth Shura Council, which later pledged allegiance to IS leader Abu Bakr al-Baghdadi.<sup>45</sup> Alarmingly, by the spring of 2016, the number of fighters in Libya’s IS ranks was estimated to have grown to 6,000.<sup>46</sup></p>
                <p>In October 2014, IS recognised its Derna affiliate. The group commandeered several government buildings and landmarks inside the city, and sought to impose itself through fear, carrying out public beatings and amputations. The IS franchise in Libya has always been dominated by foreigners at leadership level, with non-Libyans, particularly from Tunisia, Egypt and sub-Saharan Africa, also forming a large component of its rank and file.</p> 
                <p>But rival Islamist armed groups, including the Abu Salim Martyrs Brigade, led by Libyan Islamic Fighting Group veterans, maintained their control of most of Derna. Some residents resented the ultra-conservative agenda of these groups, while others saw them as key to security even as IS developed a presence there. These groups came together to form the Derna Mujahideen Shura Council (DMSC) in December 2014, partly as a counter to IS. Tensions between the two led to frequent clashes and culminated in the killing of a DMSC leader by IS in June 2015. This sparked fierce fighting and the beginning of efforts to expel IS from Derna.</p>
                <p>Both Egypt and the US carried out airstrikes against IS targets in and around Derna. In November 2015, a US airstrike killed senior IS leader Abu Nabil al-Anbari, an Iraqi national, in the first American military action against IS outside Syria and Iraq. Clashes continued, however, and IS was not fully routed from Derna’s environs until April 2016.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="16">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">May 2016</div>
                 The launch of the Benghazi Defense Brigades (BDB)
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>By early 2016, the fighting in Benghazi was still grinding on. Since its launch in May 2014, Khalifa Haftar’s Operation Dignity had aimed to defeat all Islamists, including the Muslim Brotherhood.<sup>47</sup></p>
                <p>On the anti-Haftar side, the Benghazi Revolutionaries Shura Council (BRSC), comprising several groups including the UN-designated terrorist organisation Ansar al-Sharia, was experiencing internal strains. Tensions had grown over the BRSC’s relationship with Islamic State (IS), and some of its backers, particularly in western Libya, pushed for the BRSC to distance itself from the group.</p>
                <p>Against this backdrop, a new anti-Haftar faction calling itself the Benghazi Defense Brigades (BDB) announced itself. The BDB is an umbrella group that sought to help BRSC in its fight against Haftar.<sup>48</sup> The BDB consistently affirmed in its earlier statement that the group had “no party, political or ideological affiliations”.<sup>49</sup> Yet the group had pledged loyalty to the Tripoli-based Grand Mufti Sadiq al-Ghariani and claimed to operate under the authority of his Dar al-Ifta.<sup>50</sup> The Grand Mufti in May 2016 urged all “revolutionaries” to abandon the fight against Islamic State and focus instead on fighting LNA.<sup>51</sup></p>
                <p>The BDB differed from the BRSC in that it contained former army and police figures — it was led by air force colonel Mustafa Sherkesi — who had always opposed Haftar and his operation, in addition to Islamists hardliners and self-described revolutionaries. Other leaders included a number of former BRSC members, including Ziyad Belam, former commander of al-Mukhtar Brigade, Ahmed al-Tajuri and others.<sup>52</sup></p>
                <p>The BDB intended to fight its way back to Benghazi — and in its public statements it referred time and again to the rights of displaced families to return to the city. But the group’s support base never grew, amid a series of failed missions and fears that some of its members still had links to extremists within the anti-Haftar movement — including affiliates of al-Qaeda. However, as its successful (if fleeting) capture of the El Sider and Ras Lanuf oil terminals in March 2017 showed, the group did still have a role to play.</p>
                <p>The BDB is known for its role in the Brak al-Shatti massacre. On 18 May 2017, together with the 13th Battalion, it launched a surprise attack on the LNA’s 12 Brigade in Brak al-Shatti while the latter was withdrawing towards the town of Tukrah.<sup>53</sup> At least 140 men were slaughtered with guns and knives, including both LNA fighters and a few civilian truck drivers.<sup>54</sup></p>
                <p>The Brak al-Shatti massacre brought the political reconciliation process to a stalemate. Three weeks earlier, Haftar and Fayez al-Sarraj, the chairman of Libya's Presidential Council, met in Abu Dhabi and affirmed the truce in the south.<sup>55</sup> In response to the BDB’s assault, Haftar carried out a counterattack, which forced the BDB to abandon its positions in Jufra.<sup>56</sup> The BDB disbanded in 2017. </p>
                <p>The BDB had made efforts to engage in Libya’s political process alongside its military offensive against Haftar. It, however, acted on the fringes, allegedly with the unsanctioned approval of some GNA defence ministry personnel.<sup>57</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="17">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">September 2016 to June 2018</div>
                Haftar’s forces control terminals in the oil crescent
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>In September 2016, forces aligned with Khalifa Haftar seized key terminals in Libya’s oil crescent. Using a strategy of tribal outreach, Haftar’s forces routed Ibrahim Jadhran, a commander of the controversial Petroleum Facilities Guard (PFG), who had blockaded the ports for nine months in 2013 and 2014 and whose forces remained in control of the oil crescent. With much of Libya’s lucrative oil sector now under Haftar’s control, this served as a powerful bargaining tool and prompted a shift in his favour in Western capitals, particularly in Europe.</p>
                <p>In March 2017, the Benghazi Defense Brigades (BDB) briefly seized the terminals before Haftar’s forces retook them. Despite Haftar’s position towards the Tripoli-based Central Bank of Libya (CBL), he allowed the existing system of channelling oil revenues — whereby monies are collected by the National Oil Corporation (NOC) and subsequently transmitted to the CBL in Tripoli, which funds and manages public expenditure — to continue because to disrupt it would risk international opprobrium. Haftar’s claims to be safeguarding the terminals in the national interest were undermined, however, when in June 2018 he announced that his forces were handing over control of the oil ports to the unrecognised rival NOC in the east.</p>
                <p>This parallel body had struggled for years to assert itself, having failed on a number of occasions to sell oil illicitly despite UN resolutions banning any sales that did not involve the Tripoli-based NOC. Haftar’s move massively dented oil production and threatened to further damage reconciliation efforts.<sup>58</sup> There was swift international condemnation of Haftar’s decision, including a warning of legal action from the US if any oil sales were attempted.</p>
                <p>Three weeks later, Haftar backed down following international pressure and reminders of the repercussions of any bid to sell oil outside the auspices of the Tripoli-based NOC. He returned control of the terminals to the recognised NOC in Tripoli without gaining any tangible concessions. His relationship with the NOC has remained testy ever since, even as his aligned forces remain in control of the oil crescent. </p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="18">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">December 2016</div>
                Islamic State group is driven from its Sirte stronghold
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>After establishing its first Libyan affiliate in the eastern town of Derna, the Islamic State group (IS) developed a presence both in Benghazi, where it fought the LNA, and around Sabratha in western Libya. But it was Gaddafi’s hometown of Sirte that became the main stronghold of IS in Libya.</p> 
                <p>From late 2014, IS tapped into local grievances rooted in the city’s marginalisation following the 2011 uprising, and also manipulated local tribal dynamics to eventually take control. As in Derna, foreign members of IS were key to establishing its affiliate in Sirte, but the Libyans who joined IS there included those who had defected from a local branch of Ansar al-Sharia and associated groups such as the Farouq brigade from Misrata. In February 2015, IS released a video showing the beheading of 21 Egyptians, which was apparently filmed near Sirte.</p> 
                <p>In August 2015, Sirte residents opposed to IS rule attempted an uprising following the group’s brutal assassination of Khalid al-Ferjani, a local Salafist imam critical of the group’s growing power. The revolt was brutally quashed, however, with scores killed. IS went on to consolidate its control, often carrying out public executions to instil fear in Sirte’s population.</p>
                <p>In May 2016, a coalition of Misrata-dominated forces known as Bunyan al-Marsous (BAM) launched an operation which, aided by over 400 US airstrikes against IS targets in and around Sirte, successfully dislodged the militants after a months-long fight that resulted in widespread destruction across several neighbourhoods. Most of the BAM coalition was anti-Haftar and included Madkhali-Salafists who wanted to avenge Ferjani’s killing, most of whom were part of the predominantly Madkhali-Salafist 604 battalion.</p>
                <p>Fleeing Sirte, many IS fighters — the majority of whom were not Libyan — either headed southeast towards the border with Sudan, directly south into Libya’s central desert, southwest towards Sebha, or west towards Sabratha. Estimates vary, but according to some intelligence sources, in 2018 IS still had at least 600 fighters in Libya,<sup>59</sup> predominantly in southwest and central regions, but also near Bani Walid and south of Sirte, including in the Jufra hinterland.<sup>60</sup> While weakened and no longer controlling territory, IS remains a threat, as audacious attacks on symbolic targets in Tripoli in 2018, including the High National Election Commission (HNEC), the National Oil Corporation (NOC) and the foreign ministry, have shown.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="19">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">May to June 2017</div>
                National power struggle leads to proxy conflicts in southern Libya
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>Southern Libya, with its multitude of tribal and ethnic groups along with its much-prized oil and water resources, experienced a rapid escalation of violence in the summer of 2017. This was linked to the wider national power struggle between Khalifa Haftar’s Libyan National Army (LNA) and forces aligned with Tripoli’s internationally recognised Government of National Accord (GNA).</p>
                <p>Haftar and his opponents, including Misratan forces, had for some years earlier tried to manipulate local dynamics in the neglected region for their own purposes, as they sought to expand their control of territory and strategic assets to shore up their position on the national stage.</p>
                <p>Tensions among the southern tribes, which have fought five successive local wars since the 2011 uprising, mostly over control of resources, have facilitated proxy rivalries.</p>
                <p>In December 2016, the LNA's 12th Brigade took control of the Brak al-Shatti airbase in Libya's southwest after the GNA-allied Misratan Third Force was forced to withdraw. The LNA had an invaluable base for operations in southern Libya, a region where it held little influence up to that stage.</p>
                <p>In May 2017, a raid on the Brak al-Shatti airbase by the Benghazi Defense Brigades (BDB) and Misratan forces left at least 140 people dead.<sup>61</sup> Mahdi al-Barghathi, the GNA defence minister and a former Haftar ally in Operation Dignity in Benghazi, was accused of complicity in the raid.</p>
                <p>In the spring of 2018, a battle in the key town of Sebha lasting weeks gave LNA-aligned forces the upper hand. Significantly, the LNA now controlled the Tamanhint and Jufra airbases. LNA-aligned armed groups ramped up their recruitment of mostly Sudanese and Chadian fighters, as did their rivals. Sudanese and Chadian rebel groups established their own hubs within Libya’s southern borders, which further complicated local alliances.<sup>62</sup></p>
                <p>After Haftar made a series of announcements claiming to launch operations to clamp down on lawlessness and foreigners in southern Libya, he deployed forces in and around Sebha in January 2019. This raised concerns of fresh fighting between the LNA and GNA-allied forces, amid yet another possible realignment of local loyalties. By late February, the LNA had expanded throughout southern Libya, claiming control of other key towns.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="20">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">July 2017</div>
                Haftar declares Benghazi “liberated” but fighting continues
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>More than three years after Khalifa Haftar launched Operation Dignity in Benghazi, in July 2017 he declared that the city had been “liberated”,<sup>63</sup> even as fighting there continued in pockets. Several districts of the city, particularly its downtown areas, were devastated by years of war. Major reconstruction and reconciliation challenges lay ahead, especially as the city continued to experience insecurity in the form of assassinations and bombings.</p>
                <p>In January 2018, shortly after Haftar’s forces claimed that they had cleared the final redoubts of their opponents, Benghazi was rocked by one of the deadliest attacks in post-Gaddafi Libya, when unidentified attackers detonated two car bombs in front of a mosque. The double explosions killed at least 34 people, mostly civilians. No group took responsibility for the blasts. The mosque bombings were followed the next day by the public summary executions of ten detainees held as suspects by Mahmoud al-Warfalli, a commander in the LNA’s Saiqa special forces, who was already wanted by the International Criminal Court (ICC) for alleged war crimes. Al-Warfalli remains at large despite LNA claims that it would investigate him itself.</p>
                <p>Haftar’s coalition continued to come under further internal strain, with tensions between the Saudi-inspired Madkhali-Salafists in his fighting forces and other elements, in addition to rivalries between various tribal components. The increasing power of the ultra-conservative Madkhali-Salafists, who are not only studded throughout the LNA and wider security apparatus but also have commandeered religious institutions and mosques across eastern Libya, has prompted increasing unease, particularly among civil society and religious minorities targeted by the Madkhalis, including Sufis.<sup>64</sup></p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="21">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">May 2018</div>
                Haftar launches an offensive on Derna
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>After subjecting Derna to a punishing blockade for over a year, Khalifa Haftar announced the beginning of a Libyan National Army (LNA) military offensive aimed at capturing the only town in eastern Libya that remained out of the control of his forces.<sup>65</sup> The Derna Mujaheddin Shura Council (DMSC), a coalition formed by locals and former Libyan Islamic Fighting Group (LIFG) members, which had driven the Islamic State group from the town in 2015, had earlier announced that it was dissolving and joining the newly formed Derna Protection Force (DPF), now the dominant armed faction. The DPF provided a safe haven for former jihadists and jihadist-linked figures in Derna.<sup>66</sup> The length of the LNA’s blockade, which affected fuel and medical supplies, as well as the ability of residents to travel freely to and from Derna, had changed the town’s internal dynamics, with the DPF gaining more sympathy from former opponents who had previously bristled at its jihadist tilt.</p>
                <p>Haftar’s move on Derna in May came after speculation about his health, following a trip to Paris for emergency medical treatment. The offensive included aerial bombardment of targets within Derna but also the deployment of tribal militiamen from its hinterland with a history of animosity towards the town’s population. Haftar’s backers in Cairo were particularly keen to see his forces take control of Derna, given its proximity to Egypt’s border with Libya and the fact that Egyptian militants had hidden there. </p>
                <p>In June, Haftar announced the “liberation” of Derna but clashes have continued, and the town remains restive today, with scores dead and thousands displaced.</p>
            </div>
        </div>
        <div class="right-panel__part" data-panel="22">
            <div class="right-panel__subheading" data-panel="heading">
                <div class="date">August and September 2018</div>
                Militia fighting erupts in Tripoli
            </div>
            <div class="right-panel__text" data-panel="text">
                <p>In August 2018, clashes between rival militias escalated into some of the most serious fighting Tripoli has seen since 2014. The violence drew in factions from outside the capital, including the Tarhouna-based Kani brigade from its outskirts and Misratan militia leader and former Government of National Accord (GNA) member Salah Badi, who played a key role in the Libya Dawn offensive in 2014. It also dealt another blow to international claims of improved security.<sup>67</sup> Similar to previous militia battles in Tripoli, the clashes were rooted in contests over turf, influence and a share of the letters of credit (LCs) profiteering scheme.<sup>68</sup> A key element involved growing resentment over what has become known as the “cartel” of powerful militias who hold sway in the capital, largely due to their alignment with the UN-backed GNA.<sup>69</sup> The militia balance of power in Tripoli had shifted several times since the Libya Dawn coalition took control of the city in the summer of 2014. Groups such as Rada — one of the biggest armed groups — and the Tripoli Revolutionaries Brigade, led by Haithem Tajouri, had become dominant players by 2018.</p>
                <p>A notable aspect of the August battle was the role played by Madkhali-Salafists from Tripoli in coordination with those from other parts of western Libya. Badi and others cited concern over their growing power and influence as one of their motivations to fight.<sup>70</sup> Meanwhile, Madkhali-Salafist elements in Rada and other key militias rallied to form what they call the Tripoli Protection Force in response.<sup>71</sup> UN-backed negotiations that eventually led to a ceasefire were anchored in a return to the old order, but tensions remained as grievances — particularly those of rival armed groups resentful over their loss of influence in the capital — were left unresolved. The UN Security Council sanctioned Badi for his role in the violence within residential neighbourhoods. Further clashes were to break out in the months that followed, a sign that the deeper roots of the militia rivalries that continued to plague Tripoli — namely the jockeying over proximity to state institutions — have not been tackled.</p>
            </div>
        </div>
        <div class="right-panel__part">
            <div class="footnotes">
                <div class="footnotes__line"></div>
                <div class="footnotes__wrapper">
                    <ol class="footnotes__list">
                        <li> Mary Fitzgerald, "Finding Their Place”, in The Libyan Revolution and Its Aftermath, eds. Peter Cole and Brian McQuinn (Oxford: Hurst/Oxford University Press, 2015).</li>
                        <li> Fitzgerald, "Finding Their Place”.</li>
                        <li> Peter Cole with Umar Khan, “The Fall of Tripoli: Part 1” and “The Fall of Tripoli: Part 2”, in The Libyan Revolution and Its Aftermath, eds. Peter Cole and Brian McQuinn (Oxford: Hurst/Oxford University Press, 2015).</li>
                        <li> Mary Fitzgerald, “Is civil war likely?”, Economist, 25 August 2014. <a href="https://www.economist.com/pomegranate/2014/08/25/is-civil-war-likely">https://www.economist.com/pomegranate/2014/08/25/is-civil-war-likely</a> (17 April 2019)</li>
                        <li> Wolfram Lacher and Alaa al-Idrissi, “Capital of Militias: Tripoli’s Armed Groups Capture the Libyan State”, Small Arms Survey, Geneva, June 2015. <a href="https://www.academia.edu/36954401/CAPITAL_OF_MILITIAS_-_Tripolis_Armed_Groups_Capture_the_Libyan_State_2018">https://www.academia.edu/36954401/CAPITAL_OF_MILITIAS_-_Tripolis_Armed_Groups_Capture_the_Libyan_State_2018</a> (15 April 2019)</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Kim Sengupta, “Armed federalists shut down Libya oil terminals ahead of vote”, Independent, 6 July 2012. <a href="https://www.independent.co.uk/news/world/africa/armed-federalists-shut-down-libya-oil-terminals-ahead-of-vote-7920590.html">https://www.independent.co.uk/news/world/africa/armed-federalists-shut-down-libya-oil-terminals-ahead-of-vote-7920590.html</a> (17 April 2019)</li>
                        <li> CNN, “Benghazi Mission Attack Fast Facts”, 4 September 2018. <a href="https://edition.cnn.com/2013/09/10/world/benghazi-consulate-attack-fast-facts/index.html">click</a></li>
                        <li> CNN, “Benghazi Mission Attack Fast Facts”.</li>
                        <li> US Department of Justice statement, posted on its website, 27 June 2018.</li>
                        <li> Ali Shuaib, “Civilians flee besieged former Gaddafi stronghold in Libya”, Reuters, 22 October 2012. <a href="https://www.reuters.com/article/us-libya-clashes-idUSBRE89L11B20121022">https://www.reuters.com/article/us-libya-clashes-idUSBRE89L11B20121022</a> (17 April 2019)</li>
                        <li> Human Rights Watch, “Libya: Residents of Bani Walid at Risk”, Beirut, 24 October 2012. <a href="https://www.hrw.org/news/2012/10/24/libya-residents-bani-walid-risk">https://www.hrw.org/news/2012/10/24/libya-residents-bani-walid-risk</a> (17 April 2019)</li>
                        <li> Human Rights Watch, “Libya: Reject ‘Political Isolation Law’’, Beirut, 4 May 2013. <a href="https://www.hrw.org/news/2013/05/04/libya-reject-political-isolation-law">https://www.hrw.org/news/2013/05/04/libya-reject-political-isolation-law</a> (17 April 2019)</li>
                        <li> Esam Mohammed, “Militiamen besiege Libya’s Justice Ministry”, Associated Press, 30 April 2013. <a href="https://eu.usatoday.com/story/news/world/2013/04/30/militiamen-besiege-libyas-justice-ministry/2122979/">https://eu.usatoday.com/story/news/world/2013/04/30/militiamen-besiege-libyas-justice-ministry/2122979/</a> (17 April 2019)</li>
                        <li> BBC News, “Libya revokes bill which banned Gaddafi-era officials from office”, 2 February 2015. <a href="https://www.bbc.com/news/world-latin-america-31104099">https://www.bbc.com/news/world-latin-america-31104099</a> (17 April 2019)</li>
                        <li> Andrew Simmons, “Libya’s oil blockade: A crude solution”, Al Jazeera, 11 April 2014. <a href="https://www.aljazeera.com/indepth/features/2014/04/libya-oil-blockade-crude-solution-201441111361220765.html">https://www.aljazeera.com/indepth/features/2014/04/libya-oil-blockade-crude-solution-201441111361220765.html</a> (29 May 2019)</li>
                        <li> Simmons, “Libya’s oil blockade”.</li>
                        <li> International Crisis Group, “The Prize: Fighting for Libya’s Energy Wealth”, Brussels, 25 October 2018. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/prize-fighting-libya-s-energy-wealth">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/prize-fighting-libya-s-energy-wealth</a> (17 April 2019)</li>
                        <li> Daveed Gartenstein-Ross and Nathaniel Barr, “Dignity and Dawn: Libya’s Escalating Civil War”, International Centre for Counter-Terrorism, The Hague, February 2015. <a href="https://www.icct.nl/download/file/ICCT-Gartenstein-Ross-Barr-Dignity-and-Dawn-Libyas-Escalating-Civil-War-February2015.pdf">https://www.icct.nl/download/file/ICCT-Gartenstein-Ross-Barr-Dignity-and-Dawn-Libyas-Escalating-Civil-War-February2015.pdf</a> (17 April 2019)</li>
                        <li> Mary Fitzgerald, “Libyan renegade general Khalifa Haftar claims he is winning his war”, Guardian, 24 June 2014. <a href="https://www.theguardian.com/world/2014/jun/24/libyan-renegade-general-khalifa-haftar-war">https://www.theguardian.com/world/2014/jun/24/libyan-renegade-general-khalifa-haftar-war</a> (17 April 2019)</li>
                        <li> “Ra’ees al-arkaan ya’mer silaah al-jaw bi-mane’ ayy taharrok li-quwwat Hifter”, Quryna al-Jadida, 16 May 2014.</li>
                        <li> Noureddine Jebnoun, “Beyond the mayhem: debating key dilemmas in Libya’s statebuilding”, Journal of North African Studies, Vol. 20, Issue 5, pp. 832–864.</li>
                        <li> Nizar Sarieldin, “The Battle for Benghazi: The Limits of Stabilization by Military Means”, German Institute for International and Security Affairs, February 2015. <a href="https://www.swp-berlin.org/fileadmin/contents/products/comments/2015C08_srd.pdf">https://www.swp-berlin.org/fileadmin/contents/products/comments/2015C08_srd.pdf</a> (29 May 2019)</li>
                        <li> Libya Herald, “Supreme Council of Libyan Revolutionaries Condemn Operation Dignity’s ‘Evil Attacks’”, 19 June 2014. <a href="https://www.libyaherald.com/2014/06/19/supreme-council-of-libyan-revolutionaries-condemn-operation-dignitys-evil-attacks/">https://www.libyaherald.com/2014/06/19/supreme-council-of-libyan-revolutionaries-condemn-operation-dignitys-evil-attacks/</a>(29 May 2019)</li>
                        <li> Ishaan Tharoor and Adam Taylor, “Here are the key players fighting the war for Libya, all over again”, Washington Post, 27 August 2014. <a href="https://www.washingtonpost.com/news/worldviews/wp/2014/08/27/here-are-the-key-players-fighting-the-war-for-libya-all-over-again/?utm_term=.c76397157309">https://www.washingtonpost.com/news/worldviews/wp/2014/08/27/here-are-the-key-players-fighting-the-war-for-libya-all-over-again/?utm_term=.c76397157309</a> (29 May 2019)</li>
                        <li> Sari Arraf, “The War Report 2017, Libya: A Short Guide on the Conflict”, The Geneva Academy, Geneva, June 2017. <a href="https://geneva-academy.ch/joomlatools-files/docman-files/Lybia%20A%20Short%20Guide%20to%20the%20Conflict.pdf">https://geneva-academy.ch/joomlatools-files/docman-files/Lybia%20A%20Short%20Guide%20to%20the%20Conflict.pdf</a> (29 May 2019)</li>
                        <li> UN Security Council, “Final Report of the Panel of Experts on Libya regarding the implementation of the measures related to the arms embargo, the assets freeze and the travel ban”, New York, NY, 23 February 2015. <a href="http://www.derechos.org/peace/libya/doc/lby1664.html">http://www.derechos.org/peace/libya/doc/lby1664.html</a> (29 May 2019)</li>
                        <li> Libya Al Ahrar TV, “Tripoli District Residents Express Support for Army Against ‘Terrorists’”,19 May 2014.</li>
                        <li> Gartenstein-Ross and Barr, “Dignity and Dawn: Libya’s Escalating Civil War”.</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Sarieldin, “The Battle for Benghazi”.</li>
                        <li> Mary Fitzgerald and Mattia Toaldo, “A Quick Guide to Libya’s Main Players”, European Council on Foreign Relations, London, January 2018. <a href="https://www.ecfr.eu/mena/mapping_libya_conflict">https://www.ecfr.eu/mena/mapping_libya_conflict</a> (17 April 2019)</li>
                        <li> Al Jazeera, “Libya embargo violations: UN panel to report findings to UNSC”, 1 March 2018. <a href="https://www.aljazeera.com/news/2018/03/libya-embargo-violations-panel-report-findings-unsc-180301080019627.html">https://www.aljazeera.com/news/2018/03/libya-embargo-violations-panel-report-findings-unsc-180301080019627.html</a> (17 April 2019)</li>
                        <li> Agence France-Presse, “Splits emerge between Libyan Islamists and Jihadists”, 18 August 2014. <a href="https://news.yahoo.com/splits-emerge-between-libyan-islamists-jihadists-183000425.html">https://news.yahoo.com/splits-emerge-between-libyan-islamists-jihadists-183000425.html</a> (29 May 2019)</li>
                        <li> Gartenstein-Ross and Barr, “Dignity and Dawn: Libya’s Escalating Civil War”.</li>
                        <li> Al-Wasat, “Tadhaahoraat dhakhma fi Benghazi tahtef dhad Ansar al-Sharee’a wal-durou”, 1 August 2014, <a href="http://alwasat.ly/news/libya/26952">http://alwasat.ly/news/libya/26952</a> (17 April 2019)</li>
                        <li> Al-Wasat, “Quwwaat ‘al-Karaama’ tutaaleb min shabaab Benghazi ta’meen manaateqhom”, 13 October 2014.</li>
                        <li> Mohamed Eljarh, “Libya: The Lesser of Two Evils”, Atlantic Council, Washington, D.C., 22 October 2014, <a href="https://www.atlanticcouncil.org/blogs/menasource/libya-the-lesser-of-two-evils">https://www.atlanticcouncil.org/blogs/menasource/libya-the-lesser-of-two-evils</a> (17 April 2019)</li>
                        <li> Amnesty International, “Libya: Benghazi’s Descent Into Chaos: Abductions, Summary Killings and Other Abuses”, Beirut, 28 January 2015. <a href="https://www.amnesty.org/en/documents/mde19/0001/2015/en/">https://www.amnesty.org/en/documents/mde19/0001/2015/en/</a> (30 May 2019)</li>
                        <li> Hisham al-Shalwi, “Al-sahwaat al-jadeeda fi Leebeeya: takteek aakhar li-Hifter”, Al-Arabi Al-Jadid, 20 October 2014.</li>
                        <li> Fitzgerald and Toaldo, “A Quick Guide to Libya’s Main Players”.</li>
                        <li> Fitzgerald, "Finding Their Place”.</li>
                        <li> Fitzgerald and Toaldo, “A Quick Guide to Libya’s Main Players”.</li>
                        <li> Christoper S. Chivvis, “Countering the Islamic State in Libya”, Survival, Vol. 58, No. 4, 2016, pp. 113—130.</li>
                        <li> “ISIS in Libya: A Major Regional and International Threat”, Meir Amit Intelligence and Terrorism Information Center, Ramat Hasharon, January 2016, pp. 27–8. <a href="https://www.terrorism-info.org.il//Data/articles/Art_20943/E_209_15_1076923854.pdf">https://www.terrorism-info.org.il//Data/articles/Art_20943/E_209_15_1076923854.pdf</a> (13 May 2019)</li>
                        <li> U.S. Department of Defense, Briefing by General David Rodriguez, 7 April 2016.</li>
                        <li> Fitzgerald and Toaldo, “A Quick Guide to Libya’s Main Players”.</li>
                        <li> “Statement (1): The Establishment of the Benghazi Defense Brigade”, 2 June 2016. <a href="https://www.youtube.com/watch?v=2DWz_VOdzbM">https://www.youtube.com/watch?v=2DWz_VOdzbM</a> (30 May 2019)</li>
                        <li> Libya Herald, “Heavy air raids as PFG chief says LNA trying to hit oil facilities”, 12 March 2017. <a href="https://www.libyaherald.com/2017/03/12/heavy-air-raids-as-pfg-chief-says-lna-trying-to-hit-oil-facilities/">https://www.libyaherald.com/2017/03/12/heavy-air-raids-as-pfg-chief-says-lna-trying-to-hit-oil-facilities/</a> (30 May 2019)</li>
                        <li> “Statement (1): The Establishment of the Benghazi Defense Brigade."</li>
                        <li> Andrew McGregor,  “Libya’s Military Wild Card: The Benghazi Defense Brigades and the Massacre at Brak al-Shatti”, Terrorism Monitor, Vol. 15, Issue 11, The Jamestown Foundation for Global Research and Analysis, Washington, D.C., June 2017. <a href="https://www.ecoi.net/de/dokument/1401836.html">https://www.ecoi.net/de/dokument/1401836.html</a> (17 April 2019)</li>
                        <li> Agenzia Nova, “Libia: ex membri della Shura di Bengasi alla guida delle nuove brigate arrivate ad Agedabia”, 20 June 2016. <a href="https://www.agenzianova.com/a/5767d1e3ae9550.93815045/1372340/2016-06-20/libia-ex-membri-della-shura-di-bengasi-alla-guida-delle-nuove-brigate-arrivate-ad-agedabia/linked">https://www.agenzianova.com/a/5767d1e3ae9550.93815045/1372340/2016-06-20/libia-ex-membri-della-shura-di-bengasi-alla-guida-delle-nuove-brigate-arrivate-ad-agedabia/linked</a> (13 May 2019)</li>
                        <li> McGregor,  “Libya’s Military Wild Card”. </li>
                        <li> Laureen Fagan, “Brak al-Shati forces new questions on what it will take to make the LPA work”, Africa Times, 21 May 2017. <a href="https://africatimes.com/2017/05/21/brak-al-shati-forces-new-questions-on-what-will-it-take-to-make-the-lpa-work/">https://africatimes.com/2017/05/21/brak-al-shati-forces-new-questions-on-what-will-it-take-to-make-the-lpa-work/</a> (30 May 2019)</li>
                        <li> Fagan, “Brak al-Shati forces new questions”.</li>
                        <li> Elissa Miller and Tarek Radwan, “Can Libya Survive Without Haftar?”, Atlantic Council, Washington, D.C., 16 April 2018. <a href="https://www.atlanticcouncil.org/blogs/menasource/can-libya-survive-without-haftar">https://www.atlanticcouncil.org/blogs/menasource/can-libya-survive-without-haftar</a> (30 May 2019)</li>
                        <li> McGregor,  “Libya’s Military Wild Card”. </li>
                        <li> International Crisis Group, “After the Showdown in Libya’s Oil Crescent”, Brussels, 9 August 2018. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/189-after-showdown-libyas-oil-crescent">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/189-after-showdown-libyas-oil-crescent</a> (17 April 2019)</li>
                        <li> Author interviews. </li>
                        <li> Fitzgerald and Toaldo, “A Quick Guide to Libya’s Main Players”.</li>
                        <li> BBC News, “Libya death toll 'rises to 140' at Brak El-Shati airbase”, 20 May 2017. <a href="https://www.bbc.com/news/world-africa-39983806">https://www.bbc.com/news/world-africa-39983806</a> (30 May 2019)</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Ayman al-Warfalli, “Libya’s eastern commander declares victory in battle for Benghazi”, Reuters, 5 July 2017. <a href="https://www.reuters.com/article/us-libya-security-benghazi/libyas-eastern-commander-declares-victory-in-battle-for-benghazi-idUSKBN19Q2SK">https://www.reuters.com/article/us-libya-security-benghazi/libyas-eastern-commander-declares-victory-in-battle-for-benghazi-idUSKBN19Q2SK</a> (30 May 2019)</li>
                        <li> International Crisis Group, “Addressing the Rise of Libya’s Madkhali-Salafis”, Brussels, 25 April 2019. <a href="https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/addressing-rise-libyas-madkhali-salafis">https://www.crisisgroup.org/middle-east-north-africa/north-africa/libya/addressing-rise-libyas-madkhali-salafis</a> (30 May 2019)</li>
                        <li> Ayman al-Warfalli, “Libyan commander declares ‘zero hour’ for campaign to take city”, Reuters, 7 May 2018. <a href="https://www.reuters.com/article/us-libya-security/libyan-commander-declares-zero-hour-for-campaign-to-take-city-idUSKBN1I824R">https://www.reuters.com/article/us-libya-security/libyan-commander-declares-zero-hour-for-campaign-to-take-city-idUSKBN1I824R</a> (17 April 2019)</li>
                        <li> Kevin Truitte, “The Derna Mujahideen Shura Council: A Revolutionary Islamist Coalition in Libya”, Perspectives on Terrorism, Vol. 12, Issue 5, October 2016. <a href="https://www.radicalisationresearch.org/research/truitte-derna-mujahideen-shura-council/">https://www.radicalisationresearch.org/research/truitte-derna-mujahideen-shura-council/</a> (30 May 2019) </li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Lacher and al-Idrissi, “Capital of Militias”.</li>
                        <li> Al-Manassa, “الجمعة سوق إلى بادي صلاح رسالة تنشر المنصة” [“Al-Manassa publishes Salah al-Badi’s letter to Suq al-Juma”], 5 September 2018. <a href="https://elmanassa.com/news/view/20341">https://elmanassa.com/news/view/20341</a> (30 May 2019)</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>