<div class="top-line">
    <div class="line__heading"></div>
    <div class="line__line-wrapper">
        <div class="line__segment line__segment--top"></div>
        <div class="line__segment line__segment--top">
            <div class="top-line__btn-wrapper">
                <div class="top-line__btn" data-btn="2">
                    <div class="top-line__bracket top-line__bracket-left"><?php echo file_get_contents("parts/svg/bracket-left.svg"); ?></div>
                    <div class="top-line__text-wrapper">
                        <div class="top-line__btn-line-left"></div>
                        <div class="top-line__text">
                        <p dir="rtl" lang="ar">دخلت ليبيا من جديد نزاع مسلح بعد ثماني سنوات من ثورة 2011 التي أطاحت بمعمر القذافي ونظامه. فما زالت البلاد تعاني من الفوضى وتردي الظروف الاقتصادية وضعف مؤسسات الدولة. وتُعزى أسباب التشرذم الأمني الذي عرقل الانتقال بشدة في حقبة ما بعد القذافي، في معظمها، إلى فشل برامج نزع السلاح وإعادة إدماج المقاتلين وإلى الصراع على الشرعية<sup>1</sup>.</p>
                        <p dir="rtl" lang="ar">تفسر هذه العوامل سلوك المجموعات المحلية لحماية مصالحها القبلية أو الجغرافية أو الإثنية أو الإيديولوجية وأمنها عندما تواجه شكوكاً بشأن المستقبل، وخاصة تلك الناجمة عن قلة الفرص الاقتصادية وتدهور ظروف المعيشة<sup>2</sup>. فقد قسمت الحرب الأهلية الشعب في عام 2011، إلى مؤيدين ومعارضين للنظام السابق. وأوجدت حالة استقطاب بين المناطق والمدن والبلدات، ما جعل الكثير منهم يندرج في فئتين عريضتين هما "الرابحون" و"الخاسرون".</p>
                        <p dir="rtl" lang="ar">ومع تطور الأحداث في عام 2011، اتضح أن مؤسسات الدولة والأمن التي أورثها القذافي كانت هشة وتفتقد إلى الشرعية لدرجة تعجز عن مقاومة الاضطرابات التي نشبت عقب 17 فبراير. وجد الليبيون أنفسهم فجأة يحاولون بمفردهم خوض غمار الحياة في غياب "قواعد اللعبة"؛ أي غياب مؤسسات سياسية تستطيع رسم خطط لتحقيق المصالحة والعدالة الانتقالية وإدارة عملية سياسية تشاركية. إذ لم يشارك الليبيون في الحياة السياسية طوال 42 عاماً، ولم يستطيعوا التحدث بحرية أو تنظيم أنفسهم سياسياّ.</p>
                        <p dir="rtl" lang="ar">جاءت عملية صياغة الدستور في إطار جهود المجلس الوطني الانتقالي لتحديد قواعد اللعبة. حظي المجلس، الذي تأسس في 2 مارس 2011، بدعم دولي واعترف به الليبيون ممثلاً شرعياً للثورة. وتمكن من تأمين الاستقرار الأساسي وتشكيل حكومة قائمة على تقاسم السلطة في إطار خريطة طريق لمرحلة الانتقال السياسي في ليبيا. وانتعش الاقتصاد وأجريت انتخابات برلمانية وحررت وسائل الإعلام وازدهر المجتمع المدني أثناء تلك الفترة القصيرة، من 2011 إلى 2013. لكن تبين أن الإصلاح كان سطحياً لأن آليات التنفيذ لم تكن موجودة. وقُوِّضت المكاسب السياسية والاقتصادية والاجتماعية مع نهاية 2013 ومطلع 2014 عندما دخلت البلاد حرب أهلية ثانية.</p>
                        <p dir="rtl" lang="ar">كان الاقتصاد جزءاً مهماً من القصة كما يبيِّن تحليلنا. فليبيا دولة ثرية نسبياً، لكنها تعتمد على النفط، واقتصادها غير متنوع. وترجمت هذه الثروة بالفعل إلى نصيب أعلى من الناتج المحلي الإجمالي للفرد مقارنة بجيرانها في شمال إفريقيا لغاية عام 2011، حيث بلغ 12686 دولار<sup>3</sup>. وسمح ذلك لليبيين بالحصول على تعليم ورعاية صحية على نطاق أوسع. ولكن جودة هذه الخدمات كانت رديئة عمليّا.</p>
                        <p dir="rtl" lang="ar">تمتلك ليبيا أكبر احتياطي مثبت من النفط الخام (نحو 48.4 مليار برميل) على مستوى القارة، وخامس أكبر احتياطي مثبت من الغاز الطبيعي في إفريقيا<sup>4</sup>.</p>
                        <p dir="rtl" lang="ar">أنتجت ليبيا قرابة 1.56 مليون برميل يومياً من النفط الخام<sup>5</sup> في عام 2010. وتوقفت صادرات النفط الليبية، أثناء ثورة 2011، ووُجِّه الإنتاج المتبقي الى الاستهلاك المحلي<sup>6</sup>. وانتعش إنتاج النفط على الفور، بعد سقوط القذافي، من توقف كامل للإنتاج إلى 1.1 مليون برميل/اليوم<sup>7</sup>. اكتسبت الحكومة الانتقالية ثقة بقدرتها على تمويل إعادة الإعمار وبدأت تستثمر بكثافة في إعادة البناء وتوسيع قطاع الأمن<sup>8</sup>.</p>
                        <p dir="rtl" lang="ar">بيد أن انتعاش قطاع النفط والغاز في الفترة 2011-2012 لم يدم طويلاً. فتلاشى التفاؤل عندما بدأت منافسة شديدة للسيطرة على الموارد الطبيعية. كان الخلل الرئيس في إنتاج وتصدير النفط والغاز من عام 2012 إلى عام 2014 هو انعدام الأمن الناتج عن العنف الناتج عن الأنشطة الإجرامية والنزاع المسلح. وفي هذا الصدد، وقعت الحادثة الأكثر دراماتيكية في يوليو 2013، عندما تسببت إضرابات العمال والحصار الذي فرضته قوات حرس المنشآت النفطية، بقيادة الفيدرالي إبراهيم الجضران، في إغلاق موانئ تصدير النفط في خليج سرت والبريقة ورأس لانوف والزويتينة وطبرق.</p>
                        <p dir="rtl" lang="ar">كان دافع النزاعات المسلحة في ليبيا – غالباً –على مدى السنوات الثماني الماضية، هو الطمع بالفرص الاجتماعية والاقتصادية أو بسبب المظالم الناتجة عن هذه الفرص. لقد أثر هذا العامل كثيراً على قدرة الحكومة على تسريح المقاتلين السابقين وفك ارتباطهم وإعادة إدماجهم أو إصلاح قطاع الأمن<sup>9</sup>.</p>
                        <p dir="rtl" lang="ar">أطلقت وزارة الدفاع ووزارة الداخلية في عام 2012، مشروعهما لنزع السلاح والتسريح وإعادة الإدماج، الذي أنشأت بموجبه اللجنة الأمنية العليا وقوة درع ليبيا<sup>10</sup>. وسُجل أكثر من 200000 شخص بصفة مقاتلين في كشوف الرواتب، واستلموا قرابة 1.5 مليار دينار على شكل مدفوعات. وحصلوا أيضا بالإضافة إلى المزايا النقدية، على مساكن وفرص عمل في القطاع العام وائتمان مصرفي وعلاج طبي في الخارج.</p>
                        <p dir="rtl" lang="ar">وحصلت الحكومة كما اتضح، على القليل مقابل إضافة قوات إلى كشوف الرواتب. فلم يتغير الوضع من حيث الجوهر: لم يدمج المستفيدون في أي قوة جديدة بل ظلوا جزءاً من جماعاتهم المسلحة. واحتفظوا بقياداتهم<sup>11</sup>، ولم يُطلب منهم تسليم أسلحتهم. وبالكاد كانوا يعتبرون أنفسهم ممثلين للدولة الليبية ولم يتبعوا إلا أوامر قادتهم. واعتبروا برامج نزع السلاح والتسريح وإعادة الإدماج وسيلة مشروعة للحصول على "حصتهم" المتصورة من الثروة العامة - يسهلها الفساد المؤسسي - وليست دخلاً مقابل أن يصبحوا جزءاً من <sup>12</sup>. بالإضافة إلى ذلك، وقع البرنامج فريسة للتلاعب السياسي من جانب الميليشيات التي حرصت على توجيه الأموال العامة إلى دوائرها. وأصبح أداة للحصول على التدريب والمنح وفرص العمل.</p>
                        <p dir="rtl" lang="ar">وكان عدم وجود شرطة وجيش قويين وموحدين نقطة ضعف أساسية في ليبيا ما بعد القذافي. فالمجموعات السياسية المتنافسة التي أصبحت تتمتع بسلطة سياسية بعد عام 2011 فضلت بناء <sup>13</sup>. كما مُنحت بعض المدن تمويلاً حكومياً لدورها الريادي في القتال ضد القذافي، ما أدى إلى إعادة هيكلة السلطة والسماح بظهور نخب جديدة فيها. وحرمت مناطق أو قبائل معينة من التمويل الحكومي أو نبذت من الحياة العامة من ناحية أخرى، لأنها كانت "موالية للقذافي". وترسخ نهج "رابحين" و"خاسرين" بموجب قانون العزل السياسي الصادر عن المؤتمر الوطني العام، الذي أقصى فعلياً كل من تولى مناصب متوسطة أو عليا أثناء حكم القذافي.</p>
                        <p dir="rtl" lang="ar">وعلى الرغم من نجاح انتخابات المؤتمر الوطني العام وتشكيل حكومة، فإن بصيص الأمل التي شعر به الليبيون تحطم بسبب عجز مؤسسات الدولة الديمقراطية عن تقديم الخدمات الأساسية كالكهرباء والتعليم والرعاية الصحية. ولم تخوّل الحكومة المركزية هياكل الحكم المحلية أداء هذه المهمة على الرغم من تمتع البلديات بشرعية أكبر وقدرات أقوى على تقديم الخدمات. تآكلت الشرعية الشعبية للحكومة المركزية في نهاية عام 2013. وعلى الرغم من سن القانون رقم 59 لعام 2012 بشأن الحكم المحلي، بقي التقدم المحرز في عملية اللامركزية بطيئاً.
</p>
                        <p dir="rtl" lang="ar">نشأ المجتمع المدني بداية في عام 2011 لتقديم المساعدة الإنسانية للمتضررين من العنف سد العجز في تقديم الخدمات. وسُجِّل بحلول عام 2013، أكثر من 2700 منظمة مدنية، بجميع أنواعها وأحجامها واختصاصاتها. واندرج معظمها في فئتين رئيستين: المناصرة وتقديم الخدمات. وفي الانتخابات البرلمانية 2012، سجلت عشرات المنظمات المدنية لمراقبة الانتخابات، في حين اختار كثيرون العمل على العملية الدستورية وتعبئة المواطنين للمشاركة في حوارات بشأن المواضيع الدستورية الرئيسة<sup>14</sup>.
</p>
                  
                            <ol class="footnotes__list" dir="rtl" lang="ar">
                            <li>براين ل. جوب، (محرر)، معضلة انعدام الأمن: الأمن القومي لدول العالم الثالث. (بولدر. كولورادو: لين. رينر، 1992). </li>
                            <li>جان لويس رومان بيروكس، "الجذور العميقة لتفتت الأمن في ليبيا"، دراسات الشرق الأوسط، المجلد. 55، العدد 2 (2019).</li>
                            <li> المرجع السابق.</li>
                            <li>إدارة معلومات الطاقة الأمريكية، موجز التحليل القطري: ليبيا.<a href="https://www.eia.gov/beta/international/analysis_includes/countries_long/Libya/libya.pdf">click</a> (16 مايو 2019)</li>
                            <li> المرجع السابق.</li>
                                <li>المرجع السابق.</li>
                                <li>ريتشارد بارلتروب، "النفط والغاز في حقبة ليبية جديدة: النزاع والاستمرارية"، معهد أكسفورد لدراسات الطاقة، أكسفورد، ورقة معهد أكسفورد لدراسات الطاقة: MEP 22، 2019.<a href=" https://www.oxfordenergy.org/wpcms/wp-content/uploads/2019/02/Oil-and-Gas-in-a-New-Libyan-Era-Conflict-and-Continuity-MEP-22.pdf">click</a> (16 مايو 2019).</li>
                                <li> رالف شامي وآخرون، "ليبيا بعد الثورة: التحديات والفرص"، صندوق النقد الدولي، قسم الشرق الأوسط وآسيا الوسطى، 2012.<a href="https://www.imf.org/external/pubs/ft/dp/2012/1201mcd.pdf">click</a>  (16 مايو 2019)</li>
                                <li>محمد السواني يوسف، "إصلاح قطاع الأمن ونزع سلاح الميليشيات وتسريحها وإعادة إدماجها: التحديات التي تواجه بناء الدولة في ليبيا"، الشؤون العربية المعاصرة، المجلد. 10، رقم 2 (2017).</li>
                                <li> المرجع السابق.</li>
                                <li>كريستوفر شيفيس وجيفري مارتيني، "ليبيا ما بعد القذافي: دروس وتبعات للمستقبل"، مؤسسة راند، سانتا مونيكا، كاليفورنيا، 2014.<a href="http://www.rand.org/content/dam/rand/pubs/research_reports/RR500/RR577/RAND_RR577.pdf">click</a>(16 مايو 2019).</li>
                                <li> مرجع سابق</li>
                                <li> بورزو دراغي، "ليبيا: العودة إلى الطرق القديمة السيئة"، فاينانشال تايمز، 16 فبراير 2012.<a href="https://www.ft.com/content/55f01408-5885-11e1-9f28-00144feabdc0">click</a>  (16 مايو 2019)</li>
                                <li>كارمن جها وفريدريك فولبي، "الدستورية والنظام السياسي في ليبيا 2011-2014: ثلاث خرافات عن الماضي ودستور جديد"، مجلة دراسات شمال إفريقيا، المجلد. 21، رقم 4 (2016)، 687-706.</li>
                            </ol>
                        </div>
                        <div class="top-line__btn-line-right"></div>
                    </div>
                    <div class="top-line__heading">
                        <div class="top-line__date">2011-2013</div>
                        <div class="top-line__heading-bold">Analysis</div>
                    </div>
                    <div class="top-line__heading-big">
                        2011-2013 <span class="top-line__heading-text"></span>
                    </div>
                    <div class="top-line__bracket  top-line__bracket--right"><?php echo file_get_contents("parts/svg/bracket-right.svg"); ?></div>
                </div>
            </div>
        </div>
        <div class="line__segment line__segment--top"></div>
        <div class="line__segment line__segment--top"></div>
        <div class="line__segment line__segment--top">
            <div class="top-line__btn-wrapper">
                <div class="top-line__btn" data-btn="5">
                    <div class="top-line__bracket top-line__bracket-left"><?php echo file_get_contents("parts/svg/bracket-left.svg"); ?></div>
                    <div class="top-line__text-wrapper">
                        <div class="top-line__btn-line-left"></div>
                        <div class="top-line__text">
                            <p>Three years after the NATO-led military intervention, Libya descended, for the second time, into a full-blown civil war. After the overthrow of Gaddafi and his regime, the international community was cautious not to get entangled in another complex post-conflict setting in the Middle East. While international actors and Western governments committed themselves to the responsibility to protect, some forwent the responsibility to rebuild.<sup>19</sup> “Libya is for the Libyans” was a slogan that proved popular not only among the national political leadership but also among international policymakers.<sup>20</sup></p>
                            <p>The UN Support Mission for Libya (UNSMIL), established by UN Security Council Resolution 2009 on 16 September 2011, was deployed to lead the efforts of the international community to reinforce the Libya-led transition and support the state rebuilding. Designed as a light-footprint mission, UNSMIL had an advisory and technical role.<sup>21</sup></p>
                            <p>The first head of UNSMIL, Ian Martin, acknowledged that the greatest failure was the lack of progress in security sector reform, which undermined the economic and political reconstruction efforts.<sup>22</sup> The limited results of the international assistance geared towards state-building could be attributed to the light-footprint approach of the international actors and the unrealistic design of the Libya stabilisation plan.<sup>23</sup></p>
                            <p>From 2014 to 2016, the Libyan state could not acquire legitimacy from its people and nearly stopped receiving international financial assistance channelled towards state building.<sup>24</sup> The armed confrontation that broke out in the summer of 2014 between the Karama (Dignity) coalition and the Fair Libya (Libya Dawn) coalition threw the country into chaos and pushed international actors, particularly the European Union, to stop its state-building efforts and focus more on a crisis described as a “crisis for Europe” — namely, human trafficking and smuggling of migrants — re-shaping its response accordingly.<sup>25</sup></p>
                            <p>From 2012 to 2014, the major recipient of international assistance was the public sector. This pattern shifted dramatically after 2014. International actors preferred funding civil society organisations (CSOs), given the crisis of legitimacy with two parliaments, two governments and a raging war on the ground.</p>
                            <p>By 2014, the intense armed confrontation accelerated the worsening of living conditions, including food, water and fuel shortages, a liquidity crunch and increased criminal activities in both the east and the west of Libya. Due to the deteriorating humanitarian situation in Libya, the funding for humanitarian assistance equalled the financial assistance channelled to security, peace and government programmes. Thus, the focus of international donors moved away from the necessary structural and institutional changes for the purpose of stabilisation,<sup>26</sup> and towards to humanitarian aid and peace- building assistance.</p>
                            <p>The country’s political elite, decision-makers and tribal leaders share significant responsibility for the political and state failure. They squandered public funds and undermined the trust that the Libyan people put in the new democratic institutions. In 2013, a national poll showed that support for democracy between May and November 2013 was high and stable (around 80%) while support for parliament declined from 63% to 31% during the same period. Similarly, the Libyans who believed that political parties are important in a democracy fell from 86% to 53%.<sup>27</sup> These figures translated into an 18% turnout in the June 2014 House of Representatives (HoR) elections, constituting a sharp decline from a 50% in the July 2012 General National Congress (GNC) elections.<sup>28</sup> The result has been a vicious circle of de facto leaders and institutions claiming legitimacy and a country locked in a protracted political conflict, feeding an environment where apathy is a dominant feature.</p>
                            <p>Furthermore, significant groups of the population were excluded from the political process.<sup>29</sup>  Women and youth remained underrepresented in parliament, government, municipalities and decision-making positions. They were marginalised as a result of tribal and geographical nepotism, political polarisation, militia hegemony over political and economic spheres, and a culture of negotiating behind closed doors.  Other groups were explicitly excluded by law, first by virtue of the Political Isolation Law, and second through a February 2014 law that incriminateds multiple expressions of dissent on the basis that they could constitute a defencse of Gaddafi or his regime.</p>
                            <p>Amidst the chaos, a resilient civil society took it upon itself to uphold the idea of a democratic transition. A network of CSOs continued to work in Libya despite the 2014 civil war, while several NGOs suspended their activities and many activists left the country.<sup>30</sup> Others had relocated to Tunisia and operated from across the border.</p>
                            <p>The period extending from May 2014 to December 2018 was characteriszed by tensions, violence, economic decline, loose political-military coalitions and meddling by other states.<sup>31</sup> In December 2015, the UN-brokered Libyan Political Agreement (LPA) was signed in Skhirat, Morocco, whereby an inclusive Government of National Accord (GNA) was established, but it did not result in the desired stabilisation. The effectiveness and power of the GNA-led ministries were limited, particularly in their ability to resolve the country’s ailing economy. The cash crisis —– driven by inflation and a thriving black market linked to armed groups —– persisted and power outages were the norm. Fuel and food subsidies strained the state budget and cost the statecountry hundreds of millions of USD per annum. The payments made by the Central Bank of Libya to the former revolutionary fighters (thuwwar), and the financing of two governments added to Libya’s economic woes. </p>
                            <p>According to the World Bank, the protracted conflict took a heavy toll on the economy and the well-being of the people. With oil being the main source of revenues for Libya, oil production declined to 0.38 million barrels per day in 2016, which is less than a quarter of the pre-2011 levels and less than 15% of its 2012 levels. As a result, the economy shrank by 2.5% in 2016 and the real GDP sharply declined by more than 50% as compared to its pre-2011 levels. Furthermore, the economy suffered a massive recession in 2016. Inflation substantially increased, leading to the erosion of real incomes. Some 1.3 million people were left with no access to life-saving healthcare.<sup>32</sup></p>
                            <ol class="footnotes__list">
                                <li> Alex. J. Bellamy and Paul D. P.Williams, “The new politics of protection? Cô.te d’Ivoire, Libya and the responsibility to protect”, International Affairs, Vol. 87, No. (4 (), July 2011),: pp. 825-850.</li>
                                <li>Irene Costantini, “I. ‘After Regime Change, Wwhat? The Mmissed Opportunity of State Building in Libya”,’. iIn  ed. Varveli, A. “State- Building in Libya: Integrating Diversities, Traditions and Citizenship, ed. Arturo Varveli (Rome: Reset-Dialogues on Civilization, 2017). ”</li>
                                <li> United Nations General Assembly, “Estimates in respect of special political missions, good offices and other political initiatives authorized by the General Assembly and/or the Security Council”, Report of the Secretary General, 17 October 2014 (A/69/363).</li>
                                <li> House of Commons, Foreign Affairs Committee, “Libya: Eexamination of intervention and collapse and the UK’s future policy options”, . Third Report of Session 2016-17,. Foreign Affairs Committee, 2016, p. 24. <a href="https://publications.parliament.uk/pa/cm201617/cmselect/cmfaff/119/119.pdf">click</a> (16 May 2019)</li>
                                <li> House of CommonsHouse of Commons Foreign Affairs Committee, “Libya: examination of intervention and collapse and the UK’s future policy options”. Third Report of Session 2016-17. Foreign Affairs Committee, 2016, p. 26.</li>
                                <li> House of Commons Foreign Affairs Committee, “Libya: examination of intervention and collapse and the UK’s future policy options”, p. 26.</li>
                                <li> Kateryna. Ivashchenko-Stadnik, Roman PetrovP. Roman, Luca. Rainieri, R. Pernille Rieker, Alessandra. Russo, and F.rancesca Strazzari, “How the EU is facing crises in its neighbourhood:, Evidence from Libya and Ukraine”,. EUNPACK paper, 2017.</li>
                                <li> Costantini, I.Costantini, “After Regime Change, What?”</li>
                                <li>  National Democratic Institute (NDI) and JMW Consulting, March 2014, “Committed to Democracy and Unity: Public Opinion Survey in Libya”, National Democratic Institute (NDI) and JMW Consulting, March 2014. <a href="https://www.ndi.org/sites/default/files/Libya-Committed-to-Democracy-and-Unity-ENG.pdf">click</a> (16 May 2019). </li>
                                <li> Mustafa Fetouri, “Poor election turnout sign of Libya’s despair”, Al Monitor, 30 June 2014. <a href="https://www.al-monitor.com/pulse/originals/2014/06/libya-elections-democracy-transition-chaos-war.html">click</a> (16 May 2019)</li>
                                <li> Essan Mohamed, “Libyan Tawerghans dDelay rReturn as Gaddafi-era tTensions rRemain,”, Al Bawaba, 26 June 26, 2013, <a href="https://www.albawaba.com/news/libyan-tawerghans-delay-return-gaddafi-era-tensions-remain-502211">click</a>  (16 May 2019)*</li>
                                <li> Jean-Louis Romanet Perroux, “Libya’s Untold Story: Civil Society Amid Chaos”, Middle East Brief, No. 93, May 2015, Crown Center for Middle East Studies, Brandeis University. <a href="https://www.brandeis.edu/crown/publications/meb/MEB93.pdf">click</a> (16 May 2019)</li>
                                <li> Christopher M. Blanchard, "Libya: Transition and U.S. Policy”, Congressional Research Service, 2 May 2018. <a href="https://fas.org/sgp/crs/row/RL33142.pdf">click</a> (16 May 2019). </li>
                                <li> World Bank, “Libya’s Economic Outlook — April 2017”, Washington, D.C., 2017. <a href="http://www.worldbank.org/en/country/libya/publication/economic-outlook-april-2017">click</a></li>
                            </ol>
                        </div>
                        <div class="top-line__btn-line-right"></div>
                    </div>
                    <div class="top-line__heading">
                        <div class="top-line__date">2014-2016</div>
                        <div class="top-line__heading-bold">Analysis</div>
                    </div>
                    <div class="top-line__heading-big">
                        2014-2016 <span class="top-line__heading-text"></span>
                    </div>
                    <div class="top-line__bracket  top-line__bracket--right"><?php echo file_get_contents("parts/svg/bracket-right.svg"); ?></div>
                </div>
            </div>
        </div>
        <div class="line__segment line__segment--top"></div>
        <div class="line__segment line__segment--top"></div>
        <div class="line__segment line__segment--top">
            <div class="top-line__btn-wrapper">
                <div class="top-line__btn" data-btn="8">
                    <div class="top-line__bracket top-line__bracket-left"><?php echo file_get_contents("parts/svg/bracket-left.svg"); ?></div>
                    <div class="top-line__text-wrapper">
                        <div class="top-line__btn-line-left"></div>
                        <div class="top-line__text">
                            <p>When violence broke out in the South of Libya in 2017, Fayez al-Sarraj, Chairman of the Presidency Council and Prime Minister of the Government of National Accord, called upon the international community to intervene in order to put a and stop to the deteriorating security situation in the country. The call was rejected domestically by the House of Representatives and failed to generate traction internationally. Martin Kobler, the former Special Representative of the Secretary General and the Chief of the UN Support Mission in Libya (UNSMIL), commented that the international community “is keen on having no military intervention as an option to end Libya’s crisis, but rather will always push for dialogue as the only solution.”.<sup>33</sup></p>
                            <p>As fears were growing that another violent confrontation was about to happen, hopes of peace were renewed when the GNA Prime Minister Fayez al-Sarraj and Field Marshal Khalifa Haftaer of the Libyan National Army met in Dubai in May 2017 and July 2017 to agree on a ceasefire and elections to take place over the subsequent year.  In September 2017, the UN introduced a new Action Plan and facilitated talks on reducing the size of the GNA’s Presidential Council (PC) from nine to three and to introduce changes to the mandates of the legislature and the executive authorities. Eventually, the negotiating parties made some progress but failed to reach an agreement on the sequencing of the referendum and the elections. </p>
                            <p>In December 2017, the UN Security Council described the Libyan Political Agreement (LPA) as “the only viable framework to end the Libyan political crisis”.<sup>34</sup> Yet, Haftaer and the Libyan people had different opinions on the matter. Haftaer challenged the legitimacy of the LPA and its associated institutions, invokingciting the expiry of its term as the reason, therefore, the LPA-associated institutions were no longer legitimate. He called for elections, rejecting the subordination of the LNA to “any side regardless of its source of legitimacy” unless such body iswere elected by the Libyan people.<sup>35</sup> Neither elections nor the constitutional referendum took place in 2018. The fears of a unilateral military measure by Haftaer materialiszed in 2019 as the LNA moved militarily on the wWestern region. </p>
                            <p>Public confidence in the GNA continued to plummet throughout 2017. According to a 2017 poll conducted by IFES, seventy-four percent74% of Libyans had  very little to no confidence at all in the GNA. In the country’s wWest and Tripoli, confidence in the GNA wasstood at 25% and 15% respectively, while in the eEast and South it was 1% and 20% respectively.<sup>36</sup> Fifty-five percent  of Libyans favoured to postponinge the constitutional referendum and elections for a new interim president, while 24% supported a constitutional referendum based on the latest draft.<sup>37</sup></p>
                            <p>In 2018, another poll by IFES demonstrated an improved public confidence in the GNA and an increased support tofor holding a referendum before any other milestone. While the improvement in GNA confidence in the east was small (from 1 to 4%), it was pronounced in Tripoli (from 15% to 39%).<sup>38</sup> The percentage of Libyans who supported postponement of the referendum and elections decreased to 44%, while those wanting an immediate referendum almost doubled, to a hefty 42%.<sup>39</sup> Although these figures may have reflected the views of the civilian population, power elites have continued to have the upper hand on the course of the country’s future.</p>
                            <p>Despite the failure to set dates and a sequence for the elections and referendum, Libya’s High National Elections Commission (HNEC) set in motion the preparations for polls. By March 2018, a total of 2.4 million voters were registered, which is roughly 53% of the total number of eligible voters in Libya. Preparations hit a deadlock against the backdrop of  the growing political fissures and violence. </p>
                            <p>The institutional setup for the LPA was not working.<sup>40</sup> The UN-backed dialogue led to the reorganisation of power centres around the GNA, led by al-Sarraj and Khalifa Haftaer, head of the LNA.<sup>41</sup> There was an expectation that the political representatives involved in the LPA would  bring their armed and civilian constituencies to support the dialogue outcomes, t. Thus, representatives of armed groups were not invited to partakeparticipate in the negotiations.<sup>42</sup> This assumption not only proved wrong, but also caused serious security and legitimacy repercussions. </p>
                            <p>The GNA’s international legitimacy did not compensate for its lack of control over military forces to project power, which could have granted it an actual authority on the ground. This meant, that al-Sarraj needed to negotiate with armed groups controlling the capital, such as Misrata’s Halbus, and part of the Mahjub brigades and the Islamist militias, including the Special Deterrence Force,<sup>43</sup> so that the PC cancould operate from Tripoli. Most of the militias ended up backing the GNA and the PC for purely self-serving reasons.<sup>44</sup> By mid- 2018, the militias backing the GNA played a dubious economic role, blurring legitimate and illegitimate activities. They diverted public funds throughby pressuring managers of commercial banks and manipulated letters of credit to finance their activities. Meanwhile, the GNA stood powerless unable to stop them. In short, they sought to protect their own economic interests and grow their influence over the political institutions.<sup>45</sup></p>
                            <ol class="footnotes__list">
                                <li> “Kobler meets Al-Serraj in Tripoli to discuss political process", Libya Express, 26 April 2017. <a href="http://www.libyanexpress.com/kobler-meets-al-serraj-in-tripoli-to-discuss-political-process/">click</a> (16 May 2019)</li>
                                <li> UN Security Council, "Statement of the President on the Situation in Libya", S/PRST/2017, New York, NY, 14 December 14, 2017. <a href="https://undocs.org/S/PRST/2017/26">click</a> (16 May 2019)</li>
                                <li> France 24, “Libya: Chief Commander Khalifa Hafter Considers Skhirat Agreement Expired”,. France 2417 . December  17, 2017. <a href="https://www.france24.com/ar/20171217-ليبيا-خليفة-حفتر-اتفاق-الصخيرات-المغرب-حكومة-الوفاق-الوطني-منتهي-الصلاحية">click</a></li>
                                <li> IFES, U.S. Agency for International Development, “Public Opinion Poll in Libya 2017”, Washington, D.C.   <a href="https://www.ifes.org/sites/default/files/public_opinion_in_libya_2017_english.pdf">click</a> (16 May 2019)</li>
                                <li> Ibid"Public Opinion Poll in Libya 2017”. </li>
                                <li> Confidence in the GNA amounted to 24% in the South, 32% in the West, with a noted increase of 4 and 7% increase respectively compared to 2017. See U.S. Agency for International Development, “IFES Survey on Voters’ Intent: Libya, a nationwide survey exploring public opinion of the political situation in Libya and voter intentions to participate in future elections”,  August 2018. <a href="https://www.ifes.org/sites/default/files/ifes_2018_survey_on_voters_intent_libya.pdf">click</a> (16 May 2019)</li>
                                <li> "IFES Survey on Voters’ Intent: Libya, a nationwide survey exploring public opinion of the political situation in Libya and voter intentions to participate in future elections <a href="https://www.ifes.org/sites/default/files/ifes_2018_survey_on_voters_intent_libya.pdf">click</a>”.</li>
                                <li> Wolfram Lacher, W. 2018, ‘“Libya: Getting Sserious Aabout Nnegotiations: Hhow a Nnew Ppolitical Pprocess Ccould H help Ttackle Ssecurity Cchallenges”’, SWP Comment, No. 39, October :2018, German Institute for International and Security Affairs. . Berlin <a href="https://www.swp-berlin.org/fileadmin/contents/products/comments/2018C39_lac.pdf">click</a> (16 May 2019). </li>
                                <li> Rasmus Alenius Boserup and Virginie Collombier, “Militarization and Militia-ization: Dynamics of Armed Group Proliferation in Egypt and Libya”, Istituto Affari Internazionali (IAI), Rome, October 2018. <a href="https://www.iai.it/en/pubblicazioni/militarization-and-militia-ization-dynamics-armed-group-proliferation-egypt-and-libya">click</a> (16 May 2019)’. </li>
                                <li>  Lacher, “Libya: Getting Serious About Negotiations”.</li>
                                <li> Boseru, R.A, & Collombier, V. 2018Boserup and Collombier, “Militarization and Militia-ization”.</li>
                                <li> Wolfram Lacher,W. 2018  “Tripoli’s Militias Cartel:. How Ill-Conceived Stabilisation Blocks Political Progress, and Risks Renewed War”, in SWP Comments, No. 20, April 201818/20 (May), German Institute for International and Security Affairs. <a href="https://www.swp-berlin.org/en/publication/libya-tripolis-militia-cartelhttps://www.swp-berlin.org/fileadmin/contents/products/comments/2018C20_lac.pdf">click</a> (16 May 2019)</li>
                                <li> Boseru, R.A, & Collombier, V. 2018, ‘Militarization and Militia-Ization: Dynamics of Armed Group Proliferation in Egypt and Libya’.Boserup and Virginie Collombier, “Militarization and Militia-ization”.</li>
                            </ol>
                        </div>
                        <div class="top-line__btn-line-right"></div>
                    </div>
                    <div class="top-line__heading">
                        <div class="top-line__date">2017-2018</div>
                        <div class="top-line__heading-bold">Analysis</div>
                    </div>
                    <div class="top-line__heading-big">
                        2017-2018 <span class="top-line__heading-text"></span>
                    </div>
                    <div class="top-line__bracket  top-line__bracket--right"><?php echo file_get_contents("parts/svg/bracket-right.svg"); ?></div>
                </div>
            </div>
        </div>
        <div class="line__arrow line__arrow--top"><?php echo file_get_contents("parts/caret.svg"); ?></div>
    </div>
</div>
<div class="top-line__overlay">
    <div class="btn-popup__close">
        <div class="btn-popup__cross">
            <span class="btn-popup__cross-line"></span>
            <span class="btn-popup__cross-line"></span>
        </div>
    </div>
</div>
